'use client';

import {Check,Clock3,MapPin,PackageCheck,Truck,XCircle} from 'lucide-react';
import {useEffect,useMemo,useState} from 'react';

const STEPS=[{key:'new',label:'Commande reçue'},{key:'preparing',label:'En préparation'},{key:'ready',label:'Prête'},{key:'out_for_delivery',label:'En cours de livraison'},{key:'completed',label:'Livrée'}];
const RANK:Record<string,number>={new:0,preparing:1,ready:2,out_for_delivery:3,completed:4};

export default function DeliveryTrackingPage({params}:{params:Promise<{token:string}>}){
  const [token,setToken]=useState('');const [data,setData]=useState<any>(null);const [error,setError]=useState('');const [now,setNow]=useState(Date.now());
  useEffect(()=>{params.then(p=>setToken(String(p.token||'')))},[params]);
  useEffect(()=>{if(!token)return;let stopped=false;let timer:any;const load=async()=>{try{const r=await fetch(`/api/delivery/track/${encodeURIComponent(token)}`,{cache:'no-store'});const j=await r.json();if(!r.ok)throw new Error();if(!stopped){setData(j.tracking);setError('');setNow(Date.now())}}catch{if(!stopped)setError('Ce lien de suivi est introuvable ou n’est plus disponible.')}};void load();timer=setInterval(load,4500);return()=>{stopped=true;clearInterval(timer)}},[token]);
  const status=String(data?.status||'new');const current=RANK[status]??0;const live=status==='out_for_delivery'&&data?.is_active&&Number.isFinite(Number(data?.current_lat))&&Number.isFinite(Number(data?.current_lng));
  const coords=useMemo(()=>live?`${Number(data.current_lat)},${Number(data.current_lng)}`:'',[live,data?.current_lat,data?.current_lng]);
  const mapSrc=coords?`https://maps.google.com/maps?q=${encodeURIComponent(coords)}&z=16&output=embed`:'';const mapLink=coords?`https://www.google.com/maps?q=${encodeURIComponent(coords)}`:'#';
  if(error)return <main className="delivery-track-page"><section className="delivery-track-card error"><XCircle/><h1>Suivi indisponible</h1><p>{error}</p></section></main>;
  if(!data)return <main className="delivery-track-page"><section className="delivery-track-card loading"><div className="delivery-loader"/><p>Chargement de votre commande…</p></section></main>;
  return <main className="delivery-track-page"><section className="delivery-track-card"><header className="delivery-customer-head"><div className="delivery-brand"><img src="/qatalink-icon.svg" alt="Qatalink"/><span>Suivi de livraison</span></div><span className={`delivery-status-chip status-${status}`}>{status==='new'?'Reçue':status==='preparing'?'En préparation':status==='ready'?'Prête':status==='out_for_delivery'?'En livraison':status==='completed'?'Livrée':status==='cancelled'?'Annulée':status}</span></header><div className="delivery-order-title"><span>{data.business_name}</span><h1>{data.order_number}</h1>{data.delivery_address&&<p><MapPin/> {data.delivery_address}</p>}</div>{status==='cancelled'?<div className="delivery-cancelled"><XCircle/><div><b>Commande annulée</b><span>Contactez l’établissement si vous avez besoin d’informations.</span></div></div>:<div className="delivery-steps">{STEPS.map((step,index)=>{const done=current>index||status==='completed',active=current===index;return <div className={`${done?'done':''} ${active?'active':''}`} key={step.key}><span>{done?<Check/>:index+1}</span><div><b>{step.label}</b>{active&&<small>{step.key==='out_for_delivery'?'Votre livreur est en route.':'Étape actuelle'}</small>}</div></div>})}</div>}{live?<div className="delivery-live-map"><div className="delivery-map-head"><div><Truck/><div><b>Livreur en déplacement</b><span>Position mise à jour automatiquement</span></div></div>{data.driver_label&&<em>{data.driver_label}</em>}</div><iframe title="Position du livreur" src={mapSrc} loading="lazy" referrerPolicy="no-referrer-when-downgrade"/><footer><div><Clock3/><span>{data.last_location_at?`Mise à jour ${new Date(data.last_location_at).toLocaleTimeString('fr-FR')}`:'En attente de position'}</span></div><a href={mapLink} target="_blank" rel="noreferrer">Ouvrir la carte</a></footer></div>:status==='out_for_delivery'?<div className="delivery-awaiting"><Truck/><div><b>Le livreur est en route</b><span>La carte apparaîtra dès que son téléphone transmettra une position.</span></div></div>:status==='completed'?<div className="delivery-completed"><PackageCheck/><div><b>Livraison terminée</b><span>Merci pour votre commande.</span></div></div>:null}<p className="delivery-auto-note">Actualisation automatique · {new Date(now).toLocaleTimeString('fr-FR',{hour:'2-digit',minute:'2-digit'})}</p></section></main>;
}
