'use client';

import {CheckCircle2,LocateFixed,MapPin,Navigation,Radio,Route,ShieldCheck} from 'lucide-react';
import {useEffect,useRef,useState} from 'react';

function validCoords(lat:any,lng:any){const a=Number(lat),b=Number(lng);return Number.isFinite(a)&&Number.isFinite(b)&&a>=-90&&a<=90&&b>=-180&&b<=180&&!(Math.abs(a)<1e-8&&Math.abs(b)<1e-8)}

export default function DriverTrackingPage({params}:{params:Promise<{token:string}>}){
  const [token,setToken]=useState('');const [active,setActive]=useState(false);const [message,setMessage]=useState('Prêt à partager la position.');const [last,setLast]=useState<any>(null);const [busy,setBusy]=useState(false);const [delivery,setDelivery]=useState<any>(null);const watchRef=useRef<number|null>(null);const lastSent=useRef(0);
  useEffect(()=>{params.then(p=>setToken(String(p.token||'')))},[params]);
  useEffect(()=>{if(!token)return;let stopped=false;fetch(`/api/delivery/driver?token=${encodeURIComponent(token)}`,{cache:'no-store'}).then(async r=>{const j=await r.json().catch(()=>({}));if(!stopped&&r.ok)setDelivery(j.delivery)}).catch(()=>{});return()=>{stopped=true}},[token]);
  useEffect(()=>()=>{if(watchRef.current!==null&&navigator.geolocation)navigator.geolocation.clearWatch(watchRef.current)},[]);
  async function sendLocation(position:GeolocationPosition){const now=Date.now();if(now-lastSent.current<4500)return;lastSent.current=now;const c=position.coords;if(!validCoords(c.latitude,c.longitude)){setMessage('Position GPS non valide. Attendez un signal plus précis.');return}setLast({lat:c.latitude,lng:c.longitude,accuracy:c.accuracy,at:new Date()});try{const r=await fetch('/api/delivery/driver',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({token,action:'location',lat:c.latitude,lng:c.longitude,accuracy:c.accuracy,heading:c.heading,speed:c.speed}),cache:'no-store'});if(!r.ok)throw new Error();setMessage('Position transmise à Qatalink.')}catch{setMessage('Impossible d’envoyer la position. Vérifiez votre connexion.')}}
  function start(){if(!token||!navigator.geolocation){setMessage('La géolocalisation n’est pas disponible sur cet appareil.');return}setMessage('Autorisez la localisation précise pour démarrer.');const id=navigator.geolocation.watchPosition(p=>{if(validCoords(p.coords.latitude,p.coords.longitude))setActive(true);void sendLocation(p)},e=>{setActive(false);setMessage(e.code===1?'Autorisation de localisation refusée.':'Position indisponible. Activez le GPS et réessayez.')},{enableHighAccuracy:true,maximumAge:3000,timeout:15000});watchRef.current=id}
  function stop(){if(watchRef.current!==null){navigator.geolocation.clearWatch(watchRef.current);watchRef.current=null}setActive(false);setMessage('Partage de position en pause.')}
  async function complete(){if(!token||busy)return;if(!confirm('Confirmer que la commande a été livrée ?'))return;setBusy(true);try{const r=await fetch('/api/delivery/driver',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({token,action:'complete'}),cache:'no-store'});if(!r.ok)throw new Error();stop();setMessage('Commande marquée comme livrée. Merci !')}catch{setMessage('Impossible de terminer la livraison.')}finally{setBusy(false)}}
  const maps=last?`https://www.google.com/maps?q=${last.lat},${last.lng}`:'#';
  const destination=validCoords(delivery?.customer_lat,delivery?.customer_lng)?`${Number(delivery.customer_lat)},${Number(delivery.customer_lng)}`:String(delivery?.delivery_address||'').trim();
  const routeUrl=destination?`https://www.google.com/maps/dir/?api=1&destination=${encodeURIComponent(destination)}&travelmode=driving&dir_action=navigate`:'#';
  return <main className="delivery-driver-page"><section className="delivery-driver-card"><div className="delivery-brand"><img src="/qatalink-icon.svg" alt="Qatalink"/><span>Qatalink Livraison</span></div><div className={`delivery-live-orb ${active?'active':''}`}>{active?<Radio/>:<Navigation/>}</div><h1>{active?'Position partagée en direct':'Démarrer le suivi livreur'}</h1><p>Cette page transmet uniquement votre position pendant la livraison afin que le client puisse suivre l’avancement.</p>{delivery&&<div className="delivery-driver-status" style={{marginBottom:'12px'}}><span className="on">DESTINATION</span><b>{delivery.delivery_address||'Position GPS du client'}</b>{delivery.order_number&&<small>Commande {delivery.order_number}</small>}{destination&&<a className="delivery-map-link" href={routeUrl} target="_blank" rel="noreferrer"><Route/>Ouvrir l’itinéraire vers le client</a>}</div>}<div className="delivery-driver-status"><span className={active?'on':'off'}>{active?'GPS actif':'GPS inactif'}</span><b>{message}</b>{last&&<small>Dernière position : {last.at.toLocaleTimeString('fr-FR')} · précision ≈ {Math.round(last.accuracy)} m</small>}</div>{last&&<a className="delivery-map-link" href={maps} target="_blank" rel="noreferrer"><MapPin/>Voir ma position</a>}<div className="delivery-driver-actions">{active?<button className="secondary" onClick={stop}><LocateFixed/>Mettre en pause</button>:<button className="primary" onClick={start}><LocateFixed/>Partager ma position</button>}<button className="success" disabled={busy} onClick={complete}><CheckCircle2/>{busy?'Validation…':'Commande livrée'}</button></div><div className="delivery-privacy"><ShieldCheck/><span>Le lien livreur est privé. La position n’est affichée au client que pendant une livraison Business active.</span></div></section></main>;
}
