'use client';

import {useEffect,useMemo,useState} from 'react';
import {Bike,BadgeCheck,ChevronRight,KeyRound,ShoppingBag,Trash2,Users} from 'lucide-react';
import {createSupabaseBrowserClient} from '@/lib/supabase';

type Owned={id:string;name:string};
type Mission={driver_token:string;order_number:string;status:string;delivery_address:string|null;started_at:string|null;delivered_at:string|null;last_location_at:string|null};
type SavedTeam={key:string;pin:string;label:string;business?:string;catalog?:string;lastUsedAt:number};
const LABEL:Record<string,string>={client:'Client',pro:'Pro',team:'Équipe',driver:'Livreur'};
const TEAM_STORE='qatalink_saved_team_accesses';

function parseTeamKey(raw:string){
 const value=raw.trim();if(!value)return'';
 try{const url=new URL(value);const match=url.pathname.match(/^\/ops\/([^/?#]+)/);if(match)return decodeURIComponent(match[1])}catch{}
 const path=value.match(/(?:^|\/)ops\/([^/?#]+)/);if(path)return decodeURIComponent(path[1]);
 return value.replace(/^\/+|\/+$/g,'');
}
function readSavedTeam():SavedTeam[]{try{const raw=JSON.parse(localStorage.getItem(TEAM_STORE)||'[]');return Array.isArray(raw)?raw.filter(x=>x&&x.key&&x.pin):[]}catch{return[]}}
function writeSavedTeam(entries:SavedTeam[]){try{localStorage.setItem(TEAM_STORE,JSON.stringify(entries.slice(0,12)))}catch{}}

export default function MobileEntry(){
 const supabase=useMemo(()=>createSupabaseBrowserClient(),[]);
 const [owned,setOwned]=useState<Owned[]>([]),[signed,setSigned]=useState(false),[ready,setReady]=useState(false),[mode,setMode]=useState('client'),[missions,setMissions]=useState<Mission[]>([]);
 const [teamKey,setTeamKey]=useState(''),[teamPin,setTeamPin]=useState(''),[savedTeam,setSavedTeam]=useState<SavedTeam[]>([]),[teamBusy,setTeamBusy]=useState(false),[teamError,setTeamError]=useState('');
 const [driverNotice,setDriverNotice]=useState('');
 useEffect(()=>{setSavedTeam(readSavedTeam());void(async()=>{const {data:{session}}=await supabase.auth.getSession();setSigned(!!session);if(session){const queryMode=new URLSearchParams(location.search).get('access_mode');let pending='';try{pending=localStorage.getItem('qatalink_pending_access_mode')||''}catch{};const requested=queryMode||pending;const {data:p}=await supabase.from('profiles').select('access_mode').eq('id',session.user.id).maybeSingle();let primary=String(p?.access_mode||session.user.user_metadata?.access_mode||'client');if(requested&&['client','pro','team','driver'].includes(requested)){await supabase.rpc('set_my_access_mode',{p_mode:requested});primary=requested;try{localStorage.removeItem('qatalink_pending_access_mode')}catch{}}setMode(primary);const [{data:b},{data:m}]=await Promise.all([supabase.from('businesses').select('id,name').eq('owner_user_id',session.user.id).order('created_at',{ascending:true}),supabase.rpc('my_driver_deliveries')]);setOwned((b||[]) as Owned[]);setMissions((m||[]) as Mission[])}setReady(true)})()},[supabase]);
 async function activate(next:string,url?:string){if(!signed){try{localStorage.setItem('qatalink_pending_access_mode',next)}catch{};location.href=`/login?mode=signup&access=${next}&next=/mobile`;return}await supabase.rpc('set_my_access_mode',{p_mode:next});setMode(next);if(url)location.href=url}
 async function connectTeam(){const key=parseTeamKey(teamKey),pin=teamPin.trim();setTeamError('');if(!key||!pin){setTeamError('Saisissez le lien ou la clé d’accès, puis le PIN transmis par le responsable.');return}setTeamBusy(true);try{const response=await fetch('/api/ops/orders',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({access_key:key,pin,action:'list',limit:1}),cache:'no-store'});const data=await response.json().catch(()=>({}));if(!response.ok)throw new Error(data?.error||'ACCESS_DENIED');const entry:SavedTeam={key,pin,label:String(data?.access?.label||'Accès équipe'),business:String(data?.catalog?.business_name||''),catalog:String(data?.catalog?.title||''),lastUsedAt:Date.now()};const next=[entry,...readSavedTeam().filter(x=>x.key!==key)];writeSavedTeam(next);setSavedTeam(next);try{sessionStorage.setItem(`qatalink_ops_pin_${key}`,pin);localStorage.setItem('qatalink_last_team_key',key)}catch{};if(signed)await supabase.rpc('set_my_access_mode',{p_mode:'team'});location.href=`/ops/${encodeURIComponent(key)}`}catch{setTeamError('Accès refusé. Vérifiez le lien/clé et le PIN de cet accès. Votre mot de passe Qatalink n’est pas le PIN équipe.')}finally{setTeamBusy(false)}}
 function openSaved(entry:SavedTeam){try{sessionStorage.setItem(`qatalink_ops_pin_${entry.key}`,entry.pin);localStorage.setItem('qatalink_last_team_key',entry.key)}catch{};const next=[{...entry,lastUsedAt:Date.now()},...readSavedTeam().filter(x=>x.key!==entry.key)];writeSavedTeam(next);location.href=`/ops/${encodeURIComponent(entry.key)}`}
 function removeSaved(key:string){const next=readSavedTeam().filter(x=>x.key!==key);writeSavedTeam(next);setSavedTeam(next)}
 async function driver(){if(!signed){await activate('driver');return}await supabase.rpc('set_my_access_mode',{p_mode:'driver'});setMode('driver');const mission=missions.find(m=>!m.delivered_at)||missions[0];let last='';try{last=localStorage.getItem('qatalink_last_driver_token')||''}catch{};const token=mission?.driver_token||last;if(token){location.href=`/livreur/${encodeURIComponent(token)}`;return}setDriverNotice('Mode livreur actif. Votre prochaine mission s’ouvrira automatiquement lorsque vous ouvrirez un lien de livraison Qatalink.')}
 const card=(icon:React.ReactNode,title:string,text:string,active:boolean,action:React.ReactNode)=><article style={{background:'#fff',border:active?'2px solid #c7192f':'1px solid #e7e7ea',borderRadius:20,padding:16,display:'grid',gap:12,minWidth:0,overflow:'hidden'}}><div style={{display:'flex',justifyContent:'space-between',gap:10}}><div style={{width:42,height:42,borderRadius:13,display:'grid',placeItems:'center',background:active?'#fff0f2':'#f3f3f5',flex:'0 0 auto'}}>{icon}</div>{active&&<span style={{height:'fit-content',padding:'5px 8px',borderRadius:999,background:'#fff0f2',color:'#c7192f',fontSize:10,fontWeight:900}}>PAR DÉFAUT</span>}</div><div style={{minWidth:0}}><h2 style={{margin:'0 0 5px',fontSize:20}}>{title}</h2><p style={{margin:0,opacity:.62,lineHeight:1.4,fontSize:13,overflowWrap:'anywhere'}}>{text}</p></div>{action}</article>;
 return <main style={{minHeight:'100dvh',background:'#f7f7f8',padding:'max(18px,env(safe-area-inset-top)) 14px max(28px,env(safe-area-inset-bottom))',fontFamily:'var(--font-jakarta),sans-serif',color:'#111',overflowX:'hidden'}}><section style={{maxWidth:620,margin:'0 auto',width:'100%',minWidth:0}}><header style={{display:'flex',alignItems:'center',gap:11,marginBottom:16}}><img src="/qatalink-icon.svg" alt="Qatalink" style={{width:42,height:42}}/><div style={{minWidth:0}}><b style={{fontSize:19}}>Qatalink</b><div style={{fontSize:12,opacity:.55,overflowWrap:'anywhere'}}>{signed?`Accès par défaut : ${LABEL[mode]||mode}`:'Choisissez votre espace'}</div></div></header><p style={{fontSize:12,opacity:.62,lineHeight:1.45,margin:'0 0 16px'}}>Un même compte peut utiliser plusieurs espaces. Les accès privés Équipe ont leur propre PIN, différent de votre mot de passe Qatalink.</p><div style={{display:'grid',gap:12}}>
 {card(<ShoppingBag size={21}/>,'Client','Mes adresses, Explorer et vos parcours de commande.',mode==='client',<button onClick={()=>void activate('client','/app')} style={buttonStyle}>Ouvrir l’espace client <ChevronRight size={17}/></button>)}
 {card(<BadgeCheck size={21}/>,'Pro',owned.length?`${owned.length} activité${owned.length>1?'s':''} reliée${owned.length>1?'s':''} à votre compte.`:'Créez et gérez catalogues, commandes, caisse et réglages utiles.',mode==='pro',<button disabled={!ready} onClick={()=>void activate('pro',owned.length?'/dashboard':'/create')} style={buttonStyle}>{signed?(owned.length?'Gérer mon activité':'Créer mon catalogue'):'Créer mon compte Pro'}<ChevronRight size={17}/></button>)}
 {card(<Users size={21}/>,'Équipe / Caisse / Cuisine','Un accès Caisse ou Cuisinier est un espace privé créé par le responsable. Il se rattache avec son lien/sa clé + son PIN, une seule fois sur cet appareil.',mode==='team',<div style={{display:'grid',gap:9}}>{savedTeam.length>0&&<div style={{display:'grid',gap:7}}>{savedTeam.map(entry=><div key={entry.key} style={{display:'grid',gridTemplateColumns:'minmax(0,1fr) auto',gap:7,alignItems:'stretch'}}><button onClick={()=>openSaved(entry)} style={{border:'1px solid #e1e1e5',background:'#fafafa',borderRadius:13,padding:'10px 11px',textAlign:'left',minWidth:0}}><b style={{display:'block',overflowWrap:'anywhere'}}>{entry.label}</b><small style={{display:'block',marginTop:2,opacity:.58,overflowWrap:'anywhere'}}>{[entry.business,entry.catalog].filter(Boolean).join(' · ')||'Accès enregistré'}</small></button><button onClick={()=>removeSaved(entry.key)} aria-label="Oublier cet accès" style={iconButton}><Trash2 size={16}/></button></div>)}</div>}<div style={{display:'grid',gridTemplateColumns:'1fr',gap:7,paddingTop:savedTeam.length?4:0}}><label style={miniLabel}>Lien ou clé d’accès<input value={teamKey} onChange={e=>setTeamKey(e.target.value)} placeholder="https://qatalink.com/ops/..." style={inputStyle}/></label><label style={miniLabel}>PIN de l’accès<input value={teamPin} onChange={e=>setTeamPin(e.target.value.replace(/\s/g,''))} inputMode="numeric" type="password" placeholder="PIN transmis par le responsable" style={inputStyle}/></label><button onClick={()=>void connectTeam()} disabled={teamBusy||!teamKey.trim()||!teamPin.trim()} style={buttonStyle}><span style={{display:'flex',alignItems:'center',gap:7}}><KeyRound size={16}/>{teamBusy?'Vérification…':'Connecter cet accès'}</span><ChevronRight size={17}/></button>{teamError&&<small style={{color:'#a61b31',lineHeight:1.35}}>{teamError}</small>}</div></div>)}
 {card(<Bike size={21}/>,'Livreur','Activez ce mode une fois. Les liens de livraison Qatalink ouvriront ensuite directement la mission et le suivi GPS.',mode==='driver',signed?<div style={{display:'grid',gap:8}}><button onClick={()=>void driver()} style={buttonStyle}>{missions.length?'Ouvrir ma mission':'Activer le mode livreur'}<ChevronRight size={17}/></button>{driverNotice&&<div style={{padding:10,borderRadius:12,background:'#eef9f2',color:'#17653d',fontSize:12,lineHeight:1.4}}>{driverNotice}</div>}{missions.length>0&&<div style={{display:'grid',gap:6}}>{missions.slice(0,5).map(m=><button key={m.driver_token} onClick={()=>location.href=`/livreur/${encodeURIComponent(m.driver_token)}`} style={{border:'1px solid #e5e5e8',background:'#fafafa',borderRadius:12,padding:10,textAlign:'left',minWidth:0}}><b>{m.order_number}</b><div style={{fontSize:11,opacity:.58,marginTop:3,overflowWrap:'anywhere'}}>{m.delivery_address||m.status}</div></button>)}</div>}</div>:<button onClick={()=>void driver()} style={buttonStyle}>Créer / ouvrir mon compte livreur <ChevronRight size={17}/></button>)}
 </div></section></main>
}
const buttonStyle:React.CSSProperties={width:'100%',border:0,borderRadius:14,padding:'12px 13px',background:'#111',color:'#fff',fontWeight:750,display:'flex',alignItems:'center',justifyContent:'space-between',gap:8,minWidth:0};
const inputStyle:React.CSSProperties={width:'100%',minWidth:0,border:'1px solid #dedee2',borderRadius:12,padding:'11px 12px',fontSize:13,outline:0,boxSizing:'border-box'};
const miniLabel:React.CSSProperties={display:'grid',gap:5,fontSize:11,fontWeight:800,color:'#555'};
const iconButton:React.CSSProperties={width:42,border:'1px solid #e1e1e5',background:'#fff',borderRadius:12,display:'grid',placeItems:'center'};
