'use client';

import {useEffect,useMemo,useState} from 'react';
import {Bike,BadgeCheck,ChevronRight,ShoppingBag,Users} from 'lucide-react';
import {createSupabaseBrowserClient} from '@/lib/supabase';
type Owned={id:string;name:string};type Mission={driver_token:string;order_number:string;status:string;delivery_address:string|null;started_at:string|null;delivered_at:string|null;last_location_at:string|null};
const LABEL:Record<string,string>={client:'Client',pro:'Pro',team:'Équipe',driver:'Livreur'};
export default function MobileEntry(){
 const supabase=useMemo(()=>createSupabaseBrowserClient(),[]);const [owned,setOwned]=useState<Owned[]>([]),[signed,setSigned]=useState(false),[ready,setReady]=useState(false),[mode,setMode]=useState('client'),[teamKey,setTeamKey]=useState(''),[missions,setMissions]=useState<Mission[]>([]);
 useEffect(()=>{try{setTeamKey(localStorage.getItem('qatalink_last_team_key')||'')}catch{};void(async()=>{const {data:{session}}=await supabase.auth.getSession();setSigned(!!session);if(session){const queryMode=new URLSearchParams(location.search).get('access_mode');let pending='';try{pending=localStorage.getItem('qatalink_pending_access_mode')||''}catch{};const requested=queryMode||pending;const {data:p}=await supabase.from('profiles').select('access_mode').eq('id',session.user.id).maybeSingle();let primary=String(p?.access_mode||session.user.user_metadata?.access_mode||'client');if(requested&&['client','pro','team','driver'].includes(requested)){await supabase.rpc('set_my_access_mode',{p_mode:requested});primary=requested;try{localStorage.removeItem('qatalink_pending_access_mode')}catch{}}setMode(primary);const [{data:b},{data:m}]=await Promise.all([supabase.from('businesses').select('id,name').eq('owner_user_id',session.user.id).order('created_at',{ascending:true}),supabase.rpc('my_driver_deliveries')]);setOwned((b||[]) as Owned[]);setMissions((m||[]) as Mission[])}setReady(true)})()},[supabase]);
 async function activate(next:string,url?:string){if(!signed){try{localStorage.setItem('qatalink_pending_access_mode',next)}catch{};location.href=`/login?mode=signup&access=${next}&next=/mobile`;return}await supabase.rpc('set_my_access_mode',{p_mode:next});setMode(next);if(url)location.href=url}
 function team(){const key=teamKey.trim();if(!key)return;try{localStorage.setItem('qatalink_last_team_key',key)}catch{};void activate('team',`/ops/${encodeURIComponent(key)}`)}
 const card=(icon:React.ReactNode,title:string,text:string,active:boolean,action:React.ReactNode)=><article style={{background:'#fff',border:active?'2px solid #c7192f':'1px solid #e7e7ea',borderRadius:22,padding:18,display:'grid',gap:12}}><div style={{display:'flex',justifyContent:'space-between',gap:10}}><div style={{width:44,height:44,borderRadius:14,display:'grid',placeItems:'center',background:active?'#fff0f2':'#f3f3f5'}}>{icon}</div>{active&&<span style={{height:'fit-content',padding:'5px 8px',borderRadius:999,background:'#fff0f2',color:'#c7192f',fontSize:11,fontWeight:900}}>PAR DÉFAUT</span>}</div><div><h2 style={{margin:'0 0 5px',fontSize:20}}>{title}</h2><p style={{margin:0,opacity:.62,lineHeight:1.45,fontSize:14}}>{text}</p></div>{action}</article>;
 return <main style={{minHeight:'100vh',background:'#f7f7f8',padding:'max(22px,env(safe-area-inset-top)) 16px 32px',fontFamily:'var(--font-jakarta),sans-serif',color:'#111'}}><section style={{maxWidth:620,margin:'0 auto'}}><header style={{display:'flex',alignItems:'center',gap:12,marginBottom:18}}><img src="/qatalink-icon.svg" alt="Qatalink" style={{width:44,height:44}}/><div><b style={{fontSize:20}}>Qatalink</b><div style={{fontSize:13,opacity:.55}}>{signed?`Accès par défaut : ${LABEL[mode]||mode}`:'Choisissez votre espace'}</div></div></header><p style={{fontSize:13,opacity:.62,lineHeight:1.5,margin:'0 0 18px'}}>Un compte peut utiliser plusieurs espaces. Votre choix principal détermine simplement l’accueil proposé en priorité.</p><div style={{display:'grid',gap:13}}>{card(<ShoppingBag size={22}/>,'Client','Mes adresses, Explorer et vos parcours de commande.',mode==='client',<button onClick={()=>void activate('client','/app')} style={buttonStyle}>Ouvrir l’espace client <ChevronRight size={17}/></button>)}{card(<BadgeCheck size={22}/>,'Pro',owned.length?`${owned.length} activité${owned.length>1?'s':''} reliée${owned.length>1?'s':''} à votre compte.`:'Créez et gérez catalogues, commandes, caisse et réglages utiles.',mode==='pro',<button disabled={!ready} onClick={()=>void activate('pro',owned.length?'/dashboard':'/create')} style={buttonStyle}>{signed?(owned.length?'Gérer mon activité':'Créer mon catalogue'):'Créer mon compte Pro'}<ChevronRight size={17}/></button>)}{card(<Users size={22}/>,'Équipe','Ouvrez l’accès transmis par le responsable ; vos permissions définissent ce que vous pouvez faire.',mode==='team',<div style={{display:'flex',gap:8}}><input value={teamKey} onChange={e=>setTeamKey(e.target.value)} placeholder="Clé d’accès équipe" style={inputStyle}/><button onClick={team} disabled={!teamKey.trim()} style={smallButton}>Ouvrir</button></div>)}{card(<Bike size={22}/>,'Livreur','Connectez-vous une fois. Quand vous ouvrez ensuite un lien de livraison Qatalink, la mission est rattachée à votre compte et le suivi GPS s’ouvre directement.',mode==='driver',signed?<div style={{display:'grid',gap:8}}><button onClick={()=>void activate('driver')} style={buttonStyle}>Activer le mode livreur <ChevronRight size={17}/></button>{missions.length>0&&<div style={{display:'grid',gap:6}}>{missions.slice(0,5).map(m=><button key={m.driver_token} onClick={()=>location.href=`/livreur/${encodeURIComponent(m.driver_token)}`} style={{border:'1px solid #e5e5e8',background:'#fafafa',borderRadius:13,padding:10,textAlign:'left'}}><b>{m.order_number}</b><div style={{fontSize:12,opacity:.58,marginTop:3}}>{m.delivery_address||m.status}</div></button>)}</div>}{!missions.length&&<small style={{opacity:.55}}>Aucune mission rattachée pour le moment. Ouvrez simplement le prochain lien Qatalink reçu.</small>}</div>:<button onClick={()=>void activate('driver')} style={buttonStyle}>Créer / ouvrir mon compte livreur <ChevronRight size={17}/></button>)}</div></section></main>
}
const buttonStyle:React.CSSProperties={width:'100%',border:0,borderRadius:15,padding:'12px 14px',background:'#111',color:'#fff',fontWeight:700,display:'flex',alignItems:'center',justifyContent:'space-between'};const smallButton:React.CSSProperties={border:0,borderRadius:14,padding:'0 14px',background:'#111',color:'#fff',fontWeight:700};const inputStyle:React.CSSProperties={minWidth:0,flex:1,border:'1px solid #dedee2',borderRadius:14,padding:'12px',fontSize:14,outline:0};
