import Link from 'next/link';

export const metadata={
  title:'Conditions Générales d’Utilisation — Qatalink',
  description:'Conditions Générales d’Utilisation du service Qatalink édité par Digital ADN.'
};

export default function TermsPage(){return <main className="legal-page"><div className="legal-shell">
  <div className="legal-top"><Link href="/" className="brand">← Qatalink</Link><span>Digital ADN</span></div>
  <header className="legal-hero"><div className="eyebrow">DOCUMENT JURIDIQUE</div><h1>Conditions Générales d’Utilisation</h1><p>Version du 19 août 2026 · Qatalink est édité et exploité par Digital ADN, service numérique basé en Côte d’Ivoire.</p></header>

  <section><h2>1. Objet</h2><p>Les présentes Conditions Générales d’Utilisation (« CGU ») encadrent l’accès et l’utilisation de Qatalink, une plateforme permettant notamment de créer, publier, personnaliser et partager des catalogues ou menus interactifs, de générer des QR codes, de recevoir ou transmettre des commandes, d’utiliser des fonctions de génération assistée par intelligence artificielle et, selon la formule souscrite, de gérer des équipes, des commandes et des stocks.</p></section>

  <section><h2>2. Éditeur du service</h2><p>Qatalink est exploité par <strong>Digital ADN</strong>, activité de services numériques opérant en Côte d’Ivoire. Les demandes relatives au service, au compte utilisateur ou aux présentes CGU peuvent être adressées via le support intégré à Qatalink.</p></section>

  <section><h2>3. Acceptation des CGU</h2><p>La création d’un compte, la souscription d’une formule ou l’utilisation de Qatalink implique l’acceptation des présentes CGU. L’utilisateur déclare disposer de la capacité nécessaire pour contracter et, lorsqu’il agit pour une entreprise ou une organisation, être autorisé à l’engager.</p></section>

  <section><h2>4. Compte et sécurité</h2><p>L’utilisateur doit fournir des informations exactes et maintenir ses informations de compte à jour. Il est responsable de la confidentialité de ses moyens d’accès, ainsi que des actions effectuées depuis son compte, sauf utilisation frauduleuse qui ne lui serait pas imputable. Toute suspicion d’accès non autorisé doit être signalée rapidement au support.</p></section>

  <section><h2>5. Essai gratuit</h2><p>Qatalink peut proposer un essai gratuit de 7 jours sans moyen de paiement préalable. Sauf indication contraire dans l’interface, l’essai débute à la création effective du premier catalogue. À son expiration, certaines fonctions d’édition peuvent être verrouillées. Le lien public peut bénéficier d’une période de grâce temporaire avant suspension. Les conditions visibles dans l’interface au moment de l’essai prévalent en cas d’évolution du produit.</p></section>

  <section><h2>6. Formules et limites</h2><p>Les fonctionnalités disponibles dépendent de la formule souscrite. À la date de la présente version, les offres publiques sont Starter, Pro et Business. Des plafonds de catalogues, des fonctions de commande, d’équipe, de page centrale, de stock, de génération ou d’autres limites techniques peuvent varier selon la formule. Les quotas et fonctionnalités affichés dans l’interface de souscription constituent la référence applicable au compte.</p><p>Digital ADN peut faire évoluer les caractéristiques des offres pour de nouvelles souscriptions ou renouvellements, sous réserve d’une information claire lorsque cette évolution affecte substantiellement une formule déjà payée.</p></section>

  <section><h2>7. Tarifs, facturation et paiements</h2><p>Les tarifs sont affichés en francs CFA ou dans toute autre devise proposée par Qatalink. Les formules mensuelles sont facturées selon leur période de souscription. Une formule annuelle peut être proposée avec une remise correspondant, au tarif actuel, à un mois offert par rapport à douze mensualités. Le prix total, la période concernée et les modalités de paiement sont indiqués avant validation.</p><p>Les paiements sont traités par un prestataire de paiement sécurisé. Digital ADN ne demande pas à l’utilisateur de transmettre directement dans Qatalink les données confidentielles complètes de sa carte bancaire ou de son portefeuille de paiement. Les remboursements, annulations et renouvellements sont traités conformément aux conditions affichées lors du paiement et aux règles impératives applicables.</p></section>

  <section><h2>8. Catalogues, commandes et relation avec les clients finaux</h2><p>Qatalink fournit un outil technique. Le professionnel utilisant Qatalink reste responsable des informations commerciales publiées dans son catalogue, notamment les prix, descriptions, disponibilités, taxes éventuelles, délais, conditions de livraison, réservations, prestations et obligations envers ses propres clients.</p><p>Digital ADN n’est pas partie au contrat conclu entre le professionnel et son client final du seul fait qu’une commande, une réservation ou une prise de contact transite par Qatalink ou WhatsApp. Le professionnel reste responsable de la préparation, de la livraison, de l’exécution et du service après-vente de ses produits ou prestations.</p></section>

  <section><h2>9. WhatsApp et services tiers</h2><p>Certaines formules permettent de rediriger une commande ou une conversation vers un service tiers tel que WhatsApp. L’utilisation de ce service tiers est également soumise à ses propres conditions. Qatalink ne contrôle pas la disponibilité, les règles ou les modifications apportées par ces services externes.</p></section>

  <section><h2>10. Page centrale et liens externes</h2><p>La formule qui inclut la page centrale Qatalink permet de regrouper plusieurs menus ou catalogues et, selon les réglages disponibles, des liens externes, réseaux sociaux, cartes ou moyens de contact. L’utilisateur est responsable des destinations qu’il ajoute et doit s’assurer qu’elles sont licites et sûres.</p></section>

  <section><h2>11. Gestion de stock</h2><p>Lorsque la gestion de stock est disponible, les déductions automatiques sont calculées à partir des liaisons et quantités configurées par l’utilisateur. Ces calculs constituent un outil d’assistance opérationnelle et ne remplacent pas un inventaire physique, un contrôle comptable ou les obligations réglementaires propres à l’activité. L’utilisateur doit vérifier ses paramétrages et corriger tout mouvement erroné.</p></section>

  <section><h2>12. Fonctions d’intelligence artificielle</h2><p>Les fonctions de génération d’images, de descriptions ou d’autres contenus produisent des suggestions à partir des informations fournies. Les résultats peuvent comporter des erreurs, approximations ou éléments inadaptés. L’utilisateur doit les vérifier avant publication et reste responsable de l’utilisation finale du contenu généré. Il ne doit pas demander la génération de contenus illicites, trompeurs, contrefaisants ou portant atteinte aux droits de tiers.</p></section>

  <section><h2>13. Contenus et propriété intellectuelle</h2><p>L’utilisateur conserve ses droits sur les textes, images, logos, marques et autres contenus qu’il importe dans Qatalink, sous réserve des droits des tiers. Il accorde à Digital ADN les droits techniques strictement nécessaires pour héberger, transformer, afficher, sauvegarder et distribuer ces contenus dans le cadre du service.</p><p>Qatalink, son interface, son identité visuelle, ses logiciels, composants, textes propriétaires et éléments techniques demeurent protégés par les droits applicables. Aucun droit de propriété sur la plateforme n’est transféré à l’utilisateur.</p></section>

  <section><h2>14. Utilisations interdites</h2><p>Il est notamment interdit d’utiliser Qatalink pour publier ou vendre des contenus ou produits illicites, usurper une identité, porter atteinte aux droits de tiers, diffuser des logiciels malveillants, contourner des limitations techniques, tenter d’accéder sans autorisation à des comptes ou systèmes, ou utiliser le service d’une manière susceptible de compromettre sa sécurité ou sa disponibilité.</p></section>

  <section><h2>15. Disponibilité, maintenance et sauvegarde</h2><p>Digital ADN met en œuvre des moyens raisonnables pour assurer la disponibilité de Qatalink, sans garantir une disponibilité ininterrompue. Des interruptions peuvent intervenir pour maintenance, sécurité, mise à jour ou en raison de fournisseurs techniques externes. L’utilisateur est invité à conserver une copie des contenus critiques nécessaires à son activité.</p></section>

  <section><h2>16. Suspension ou résiliation</h2><p>Digital ADN peut suspendre un compte en cas de non-paiement, de risque de sécurité, d’utilisation illicite, d’abus manifeste ou de violation grave des présentes CGU. Lorsque cela est raisonnablement possible, l’utilisateur est informé et peut régulariser la situation. La résiliation ou l’expiration d’une formule peut limiter l’accès aux fonctions payantes sans supprimer immédiatement les données lorsque Qatalink prévoit une période de conservation.</p></section>

  <section><h2>17. Responsabilité</h2><p>Digital ADN est responsable de ses obligations dans les limites prévues par le droit applicable. Qatalink étant un outil de création et de gestion, Digital ADN ne saurait être tenu responsable des informations erronées saisies par un utilisateur, des engagements commerciaux pris par un professionnel envers ses clients, d’une mauvaise configuration de stock, d’un contenu généré publié sans vérification, ou d’une indisponibilité imputable à un service tiers hors de son contrôle, sous réserve des dispositions impératives contraires.</p></section>

  <section><h2>18. Données personnelles</h2><p>Les traitements de données personnelles liés à Qatalink sont décrits dans la <Link href="/confidentialite">Politique de confidentialité</Link>. La plateforme est exploitée dans le cadre notamment de la loi ivoirienne n° 2013-450 du 19 juin 2013 relative à la protection des données à caractère personnel et de la loi n° 2013-546 du 30 juillet 2013 relative aux transactions électroniques, ainsi que des textes applicables.</p></section>

  <section><h2>19. Modification des CGU</h2><p>Les présentes CGU peuvent être mises à jour pour refléter l’évolution de Qatalink, de ses offres ou des obligations légales. La date de dernière mise à jour est affichée en tête du document. En cas de modification substantielle, Digital ADN peut informer les utilisateurs par l’interface ou par tout moyen approprié.</p></section>

  <section><h2>20. Droit applicable et règlement des différends</h2><p>Les présentes CGU sont régies par le droit de la République de Côte d’Ivoire, sous réserve des règles impératives éventuellement applicables à l’utilisateur. Les parties s’efforcent de rechercher une solution amiable avant toute procédure contentieuse. À défaut, le litige relève des juridictions compétentes selon les règles applicables.</p></section>

  <section><h2>21. Contact</h2><p>Pour toute question concernant les CGU, la facturation ou le fonctionnement de Qatalink, l’utilisateur peut contacter Digital ADN via le support intégré à la plateforme.</p></section>

  <div className="legal-bottom"><Link href="/confidentialite">Politique de confidentialité</Link><Link href="/">Retour à Qatalink</Link></div>
</div></main>}
