import './globals.css';
import './enhancements.css';
import './trial-mobile.css';
import './editor.css';
import './credits-qr.css';
import './theme-fonts.css';
import './dashboard-v2.css';
import './dashboard-extras.css';
import './dashboard-integrations.css';
import './analytics.css';
import './advanced-studio.css';
import './vitrine-media.css';
import './vibecoder.css';
import './automatic-image-assignment.css';
import './public-theme.css';
import './public-catalog-v2.css';
import './public-category-scroll.css';
import './public-currency.css';
import './public-flow.css';
import './delivery-location-capture.css';
import './multipage.css';
import './vitrine.css';
import './qatalink-v3.css';
import './pwa.css';
import './landing-extras.css';
import './landing-sales.css';
import './pricing-2026.css';
import './turnkey.css';
import './cle-en-main.css';
import './cle-en-main-hero.css';
import './legal.css';
import './activation-engine.css';
import './trial-lifecycle.css';
import './mobile-money.css';
import './mobile-hardening.css';
import './onboarding-admin.css';
import './onboarding-v3.css';
import './support-chat.css';
import './trial-conversion.css';
import './generation-activity.css';
import './image-generation-controls.css';
import './business-stock.css';
import './catalog-completion.css';
import './catalog-identity.css';
import './plan-experience.css';
import './ux-fix.css';
import './catalog-deletion.css';
import './qr-canonical.css';
import './order-ops.css';
import './order-ops-v2.css';
import './ops-color-ui.css';
import './ops-pos.css';
import './order-source-analytics.css';
import './forecast-beta.css';
import './forecast-wizard.css';
import './forecast-external.css';
import './delivery-tracking.css';
import './delivery-eta.css';
import './business-beta-marketing.css';
import './point-of-sale.css';
import './landing-header-experience.css';
import './ai-credits.css';
import './seo-content.css';
import './dark-mode-hardening.css';
import type {Metadata} from 'next';
import { Plus_Jakarta_Sans, Playfair_Display } from 'next/font/google';
import { ThemeProvider } from '@/components/theme-provider';
import { PwaInstallButton } from '@/components/pwa-install-button';
import { MetaPixel } from '@/components/meta-pixel';
import { GenerationActivityCenter } from '@/components/generation-activity-center';
import { ItemImageGenerationControls } from '@/components/item-image-generation-controls';
import { ItemDescriptionGenerationControls } from '@/components/item-description-generation-controls';
import { StockManagementCenter } from '@/components/stock-management-center';
import { CatalogCompletionControls } from '@/components/catalog-completion-controls';
import { CatalogIdentityControls } from '@/components/catalog-identity-controls';
import { AutomaticImageAssignment } from '@/components/automatic-image-assignment';
import { CreateAutoIllustrations } from '@/components/create-auto-illustrations';
import { DashboardPlanExperience } from '@/components/dashboard-plan-experience';
import { QatalinkUxRefinements } from '@/components/qatalink-ux-refinements';
import { CatalogDeletionControls } from '@/components/catalog-deletion-controls';
import { QrCanonicalControls } from '@/components/qr-canonical-controls';
import { OrderOperationsCenter } from '@/components/order-operations-center';
import { MobileMoneyPaymentInfo } from '@/components/mobile-money-payment-info';
import { LandingSupportExperience } from '@/components/landing-support-experience';
import { PlanCopyAlignment } from '@/components/plan-copy-alignment';
import { DashboardKeyInHandPrompt } from '@/components/key-in-hand-configurator';
import { DirectPrintLabelFix } from '@/components/direct-print-label-fix';
import { OpsStockAlerts } from '@/components/ops-stock-alert-alerts';
