import './globals.css';
import './enhancements.css';
import './trial-mobile.css';
import './editor.css';
import './credits-qr.css';
import './theme-fonts.css';
import './dashboard-v2.css';
import './dashboard-extras.css';
import './dashboard-integrations.css';
import './analytics.css';
import './advanced-studio.css';
import './vitrine-media.css';
import './vibecoder.css';
import './automatic-image-assignment.css';
import './public-theme.css';
import './public-catalog-v2.css';
import './public-category-scroll.css';
import './public-currency.css';
import './public-flow.css';
import './delivery-location-capture.css';
import './multipage.css';
import './vitrine.css';
import './qatalink-v3.css';
import './pwa.css';
import './landing-extras.css';
import './landing-sales.css';
import './pricing-2026.css';
import './turnkey.css';
import './cle-en-main.css';
import './cle-en-main-hero.css';
import './legal.css';
import './activation-engine.css';
import './trial-lifecycle.css';
import './mobile-money.css';
import './mobile-hardening.css';
import './onboarding-admin.css';
import './onboarding-v3.css';
import './support-chat.css';
import './trial-conversion.css';
import './generation-activity.css';
import './image-generation-controls.css';
import './business-stock.css';
import './catalog-completion.css';
import './catalog-identity.css';
import './plan-experience.css';
import './ux-fix.css';
import './catalog-deletion.css';
import './qr-canonical.css';
import './order-ops.css';
import './order-ops-v2.css';
import './ops-color-ui.css';
import './ops-pos.css';
import './stock-availability.css';
import './order-source-analytics.css';
import './forecast-beta.css';
import './forecast-wizard.css';
import './forecast-external.css';
import './delivery-tracking.css';
import './delivery-eta.css';
import './business-beta-marketing.css';
import './point-of-sale.css';
import './landing-header-experience.css';
import './ai-credits.css';
import './seo-content.css';
import './dark-mode-hardening.css';
import type {Metadata} from 'next';
import { Plus_Jakarta_Sans, Playfair_Display } from 'next/font/google';
import { ThemeProvider } from '@/components/theme-provider';
import { PwaInstallButton } from '@/components/pwa-install-button';
import { MetaPixel } from '@/components/meta-pixel';
import { GenerationActivityCenter } from '@/components/generation-activity-center';
import { ItemImageGenerationControls } from '@/components/item-image-generation-controls';
import { ItemDescriptionGenerationControls } from '@/components/item-description-generation-controls';
import { StockManagementCenter } from '@/components/stock-management-center';
import { CatalogCompletionControls } from '@/components/catalog-completion-controls';
import { CatalogIdentityControls } from '@/components/catalog-identity-controls';
import { AutomaticImageAssignment } from '@/components/automatic-image-assignment';
import { CreateAutoIllustrations } from '@/components/create-auto-illustrations';
import { DashboardPlanExperience } from '@/components/dashboard-plan-experience';
import { QatalinkUxRefinements } from '@/components/qatalink-ux-refinements';
import { CatalogDeletionControls } from '@/components/catalog-deletion-controls';
import { QrCanonicalControls } from '@/components/qr-canonical-controls';
import { OrderOperationsCenter } from '@/components/order-operations-center';
import { MobileMoneyPaymentInfo } from '@/components/mobile-money-payment-info';
import { LandingSupportExperience } from '@/components/landing-support-experience';
import { PlanCopyAlignment } from '@/components/plan-copy-alignment';
import { DashboardKeyInHandPrompt } from '@/components/key-in-hand-configurator';
import { DirectPrintLabelFix } from '@/components/direct-print-label-fix';
import { OpsStockAlerts } from '@/components/ops-stock-alerts';
import { DashboardVibecoder } from '@/components/dashboard-vibecoder';
import { DashboardNavOrder } from '@/components/dashboard-nav-order';
import { OpsPosOrderTaking } from '@/components/ops-pos-order-taking';
import { OpsOrderSourceBadges } from '@/components/ops-order-source-badges';
import { OrderSourceAnalytics } from '@/components/order-source-analytics';
import { OrderSourceShareControls } from '@/components/order-source-share-controls';
import { DashboardForecastWizard } from '@/components/dashboard-forecast-wizard';
import { ForecastCopyRefinement } from '@/components/forecast-copy-refinement';
import { OpsDeliveryTracking } from '@/components/ops-delivery-tracking';
import { PublicDeliveryTrackingHandoff } from '@/components/public-delivery-tracking-handoff';
import { PublicDeliveryLocationCapture } from '@/components/public-delivery-location-capture';
import { BusinessBetaMarketing } from '@/components/business-beta-marketing';
import { DashboardPosCenter } from '@/components/dashboard-pos-center';
import { DashboardSettingsExtras } from '@/components/dashboard-settings-extras';
import { LandingHeaderExperience } from '@/components/landing-header-experience';
import { LandingAndroidBetaDownload } from '@/components/landing-android-beta-download';
import { AiCreditExperience } from '@/components/ai-credit-experience';
import { CapacitorNativeBridge } from '@/components/capacitor-native-bridge';
import { CatalogOrderControls } from '@/components/catalog-order-controls';
import { NativeSpaceSwitcher } from '@/components/native-space-switcher';
import { SmartNotificationCenter } from '@/components/smart-notification-center';
import { NativeNotificationBridge } from '@/components/native-notification-bridge';
import { NativeBackButton } from '@/components/native-back-button';
import { AdminInstallCounters } from '@/components/admin-install-counters';
import { FirstCatalogResumeReminder } from '@/components/first-catalog-resume-reminder';

const jakarta=Plus_Jakarta_Sans({subsets:['latin'],variable:'--font-jakarta'});const playfair=Playfair_Display({subsets:['latin'],style:['normal','italic'],variable:'--font-playfair'});const logo='/qatalink-icon.svg';
export const metadata:Metadata={metadataBase:new URL('https://qatalink.com'),title:{default:'Qatalink — Catalogue digital, menu QR et gestion de commerce',template:'%s | Qatalink'},description:'Créez un catalogue ou menu interactif par QR code, recevez des commandes, gérez équipe, caisse, stock et livraison avec Qatalink.',applicationName:'Qatalink',category:'business',creator:'Qatalink',publisher:'Qatalink',keywords:['menu QR code','catalogue digital','catalogue interactif','commande WhatsApp','outil gestion restaurant','caisse restaurant','digitalisation commerce Afrique'],manifest:'/manifest.webmanifest',icons:{icon:[{url:logo,type:'image/svg+xml'}],shortcut:logo,apple:logo},appleWebApp:{capable:true,statusBarStyle:'default' as const,title:'Qatalink'},openGraph:{type:'website',locale:'fr_FR',url:'https://qatalink.com',siteName:'Qatalink',title:'Qatalink — Catalogue digital, menu QR et gestion de commerce',description:'Catalogue interactif, QR permanent, commandes, caisse, stock, livraison et outils IA pour commerces.',images:[{url:'/qatalink-icon.svg'}]},twitter:{card:'summary',title:'Qatalink',description:'Catalogues et menus interactifs, QR code, commandes et gestion de commerce.',images:['/qatalink-icon.svg']},robots:{index:true,follow:true}};
const organization={"@context":"https://schema.org","@type":"Organization",name:'Qatalink',url:'https://qatalink.com',logo:'https://qatalink.com/qatalink-icon.svg',sameAs:[]};
const website={"@context":"https://schema.org","@type":"WebSite",name:'Qatalink',url:'https://qatalink.com',inLanguage:'fr',publisher:{"@type":"Organization",name:'Qatalink'}};
const software={"@context":"https://schema.org","@type":"SoftwareApplication",name:'Qatalink',url:'https://qatalink.com',applicationCategory:'BusinessApplication',operatingSystem:'Web, Android, PWA',description:'Plateforme de catalogues et menus interactifs avec QR code, commandes, équipe, caisse, stock, livraison et outils IA.'};
export default function RootLayout({children}:{children:React.ReactNode}){return <html lang="fr" suppressHydrationWarning><body className={`${jakarta.variable} ${playfair.variable}`}><script type="application/ld+json" dangerouslySetInnerHTML={{__html:JSON.stringify(organization)}}/><script type="application/ld+json" dangerouslySetInnerHTML={{__html:JSON.stringify(website)}}/><script type="application/ld+json" dangerouslySetInnerHTML={{__html:JSON.stringify(software)}}/><ThemeProvider><CapacitorNativeBridge/><NativeNotificationBridge/><NativeBackButton/><FirstCatalogResumeReminder/>{children}<LandingAndroidBetaDownload/><MobileMoneyPaymentInfo/><LandingSupportExperience/><LandingHeaderExperience/><PlanCopyAlignment/><DashboardPlanExperience/><ItemImageGenerationControls/><ItemDescriptionGenerationControls/><StockManagementCenter/><CatalogCompletionControls/><CatalogIdentityControls/><AutomaticImageAssignment/><CreateAutoIllustrations/><QatalinkUxRefinements/><CatalogDeletionControls/><QrCanonicalControls/><OrderSourceShareControls/><OrderOperationsCenter/><OpsStockAlerts/><OpsPosOrderTaking/><OpsOrderSourceBadges/><OrderSourceAnalytics/><OpsDeliveryTracking/><PublicDeliveryTrackingHandoff/><PublicDeliveryLocationCapture/><DashboardForecastWizard/><ForecastCopyRefinement/><DashboardSettingsExtras/><DashboardPosCenter/><BusinessBetaMarketing/><AiCreditExperience/><GenerationActivityCenter/><DashboardKeyInHandPrompt/><DirectPrintLabelFix/><DashboardVibecoder/><DashboardNavOrder/><CatalogOrderControls/><NativeSpaceSwitcher/><SmartNotificationCenter/><AdminInstallCounters/><PwaInstallButton/><MetaPixel/></ThemeProvider></body></html>}
