import Image from 'next/image';
import Link from 'next/link';
import {ThemeToggle} from '@/components/theme-toggle';
import {PaymentTrustBadge} from '@/components/payment-trust-badge';
import {KeyInHandCallout} from '@/components/key-in-hand-configurator';
import {ArrowRight,BarChart3,Bluetooth,Check,ImageIcon,Link2,MessageCircle,Palette,Printer,QrCode,ShoppingCart,Smartphone,Sparkles,Star,Warehouse} from 'lucide-react';

const howDemo='https://monadia-bucket.sfo3.cdn.digitaloceanspaces.com/qatalink-comment-%C3%A7a-marche.mp4';
const foodImage='https://rifjsvbbhsnpifgooenl.supabase.co/storage/v1/object/public/generated-assets/6e6e7d9a-1f37-4194-ad90-2bf3ece6909e/e000b99c-f409-4e81-9d1d-a734ff785efb/1786319610644-97a5f893-74fd-4e6a-86f4-07b40a5853a9.png';
const demos=[
  {name:'Restaurant',label:'Menu interactif',src:'https://monadia-bucket.sfo3.cdn.digitaloceanspaces.com/qatalink-restaurant.mp4'},
  {name:'Spa & Beauté',label:'Catalogue de services',src:'https://monadia-bucket.sfo3.cdn.digitaloceanspaces.com/qatalink-spa.mp4'},
  {name:'Hôtel',label:'Catalogue de chambres',src:'https://monadia-bucket.sfo3.cdn.digitaloceanspaces.com/qatalink-hotel.mp4'},
  {name:'Immobilier',label:'Biens & demandes',src:'https://monadia-bucket.sfo3.cdn.digitaloceanspaces.com/qatalink-immobilier.mp4'},
  {name:'Boutique',label:'Catalogue produits',src:'https://monadia-bucket.sfo3.cdn.digitaloceanspaces.com/qatalink-boutique.mp4'}
];
const faqItems=[
  ['Dois-je refaire mon QR quand je modifie mon menu/catalogue ?','Non. Votre QR reste le même. Vous pouvez modifier prix, photos, descriptions, catégories, couleurs, promotions et thème sans le réimprimer.'],
  ['Puis-je créer mon menu/catalogue à partir d’une simple photo ?','Oui. Importez une photo, une capture ou un scan. Qatalink organise les catégories, articles et prix, puis vous pouvez tout corriger.'],
  ['Comment fonctionnent les commandes ?','Starter envoie le panier directement vers WhatsApp. Pro et Business peuvent enregistrer les commandes dans Qatalink, puis proposer WhatsApp en complément ou le désactiver par catalogue.'],
  ['À quoi sert la page centrale Business ?','Elle regroupe jusqu’à 15 menus/catalogues, vos réseaux sociaux, votre site, WhatsApp, Google Maps et d’autres liens sur une seule page d’entrée.'],
  ['Quelles imprimantes thermiques sont compatibles ?','Qatalink est conçu pour les imprimantes thermiques ESC/POS 58 mm et 80 mm. L’impression système reste disponible, et l’impression directe fonctionne sur les navigateurs/appareils compatibles avec la connexion ESC/POS.'],
  ['Puis-je suivre mon stock ?','Oui avec Business. Vous reliez un plat ou une boisson à un ingrédient, une bouteille ou un produit ; le stock se déduit automatiquement lorsque la commande est terminée.'],
  ['Puis-je importer une fiche de stock ?','Oui avec Business : vous pouvez coller un texte complet ou envoyer une photo/capture d’inventaire, puis vérifier les lignes détectées avant import.'],
  ['Comment fonctionnent les images IA ?','Vous pouvez générer des visuels professionnels directement depuis les articles. Starter inclut 50 crédits, Pro 150 et Business 250, avec packs supplémentaires disponibles.'],
  ['Les descriptions peuvent-elles être générées ?','Oui. Qatalink peut transformer un nom ou une description basique en texte plus vendeur, en restant strictement fidèle aux informations que vous avez fournies.'],
  ['Quand commencent les 7 jours gratuits ?','Le compteur démarre uniquement lorsque votre premier catalogue est réellement créé.'],
  ['Que se passe-t-il après l’essai ?','Votre travail reste conservé. L’édition est verrouillée à la fin de l’essai et le lien public bénéficie encore d’une courte période de grâce avant suspension.'],
  ['Est-ce réservé aux restaurants ?','Non. Qatalink convient aussi aux hôtels, spas, salons, boutiques, showrooms, agences immobilières et autres activités qui présentent des produits ou services.']
];

export default function Home(){return <>
  <header className="nav landing-nav"><div className="container landing-nav-inner" style={{display:'flex',alignItems:'center',justifyContent:'space-between'}}>
    <Link className="brand landing-brand" href="/"><Image src="/qatalink-logo.png" width={34} height={34} alt="Qatalink"/><span>qatalink</span></Link>
    <nav className="navlinks"><a href="#features">Fonctionnalités</a><a href="#operations">Commandes</a><a href="#pricing">Tarifs</a><Link href="/cle-en-main">Clé-en-main</Link></nav>
    <div className="actions landing-nav-actions"><ThemeToggle/><Link className="btn btn-ghost" href="/login">Connexion</Link><Link className="btn btn-primary landing-create-btn" href="/create"><span className="landing-create-full">Créer mon menu/catalogue</span><span className="landing-create-short">Créer</span></Link></div>
  </div></header>
  <main>
    <section className="hero container hero-conversion">
      <div className="hero-conversion-copy">
        <div className="pill"><Sparkles size={14}/> 7 jours gratuits · aucune carte requise</div>
        <h1>Transformez votre <span className="hero-simple-word">menu/catalogue</span> en <span className="hero-interactive-word">expérience interactive</span></h1>
        <p>Présentez mieux vos offres, laissez vos clients sélectionner ce qu’ils veulent, recevez les commandes et mettez à jour prix, photos et disponibilités sans refaire vos supports.</p>
        <div className="hero-cta"><Link href="/create" className="btn btn-primary">Créer mon menu/catalogue gratuitement <ArrowRight size={17}/></Link><Link href="/cle-en-main" className="btn btn-ghost">Je préfère une solution clé-en-main</Link></div>
        <div className="hero-reassurance"><span><Check size={13}/>QR permanent</span><span><Check size={13}/>Tous les catalogues sont interactifs</span><span><Check size={13}/>Menu digital + commandes + contenu IA</span></div>
      </div>
      <HeroActivationDemo/>
    </section>

    <section className="marquee" id="demo"><div className="track">{[...demos,...demos].map((d,i)=><div className="phone" key={`${d.name}-${i}`}><video src={d.src} autoPlay muted loop playsInline preload="metadata" disablePictureInPicture aria-label={`Démonstration ${d.name}`}/><div className="phone-label"><strong>{d.name}</strong><span>{d.label}</span></div></div>)}</div></section>

    <section className="section alt" id="features"><div className="container"><div className="section-head"><div className="eyebrow">PLUS QU’UN QR CODE</div><h2>Votre menu/catalogue devient un vrai outil commercial</h2><p>Qatalink réunit présentation, contenu, commande, équipe et suivi dans une seule expérience.</p></div><div className="grid-3">
      <Feature icon={<ImageIcon/>} title="Photo ou texte → catalogue" text="Importez votre ancienne carte, une capture ou un texte complet et récupérez une structure modifiable."/>
      <Feature icon={<Palette/>} title="Personnalisation complète" text="Couleurs, fonds, typographies, promotions, catégories, photos et identité de marque restent modifiables."/>
      <Feature icon={<ShoppingCart/>} title="Commandes interactives" text="Le client sélectionne plusieurs articles et quantités avant WhatsApp ou l’enregistrement dans Qatalink."/>
      <Feature icon={<QrCode/>} title="QR permanent" text="Mettez le contenu à jour sans changer ni réimprimer le QR déjà installé chez vous."/>
      <Feature icon={<Sparkles/>} title="Images et descriptions IA" text="Améliorez la présentation de vos plats, produits et services sans séance photo pour chaque modification."/>
      <Feature icon={<Warehouse/>} title="Stock automatique" text="Avec Business, reliez les ventes au stock et suivez les déductions, seuils bas et mouvements."/>
    </div></div></section>

    <section className="section ai-sales-section"><div className="container"><div className="section-head"><div className="eyebrow">DONNER ENVIE AVANT MÊME LA COMMANDE</div><h2>Une mauvaise photo peut faire paraître un bon plat ordinaire.</h2><p>Qatalink permet de générer des images de menu plus professionnelles et des descriptions appétissantes, directement rattachées à chaque article.</p></div><div className="ai-before-after"><div className="ai-visual-card before"><span>AVANT</span><div className="ai-image-frame"><img src={foodImage} alt="Exemple de plat avant amélioration"/></div><div><b>Photo peu vendeuse</b><p>Floue, sombre, mal cadrée : le client a moins de raisons de s’arrêter sur le produit.</p></div></div><div className="ai-transform-arrow">→</div><div className="ai-visual-card after"><span>APRÈS AVEC QATALINK</span><div className="ai-image-frame"><img src={foodImage} alt="Exemple de visuel professionnel généré"/></div><div><b>Visuel plus professionnel</b><p>Un rendu propre et appétissant, prêt à être utilisé directement dans le menu/catalogue.</p></div></div></div><div className="description-demo"><div><span>DESCRIPTION BASIQUE</span><p>“Poulet braisé”</p></div><div className="description-arrow">→</div><div><span>DESCRIPTION PLUS VENDEUSE</span><p>“Poulet braisé savoureux, présenté avec un rendu gourmand et généreux qui met immédiatement le plat en valeur.”</p></div></div><p className="ai-fidelity-note">La génération de description privilégie désormais le nom exact du produit et les précisions fournies par le commerçant : elle ne doit pas inventer un accompagnement ou un ingrédient absent.</p></div></section>

    <section className="section alt hub-section"><div className="container hub-grid"><div><div className="eyebrow">PAGE CENTRALE BUSINESS</div><h2>Un seul lien pour vos menus, vos réseaux, votre site et votre présence locale.</h2><p>Le client peut arriver sur une page centrale, choisir le bon menu/catalogue puis accéder aussi à WhatsApp, Instagram, Facebook, TikTok, votre site, votre localisation Google Maps ou votre lien d’avis.</p><div className="hub-benefits"><span><Link2/>Regroupez jusqu’à 15 menus/catalogues</span><span><MessageCircle/>Rendez vos contacts faciles à retrouver</span><span><Star/>Facilitez l’accès à votre fiche Google et à votre lien d’avis</span></div></div><div className="hub-mock"><div className="hub-brand">VOTRE ENTREPRISE</div><button>Menu restaurant</button><button>Carte boissons</button><button>Catalogue événements</button><div className="hub-socials"><span>Instagram</span><span>WhatsApp</span><span>Google Maps</span><span>Avis Google</span></div></div></div></section>

    <section className="section ops-marketing" id="operations"><div className="container"><div className="section-head"><div className="eyebrow">CAISSE & COMMANDES</div><h2>Recevez les commandes, cumulez plusieurs passages et imprimez une seule addition.</h2><p>Pas besoin de parler de “POS” au personnel : Qatalink devient simplement l’écran où l’équipe voit les commandes, change leur statut et imprime les tickets.</p></div><div className="ops-marketing-grid"><Feature icon={<BarChart3/>} title="Commandes centralisées" text="Nouvelle → En préparation → Prête → Terminée. L’équipe suit le service depuis un écran partagé."/><Feature icon={<ShoppingCart/>} title="Addition fusionnée" text="Deux ou plusieurs commandes de la même table peuvent être regroupées en une seule addition et un seul ticket."/><Feature icon={<Printer/>} title="Tickets thermiques" text="Format 58 mm prévu, impression système et impression directe lorsque le navigateur et l’imprimante sont compatibles."/><Feature icon={<Bluetooth/>} title="ESC/POS 58 mm et 80 mm" text="Qatalink vise les imprimantes thermiques ESC/POS Bluetooth ou USB courantes. La compatibilité directe dépend du navigateur, du protocole et du modèle."/></div><div className="printer-note"><Printer/><div><b>Matériel recommandé</b><p>Imprimante thermique ESC/POS 58 mm pour une caisse compacte ; les modèles 80 mm ESC/POS peuvent également être utilisés selon la configuration. Sur les appareils non compatibles avec l’impression directe, l’impression système reste disponible.</p></div></div></div></section>

    <section className="section how-section" id="how"><div className="container"><div className="section-head"><div className="eyebrow">COMMENT ÇA MARCHE</div><h2>Importez, vérifiez, publiez et gérez votre activité depuis le même espace.</h2><p>Qatalink organise le contenu, vous laisse tout vérifier puis transforme votre offre en expérience mobile partageable.</p></div><div className="how-showcase"><div className="how-video-card"><div className="how-video-top"><span className="live-dot"/>DÉMO QATALINK</div><div className="how-video-wrap"><video src={howDemo} controls muted playsInline preload="metadata"/></div><div className="how-video-caption"><strong>Voyez le parcours côté client</strong><span>Le même menu/catalogue peut ensuite évoluer sans changer de QR.</span></div></div><div className="how-copy"><div className="how-mini-step"><span>01</span><div><b>Importez votre contenu</b><p>Photo, texte complet ou catalogue vide.</p></div></div><div className="how-mini-step"><span>02</span><div><b>Améliorez la présentation</b><p>Images professionnelles, descriptions, couleurs et catégories.</p></div></div><div className="how-mini-step"><span>03</span><div><b>Activez vos commandes</b><p>WhatsApp direct ou espace privé Qatalink selon votre formule.</p></div></div><div className="how-mini-step"><span>04</span><div><b>Ajoutez l’exploitation</b><p>Équipe, impression, fusion de commandes et stock avec les offres supérieures.</p></div></div><Link href="/create" className="btn btn-primary how-main-cta">Créer mon Qatalink <ArrowRight size={17}/></Link></div></div></div></section>

    <section className="section alt" id="pricing"><div className="container"><div className="section-head"><div className="eyebrow">TARIFS SIMPLES</div><h2>Trois formules selon la façon dont vous voulez gérer vos commandes.</h2><p>Tous les catalogues sont interactifs. Starter envoie la commande sur WhatsApp ; Pro la centralise dans Qatalink ; Business ajoute la page centrale multi-catalogues et le stock automatique. À l’année, vous payez 11 mois au lieu de 12.</p></div><PaymentTrustBadge/><div className="pricing">
      <Price name="Starter" price="9 900" annual="108 900" oldAnnual="118 800" saving="9 900" features={['1 menu/catalogue interactif','Sélection + quantités + panier','Commande envoyée directement sur WhatsApp','QR permanent','Prix, photos et catégories modifiables','50 crédits image inclus']} />
      <Price name="Pro" price="24 900" annual="273 900" oldAnnual="298 800" saving="24 900" featured features={['Jusqu’à 5 menus/catalogues','Commandes enregistrées dans Qatalink','WhatsApp activable ou désactivable','Accès équipe et permissions','Fusion de commandes + addition unique','Tickets thermiques + impression directe compatible','150 crédits image inclus']} />
      <Price name="Business" price="49 900" annual="548 900" oldAnnual="598 800" saving="49 900" features={['Jusqu’à 15 menus/catalogues','Tout Pro','Page centrale avec menus, réseaux, site et Google Maps','Gestion et import du stock par texte ou image','Liaisons plats/boissons → stock','Déduction automatique + alertes stock bas','250 crédits image inclus']} />
    </div><p style={{textAlign:'center',marginTop:18,color:'var(--muted)'}}>Besoin de plus d’illustrations ? Pack de 100 crédits à 2 000 F CFA pour les abonnés, payable par Mobile Money ou carte bancaire.</p><KeyInHandCallout source="Landing principale · sous les tarifs"/></div></section>

    <section className="section" id="faq"><div className="container"><div className="section-head"><div className="eyebrow">FAQ</div><h2>Les réponses aux questions qui reviennent avant de se lancer</h2><p>Menu/catalogue, commandes, IA, impression, stock, page centrale et abonnement.</p></div><div className="faq faq-rich">{faqItems.map(([q,a])=><details key={q}><summary>{q}</summary><p>{a}</p></details>)}</div></div></section>
  </main>
  <footer className="footer"><div className="container" style={{display:'flex',justifyContent:'space-between',gap:20,flexWrap:'wrap'}}><div className="brand"><Image src="/qatalink-logo.png" width={32} height={32} alt="Qatalink"/>qatalink</div><div className="site-legal-links"><Link href="/cgu">CGU</Link><Link href="/confidentialite">Confidentialité</Link><span>Édité par Digital ADN</span></div><div>© 2026 Qatalink. Menus & catalogues interactifs.</div></div></footer>
</>}

function Feature({icon,title,text}:{icon:React.ReactNode;title:string;text:string}){return <div className="card"><div className="iconbox">{icon}</div><h3>{title}</h3><p>{text}</p></div>}
function HeroActivationDemo(){return <div className="activation-live-demo" aria-label="Démonstration visuelle de menu catalogue interactif"><div className="activation-demo-source"><strong>VOTRE MENU / CATALOGUE</strong><div className="activation-source-line"/><div className="activation-source-line short"/><div className="activation-source-line"/><div className="activation-source-line short"/><div className="activation-source-price"><span>Offre signature</span><b>10 000 F</b></div></div><div className="activation-demo-arrow">→</div><div className="activation-demo-phone"><div className="activation-demo-phone-head"><small>MENU / CATALOGUE INTERACTIF</small><b>Votre entreprise</b></div><div className="activation-demo-tabs"><span>Nouveautés</span><span>Populaires</span><span>Offres</span></div><div className="activation-demo-item"><span className="activation-demo-thumb"/><div><b>Offre Signature</b><small>Disponible maintenant</small></div><strong>10 000 F</strong></div><div className="activation-demo-item"><span className="activation-demo-thumb"/><div><b>Pack Premium</b><small>Présentation claire</small></div><strong>15 000 F</strong></div><div className="activation-demo-item"><span className="activation-demo-thumb"/><div><b>Nouveauté</b><small>Modifiable à tout moment</small></div><strong>8 500 F</strong></div><div className="activation-demo-cta">COMMANDER / CONTACTER</div></div><div className="activation-demo-qr"><QrCode size={54}/><b>LE MÊME QR</b><small>même après vos modifications</small></div></div>}
function Price({name,price,annual,oldAnnual,saving,features,featured=false}:{name:string;price:string;annual:string;oldAnnual:string;saving:string;features:string[];featured?:boolean}){return <div className={'price-card '+(featured?'featured':'')}>{featured&&<div className="popular">RECOMMANDÉ</div>}<h3>{name}</h3><div className="price">{price} F <small>/ mois</small></div><div className="landing-annual"><span className="annual-card-badge">1 MOIS OFFERT</span><b>{annual} F / an</b><small><s>{oldAnnual} F</s> · économie de <strong>{saving} F</strong></small></div><div className="price-payment-method"><Smartphone size={14}/>Mobile Money ou carte bancaire</div><div className="features">{features.map((f,i)=><div className="feature" key={i}><Check size={16} color="#c7192f"/>{f}</div>)}</div><Link className={featured?'btn btn-primary':'btn btn-dark'} style={{width:'100%'}} href="/create">Choisir {name}</Link></div>}
