'use client';
import {useEffect,useMemo,useState} from 'react';
import {Bike,BriefcaseBusiness,ShoppingBag,UsersRound,X} from 'lucide-react';
import {createSupabaseBrowserClient} from '@/lib/supabase';
type U={id:string;email:string|null;full_name:string|null;access_mode:string;created_at:string;last_sign_in_at:string|null;roles:string[];role_events:number;business_count:number;deliveries_count:number};
type O={role_counts?:Record<string,number>;recent_users?:U[];recent_businesses?:any[];free_accounts?:number};
const labels:Record<string,string>={client:'Client',pro:'Pro',team:'Équipe',driver:'Livreur',free:'Free',static:'Starter',interactive:'Pro',linkhub:'Business'};
export function AdminRoleInsights(){const supabase=useMemo(()=>createSupabaseBrowserClient(),[]);const [data,setData]=useState<O|null>(null),[selected,setSelected]=useState<U|null>(null);
 useEffect(()=>{if(location.pathname!='/admin')return;void(async()=>{const {data:d}=await supabase.rpc('admin_qatalink_overview');setData(d||null)})()},[supabase]);
 useEffect(()=>{if(!data?.recent_businesses?.length)return;const fix=()=>{const rows=Array.from(document.querySelectorAll<HTMLTableRowElement>('.admin-table tbody tr'));for(const r of rows){const name=r.querySelector('td b')?.textContent?.trim();const b=data.recent_businesses!.find((x:any)=>String(x.name||'').trim()===name);const cells=r.querySelectorAll('td');if(b&&cells[5])cells[5].textContent=labels[b.plan_code]||b.plan_code||'Free'}};fix();const mo=new MutationObserver(fix);mo.observe(document.body,{childList:true,subtree:true});return()=>mo.disconnect()},[data]);
 if(!data)return null;const rc=data.role_counts||{};const users=data.recent_users||[];const cards=[['client','Clients',ShoppingBag],['pro','Pros',BriefcaseBusiness],['team','Équipes',UsersRound],['driver','Livreurs',Bike]] as const;
 return <section style={{maxWidth:1180,margin:'0 auto 48px',padding:'0 20px'}}><div style={{display:'grid',gridTemplateColumns:'repeat(4,minmax(0,1fr))',gap:12,marginBottom:24}}>{cards.map(([k,l,Icon])=><article key={k} className="admin-kpi"><Icon/><b>{Number(rc[k]||0)}</b><span>{l}</span></article>)}</div><div className="admin-section"><div className="admin-section-title"><div><h2>Nouveaux utilisateurs & rôles</h2><p>Rôle principal choisi, rôles réellement utilisés et activité liée au compte.</p></div><span className="admin-status active">{data.free_accounts||0} Free</span></div><div style={{overflowX:'auto'}}><table className="admin-table"><thead><tr><th>Utilisateur</th><th>Accès principal</th><th>Rôles détectés</th><th>Activité</th><th>Inscription</th></tr></thead><tbody>{users.map(u=><tr key={u.id} onClick={()=>setSelected(u)} style={{cursor:'pointer'}}><td><b>{u.full_name||u.email||'Utilisateur'}</b><small>{u.email}</small></td><td><span className="admin-status active">{labels[u.access_mode]||u.access_mode}</span></td><td>{(u.roles||[]).map(r=><span key={r} style={{display:'inline-block',margin:'2px 4px 2px 0',padding:'4px 7px',borderRadius:999,background:'#f1f1f3',fontSize:11,fontWeight:800}}>{labels[r]||r}</span>)}</td><td><b>{u.role_events||0}</b> ouvertures · {u.business_count||0} activité(s) · {u.deliveries_count||0} livraison(s)</td><td>{new Date(u.created_at).toLocaleDateString('fr-FR')}</td></tr>)}</tbody></table></div></div>{selected&&<div className="admin-modal-backdrop" onClick={()=>setSelected(null)}><div className="admin-modal" onClick={e=>e.stopPropagation()} style={{maxWidth:560}}><button className="admin-modal-close" onClick={()=>setSelected(null)}><X/></button><div className="eyebrow">UTILISATEUR QATALINK</div><h2>{selected.full_name||selected.email||'Utilisateur'}</h2><p>{selected.email}</p><div className="admin-detail-grid"><div><span>Accès principal</span><b>{labels[selected.access_mode]||selected.access_mode}</b></div><div><span>Rôles utilisés</span><b>{(selected.roles||[]).map(r=>labels[r]||r).join(', ')||'Client'}</b></div><div><span>Interactions rôles</span><b>{selected.role_events||0}</b></div><div><span>Activités possédées</span><b>{selected.business_count||0}</b></div><div><span>Livraisons rattachées</span><b>{selected.deliveries_count||0}</b></div><div><span>Dernière connexion</span><b>{selected.last_sign_in_at?new Date(selected.last_sign_in_at).toLocaleString('fr-FR'):'Jamais'}</b></div></div></div></div>}</section>}
