'use client';

import {useEffect,useMemo,useRef,useState} from 'react';
import {createPortal} from 'react-dom';
import {Check,ImagePlus,RefreshCw,Sparkles,UploadCloud,X} from 'lucide-react';
import {createSupabaseBrowserClient} from '@/lib/supabase';

const MAX_IMAGES=12;
const MAX_BYTES=10*1024*1024;
type Uploaded={name:string;url:string;storage_path:string};
type Assignment={image_index:number;item_id:string;item_name:string;confidence:number;reason:string;alt_text:string;image_url:string;storage_path:string;file_name:string};

type CatalogItem={id:string;name:string};

export function AutomaticImageAssignment(){
  const supabase=useMemo(()=>createSupabaseBrowserClient(),[]);
  const inputRef=useRef<HTMLInputElement|null>(null);
  const [host,setHost]=useState<Element|null>(null);const [open,setOpen]=useState(false);const [files,setFiles]=useState<File[]>([]);const [uploaded,setUploaded]=useState<Uploaded[]>([]);const [assignments,setAssignments]=useState<Assignment[]>([]);const [items,setItems]=useState<CatalogItem[]>([]);const [busy,setBusy]=useState('');const [error,setError]=useState('');const [replacePrimary,setReplacePrimary]=useState(true);const [feedback,setFeedback]=useState('');

  useEffect(()=>{
    if(typeof window==='undefined'||location.pathname!=='/dashboard')return;let timer:any;
    const resolve=()=>{const title=document.querySelector('.dash-v3-top h1')?.textContent?.trim()||'';setHost(title==='Articles & catégories'?document.querySelector('.dash-toolbar'):null)};
    resolve();const o=new MutationObserver(()=>{clearTimeout(timer);timer=setTimeout(resolve,70)});o.observe(document.body,{childList:true,subtree:true,characterData:true});return()=>{clearTimeout(timer);o.disconnect()};
  },[]);

  function reset(){setFiles([]);setUploaded([]);setAssignments([]);setItems([]);setError('');setReplacePrimary(true);if(inputRef.current)inputRef.current.value=''}
  function close(){if(busy)return;setOpen(false);reset()}
  function addFiles(list:FileList|null){if(!list)return;const incoming=Array.from(list).filter(f=>f.type.startsWith('image/')&&f.size<=MAX_BYTES);setFiles(cur=>{const map=new Map(cur.map(f=>[`${f.name}:${f.size}:${f.lastModified}`,f]));for(const f of incoming){if(map.size>=MAX_IMAGES)break;map.set(`${f.name}:${f.size}:${f.lastModified}`,f)}return Array.from(map.values()).slice(0,MAX_IMAGES)});setAssignments([]);setUploaded([]);if(incoming.length<list.length)setError('Certaines images ont été ignorées : image uniquement, 10 Mo maximum.');else setError('');if(inputRef.current)inputRef.current.value=''}

  async function context(){const {data:{session}}=await supabase.auth.getSession();if(!session)throw new Error('Session expirée.');const params=new URLSearchParams(location.search);let catalogId=params.get('catalog')||'';if(!catalogId){const {data:businesses}=await supabase.from('businesses').select('id').eq('owner_user_id',session.user.id).order('created_at',{ascending:true}).limit(1);const bid=businesses?.[0]?.id;if(bid){const {data:catalogs}=await supabase.from('catalogs').select('id').eq('business_id',bid).eq('is_active',true).order('created_at',{ascending:false}).limit(1);catalogId=String(catalogs?.[0]?.id||'')}}if(!catalogId)throw new Error('Catalogue introuvable.');return {session,catalogId}}

  async function uploadAll(userId:string,catalogId:string){const rows:Uploaded[]=[];for(let i=0;i<files.length;i++){const f=files[i];const safe=f.name.replace(/[^a-zA-Z0-9._-]+/g,'-');const path=`${userId}/auto-illustrations/${catalogId}/${Date.now()}-${i}-${safe}`;const up=await supabase.storage.from('catalog-assets').upload(path,f,{contentType:f.type||'image/jpeg',upsert:false});if(up.error)throw new Error(`Impossible d’envoyer « ${f.name} ».`);const {data:u}=supabase.storage.from('catalog-assets').getPublicUrl(path);rows.push({name:f.name,url:u.publicUrl,storage_path:path})}return rows}

  async function analyze(){if(!files.length)return;setBusy('analyze');setError('');try{const {session,catalogId}=await context();const rows=await uploadAll(session.user.id,catalogId);setUploaded(rows);const r=await fetch('/api/images/auto-assign',{method:'POST',headers:{'Content-Type':'application/json',Authorization:`Bearer ${session.access_token}`},body:JSON.stringify({action:'analyze',catalog_id:catalogId,images:rows})});const j=await r.json().catch(()=>({}));if(!r.ok)throw new Error(j.error||'Impossible d’analyser les images.');setAssignments(j.assignments||[]);setItems(j.items||[])}catch(e:any){setError(e?.message||'Une erreur est survenue.')}finally{setBusy('')}}

  async function apply(){if(!assignments.some(a=>a.item_id))return;setBusy('apply');setError('');try{const {session,catalogId}=await context();const r=await fetch('/api/images/auto-assign',{method:'POST',headers:{'Content-Type':'application/json',Authorization:`Bearer ${session.access_token}`},body:JSON.stringify({action:'apply',catalog_id:catalogId,assignments,replace_primary:replacePrimary})});const j=await r.json().catch(()=>({}));if(!r.ok)throw new Error(j.error||'Impossible d’appliquer les illustrations.');setFeedback(`${j.applied||0} illustration(s) attribuée(s) automatiquement.`);setOpen(false);reset();setTimeout(()=>location.reload(),800)}catch(e:any){setError(e?.message||'Une erreur est survenue.')}finally{setBusy('')}}

  const action=host&&createPortal(<button type="button" className="btn btn-ghost q-auto-images-trigger" onClick={()=>{reset();setOpen(true)}}><ImagePlus size={15}/>Attribuer des images</button>,host);
  const modal=open&&createPortal(<div className="q-auto-images-backdrop" onMouseDown={e=>{if(e.target===e.currentTarget)close()}}><section className="q-auto-images-modal"><header><div><span className="eyebrow">ATTRIBUTION AUTOMATIQUE</span><h2>Ajoutez vos photos, Qatalink les place sur les bons articles</h2><p>Envoyez des photos de plats, produits ou services. Qatalink regarde chaque image, la compare aux articles de ce catalogue et vous montre les correspondances avant publication.</p></div><button onClick={close}><X/></button></header>{!assignments.length?<div className="q-auto-images-body"><button className="q-auto-images-drop" onClick={()=>inputRef.current?.click()}><UploadCloud/><b>Ajouter les images à reconnaître</b><span>Jusqu’à {MAX_IMAGES} images · 10 Mo maximum chacune</span></button><input hidden ref={inputRef} multiple type="file" accept="image/*" onChange={e=>addFiles(e.target.files)}/>{files.length>0&&<div className="q-auto-images-files">{files.map((f,i)=><div key={`${f.name}-${i}`}><span><b>{i+1}</b>{f.name}</span><button onClick={()=>setFiles(cur=>cur.filter((_,n)=>n!==i))}><X size={13}/></button></div>)}</div>}<p className="q-auto-images-note">Conseil : utilisez des photos où le produit ou le plat est suffisamment visible. Les images sans correspondance fiable restent non attribuées.</p>{error&&<div className="q-auto-images-error">{error}</div>}<footer><button className="btn btn-ghost" onClick={close}>Annuler</button><button className="btn btn-primary" onClick={analyze} disabled={!files.length||busy==='analyze'}>{busy==='analyze'?<><RefreshCw size={14}/>Reconnaissance…</>:<><Sparkles size={14}/>Reconnaître et associer</>}</button></footer></div>:<div className="q-auto-images-body"><div className="q-auto-images-results">{assignments.map((a,i)=><article key={i}><img src={a.image_url} alt={a.alt_text||a.file_name}/><div><b>{a.file_name}</b><select value={a.item_id} onChange={e=>setAssignments(cur=>cur.map((x,n)=>n===i?{...x,item_id:e.target.value,item_name:items.find(it=>it.id===e.target.value)?.name||''}:x))}><option value="">Ne pas attribuer</option>{items.map(it=><option key={it.id} value={it.id}>{it.name}</option>)}</select><small>{a.item_id?`${Math.round(a.confidence*100)} % de confiance · ${a.reason}`:a.reason}</small></div>{a.item_id&&<Check className="q-auto-images-ok"/>}</article>)}</div><label className="q-auto-images-check"><input type="checkbox" checked={replacePrimary} onChange={e=>setReplacePrimary(e.target.checked)}/>Remplacer l’illustration principale existante lorsque l’article en possède déjà une</label>{error&&<div className="q-auto-images-error">{error}</div>}<footer><button className="btn btn-ghost" onClick={()=>{setAssignments([]);setUploaded([])}}>Changer les images</button><button className="btn btn-primary" onClick={apply} disabled={busy==='apply'||!assignments.some(a=>a.item_id)}>{busy==='apply'?'Publication…':'Appliquer les illustrations'}</button></footer></div>}</section></div>,document.body);
  return <>{action}{modal}{feedback&&createPortal(<div className="q-catalog-complete-feedback">{feedback}</div>,document.body)}</>;
}
