'use client';

import {useEffect,useMemo,useRef,useState} from 'react';
import {createPortal} from 'react-dom';
import {Download,ImagePlus,Loader2,Sparkles,Upload} from 'lucide-react';
import {QRCodeSVG} from 'qrcode.react';
import {createSupabaseBrowserClient} from '@/lib/supabase';

const fonts=['Plus Jakarta Sans','Inter','Poppins','Montserrat','Manrope','Space Grotesk','Playfair Display','DM Serif Display','Lora'];
const sleep=(ms:number)=>new Promise(r=>setTimeout(r,ms));
function loadImage(src:string){return new Promise<HTMLImageElement>((resolve,reject)=>{const i=new Image();i.crossOrigin='anonymous';i.onload=()=>resolve(i);i.onerror=reject;i.src=src})}
function svgToImage(svg:SVGSVGElement){return new Promise<HTMLImageElement>((resolve,reject)=>{const xml=new XMLSerializer().serializeToString(svg);const i=new Image();i.onload=()=>resolve(i);i.onerror=reject;i.src='data:image/svg+xml;charset=utf-8,'+encodeURIComponent(xml)})}
function cover(ctx:CanvasRenderingContext2D,img:HTMLImageElement,w:number,h:number){const s=Math.max(w/img.width,h/img.height),dw=img.width*s,dh=img.height*s;ctx.drawImage(img,(w-dw)/2,(h-dh)/2,dw,dh)}

export function BusinessCardStudio(){
 const supabase=useMemo(()=>createSupabaseBrowserClient(),[]);const [host,setHost]=useState<Element|null>(null);const [session,setSession]=useState<any>(null);const [catalog,setCatalog]=useState<any>(null);const [business,setBusiness]=useState<any>(null);const [theme,setTheme]=useState<any>({});const [wallet,setWallet]=useState(0);const [font,setFont]=useState('Plus Jakarta Sans');const [prompt,setPrompt]=useState('');const [logo,setLogo]=useState('');const [fields,setFields]=useState({name:'',role:'',phone:'',email:'',address:'',website:'',other:''});const [busy,setBusy]=useState(false);const [progress,setProgress]=useState('');const [error,setError]=useState('');const [background,setBackground]=useState('');const canvasRef=useRef<HTMLCanvasElement|null>(null);
 const cardUrl=catalog?`https://qatalink.com/h/${catalog.hub_public_slug}`:'';
 useEffect(()=>{let dead=false;const sync=async()=>{const title=document.querySelector('.dash-v3-top h1')?.textContent?.trim(),wrap=document.querySelector('.qr-v3-wrap');if(title!=='QR & partage'||!wrap){setHost(null);return}setHost(wrap);const {data:{session:s}}=await supabase.auth.getSession();if(!s||dead)return;setSession(s);let id=new URLSearchParams(location.search).get('catalog')||'';if(!id){const {data:b}=await supabase.from('businesses').select('id').eq('owner_user_id',s.user.id).order('created_at',{ascending:true}).limit(1).maybeSingle();if(b){const {data:c}=await supabase.from('catalogs').select('id').eq('business_id',b.id).order('created_at',{ascending:false}).limit(1).maybeSingle();id=String(c?.id||'')}}if(!id||id===catalog?.id)return;const {data:c}=await supabase.from('catalogs').select('id,business_id,title,hub_public_slug,logo_url').eq('id',id).maybeSingle();if(!c)return;const [{data:b},{data:t},{data:w}]=await Promise.all([supabase.from('businesses').select('name,phone,email,address_text,logo_url').eq('id',c.business_id).maybeSingle(),supabase.from('catalog_theme_settings').select('primary_color,secondary_color,background_color,text_color').eq('catalog_id',id).maybeSingle(),supabase.from('credit_wallets').select('balance').eq('business_id',c.business_id).maybeSingle()]);setCatalog(c);setBusiness(b);setTheme(t||{});setWallet(Number(w?.balance||0));setLogo(String(c.logo_url||b?.logo_url||''));setFields(v=>({...v,name:v.name||'',phone:v.phone||'',email:v.email||'',address:v.address||''}))};void sync();const t=setInterval(()=>void sync(),1500);return()=>{dead=true;clearInterval(t)}},[catalog?.id,supabase]);
 async function uploadLogo(file:File){if(!session||!catalog)return;const safe=file.name.replace(/[^a-zA-Z0-9._-]+/g,'-');const path=`${session.user.id}/${catalog.id}/business-card/${Date.now()}-${safe}`;const up=await supabase.storage.from('catalog-assets').upload(path,file,{contentType:file.type||'image/png'});if(up.error)return setError(up.error.message);const {data:u}=supabase.storage.from('catalog-assets').getPublicUrl(path);setLogo(u.publicUrl)}
 async function generate(){if(!session||!catalog||busy)return;if(wallet<50)return setError(`Il faut 50 crédits minimum. Solde actuel : ${wallet}.`);setBusy(true);setError('');setProgress('Création du fond de carte…');try{const r=await fetch('/api/business-card/generate',{method:'POST',headers:{'Content-Type':'application/json',Authorization:`Bearer ${session.access_token}`},body:JSON.stringify({catalog_id:catalog.id,prompt,logo_url:logo})});const d=await r.json().catch(()=>({}));if(!r.ok)throw new Error(d.error||'Génération impossible');setWallet(Number(d.balance??wallet-50));for(let i=0;i<75;i++){await sleep(2200);const sr=await fetch('/api/marketing-assets/status',{method:'POST',headers:{'Content-Type':'application/json',Authorization:`Bearer ${session.access_token}`},body:JSON.stringify({job_id:d.job_id})});const sd=await sr.json().catch(()=>({}));if(sd.status==='completed'&&sd.image_url){setBackground(sd.image_url);setProgress('Carte prête.');setTimeout(()=>void compose(sd.image_url),50);return}if(sd.status==='failed')throw new Error('La génération a échoué. Les crédits ont été recrédités.')}throw new Error('La génération continue. Revenez dans quelques instants.')}catch(e:any){setError(e?.message||'Génération impossible');setProgress('')}finally{setBusy(false)}}
 async function compose(bg=background){if(!bg||!catalog)return;const canvas=canvasRef.current||document.createElement('canvas');canvas.width=1004;canvas.height=650;const ctx=canvas.getContext('2d');if(!ctx)return;const img=await loadImage(bg);cover(ctx,img,canvas.width,canvas.height);ctx.fillStyle='rgba(0,0,0,.28)';ctx.fillRect(0,0,canvas.width,canvas.height);const text=theme?.text_color||'#fff';const primary=theme?.primary_color||'#B5122B';const left=70;ctx.textAlign='left';ctx.fillStyle=text;ctx.font=`800 58px "${font}", Arial`;const rows=[fields.name,fields.role,fields.phone,fields.email,fields.address,fields.website,fields.other].map(v=>v.trim()).filter(Boolean);let y=130;rows.forEach((v,i)=>{ctx.font=`${i===0?'800':'600'} ${i===0?58:31}px "${font}", Arial`;ctx.fillText(v,left,y);y+=i===0?64:45});if(logo){try{const li=await loadImage(logo);const max=125,s=Math.min(max/li.width,max/li.height);ctx.drawImage(li,70,650-70-li.height*s,li.width*s,li.height*s)}catch{}}const qr=document.querySelector('[data-business-card-qr] svg') as SVGSVGElement|null;if(qr){const qi=await svgToImage(qr);ctx.fillStyle='#fff';ctx.roundRect(760,370,190,190,22);ctx.fill();ctx.drawImage(qi,780,390,150,150)}ctx.fillStyle=primary;ctx.fillRect(0,0,18,650);if(canvasRef.current!==canvas){canvasRef.current=canvas}const preview=document.querySelector<HTMLCanvasElement>('.q-business-card-preview canvas');if(preview){preview.width=1004;preview.height=650;preview.getContext('2d')?.drawImage(canvas,0,0)}}
 function download(){if(!canvasRef.current)return;const a=document.createElement('a');a.href=canvasRef.current.toDataURL('image/png');a.download='carte-de-visite-qatalink-85x55mm.png';a.click()}
 if(!host||!catalog)return null;
 return createPortal(<section className="dash-card q-business-card"><div className="dash-toolbar"><div><div className="eyebrow">CARTE DE VISITE · 85 × 55 MM</div><h2>Créer votre carte de visite</h2><p>Format standard 85 × 55 mm, ratio ≈ 1,55:1. Le design reprend automatiquement les couleurs réelles du thème sélectionné. Génération : 50 crédits.</p></div><div className="qr-credit-pill"><b>{wallet}</b><span>crédits</span></div></div><div className="q-bc-grid"><div><div className="settings-v2-grid">{Object.entries({name:'Nom',role:'Fonction / activité',phone:'Téléphone',email:'Email',address:'Adresse',website:'Site web',other:'Autre information'}).map(([k,l])=><div className="field" key={k}><label>{l}</label><input className="input" value={(fields as any)[k]} onChange={e=>setFields({...fields,[k]:e.target.value})}/></div>)}<div className="field"><label>Police</label><select className="input" value={font} onChange={e=>setFont(e.target.value)}>{fonts.map(f=><option key={f}>{f}</option>)}</select></div><div className="field"><label>Logo</label><label className="btn btn-ghost"><Upload size={14}/>Importer un logo<input hidden type="file" accept="image/*" onChange={e=>{const f=e.target.files?.[0];if(f)void uploadLogo(f)}}/></label></div></div><div className="field"><label>Prompt / direction créative facultative</label><textarea className="input" rows={3} value={prompt} onChange={e=>setPrompt(e.target.value)} placeholder="Ex. élégant et minimal, ambiance premium, formes fluides…"/></div><p className="q-bc-note">Les champs non remplis sont totalement supprimés du rendu : aucun espace vide, aucun libellé inutile.</p><button className="btn btn-primary" onClick={generate} disabled={busy||wallet<50}>{busy?<Loader2 className="spin" size={16}/>:<Sparkles size={16}/>}Générer · 50 crédits</button>{background&&<button className="btn btn-ghost" onClick={()=>compose()}><ImagePlus size={15}/>Actualiser l’aperçu</button>}{error&&<p className="qpos-notice">{error}</p>}{progress&&<p className="qpos-notice">{progress}</p>}</div><div className="q-business-card-preview"><canvas/>{background?<button className="btn btn-primary" onClick={download}><Download size={15}/>Télécharger PNG</button>:<div className="q-bc-empty">Votre carte apparaîtra ici</div>}</div></div><div data-business-card-qr style={{position:'absolute',left:-99999}}><QRCodeSVG value={cardUrl} size={300} level="M" marginSize={4}/></div><style jsx>{`.q-business-card{margin-top:18px;position:relative}.q-bc-grid{display:grid;grid-template-columns:1.1fr .9fr;gap:20px}.q-business-card-preview canvas{width:100%;aspect-ratio:1.545/1;border-radius:18px;background:#f3f3f3;display:block}.q-bc-empty{min-height:280px;display:grid;place-items:center;border:1px dashed var(--line,#ddd);border-radius:18px}.q-bc-note{font-size:12px;color:var(--muted,#777)}@media(max-width:800px){.q-bc-grid{grid-template-columns:1fr}}`}</style></section>,host)}