'use client';

import {useEffect,useMemo,useRef,useState} from 'react';
import {createPortal} from 'react-dom';
import {AlertTriangle,ImagePlus,Link2,Save} from 'lucide-react';
import {createSupabaseBrowserClient} from '@/lib/supabase';

type Business={id:string;name:string;description:string|null;whatsapp_number:string|null;logo_url:string|null;cover_url:string|null};
type Catalog={id:string;title:string;public_slug:string;hub_public_slug:string|null};

function slugify(value:string){return value.normalize('NFD').replace(/[\u0300-\u036f]/g,'').toLowerCase().replace(/[^a-z0-9]+/g,'-').replace(/^-+|-+$/g,'').slice(0,48)||'catalogue'}
function suffix(){return Math.random().toString(36).slice(2,8)}

export function CatalogIdentityControls(){
  const supabase=useMemo(()=>createSupabaseBrowserClient(),[]);const [host,setHost]=useState<Element|null>(null);const [business,setBusiness]=useState<Business|null>(null);const [catalog,setCatalog]=useState<Catalog|null>(null);const [initialName,setInitialName]=useState('');const [notice,setNotice]=useState('');const [busy,setBusy]=useState('');const logoInput=useRef<HTMLInputElement|null>(null);const coverInput=useRef<HTMLInputElement|null>(null);
  useEffect(()=>{if(location.pathname!='/dashboard')return;let timer:any;const resolve=()=>{clearTimeout(timer);timer=setTimeout(()=>{const title=document.querySelector('.dash-v3-top h1')?.textContent?.trim()||'';setHost(title==='Vos catalogues'?document.querySelector('.dash-v3-main .dash-section')||document.querySelector('.dash-v3-main'):null)},30)};resolve();const mo=new MutationObserver(resolve);mo.observe(document.body,{subtree:true,childList:true,characterData:true});document.addEventListener('click',resolve,true);window.addEventListener('popstate',resolve);return()=>{clearTimeout(timer);mo.disconnect();document.removeEventListener('click',resolve,true);window.removeEventListener('popstate',resolve)}},[]);
  useEffect(()=>{if(!host)return;void load()},[host]);
  async function load(){const {data:b}=await supabase.from('businesses').select('id,name,description,whatsapp_number,logo_url,cover_url').order('created_at',{ascending:true}).limit(1).maybeSingle();if(!b)return;setBusiness(b as Business);setInitialName(String(b.name||''));let id=new URLSearchParams(location.search).get('catalog')||'';let q=supabase.from('catalogs').select('id,title,public_slug,hub_public_slug').eq('business_id',b.id);const {data:c}=id?await q.eq('id',id).maybeSingle():await q.order('created_at',{ascending:false}).limit(1).maybeSingle();setCatalog(c as Catalog|null)}
  async function upload(kind:'logo'|'cover',file?:File){if(!file||!business)return;if(!file.type.startsWith('image/')){setNotice('Choisissez une image.');return}setBusy(kind);const {data:{session}}=await supabase.auth.getSession();if(!session){setNotice('Session expirée.');setBusy('');return}const safe=file.name.replace(/[^a-zA-Z0-9._-]+/g,'-');const path=`${session.user.id}/business/${business.id}/${kind}-${Date.now()}-${safe}`;const up=await supabase.storage.from('catalog-assets').upload(path,file,{contentType:file.type||'image/jpeg'});if(up.error){setNotice(up.error.message);setBusy('');return}const {data:u}=supabase.storage.from('catalog-assets').getPublicUrl(path);const key=kind==='logo'?'logo_url':'cover_url';const {error}=await supabase.from('businesses').update({[key]:u.publicUrl}).eq('id',business.id);if(error)setNotice(error.message);else{setBusiness({...business,[key]:u.publicUrl});setNotice(kind==='logo'?'Logo mis à jour.':'Bannière mise à jour.')}setBusy('')}
  async function save(){if(!business)return;setBusy('save');const {error}=await supabase.from('businesses').update({name:business.name.trim(),description:business.description?.trim()||null,whatsapp_number:business.whatsapp_number?.trim()||null}).eq('id',business.id);setBusy('');setNotice(error?error.message:'Identité enregistrée.');if(!error&&business.name.trim()===initialName)setInitialName(business.name.trim())}
  const nameChanged=!!business&&business.name.trim()!==initialName.trim()&&business.name.trim().length>1;
  async function regenerateLinks(){if(!business||!catalog||!nameChanged)return;const ok=confirm('Changer les liens publics va invalider l’ancien lien du catalogue, l’ancien lien de page centrale et les anciens QR associés. De nouveaux QR devront être téléchargés/imprimés. Continuer ?');if(!ok)return;setBusy('links');const base=slugify(business.name);const nextMenu=`${base}-${suffix()}`;const nextHub=`${base}-${suffix()}`;const {error}=await supabase.from('catalogs').update({public_slug:nextMenu,hub_public_slug:nextHub}).eq('id',catalog.id);setBusy('');if(error){setNotice(error.message);return}setCatalog({...catalog,public_slug:nextMenu,hub_public_slug:nextHub});setInitialName(business.name.trim());setNotice('Nouveaux liens créés. Allez dans QR & partage pour télécharger les nouveaux QR.')}
  if(!host||!business||!catalog)return null;const proposedBase=slugify(business.name);return createPortal(<section className="dash-card catalog-identity-card"><div className="catalog-identity-head"><div><span className="eyebrow">IDENTITÉ & LIENS</span><h3>Informations visibles du catalogue</h3><p>Modifiez ici les informations essentielles sans devoir aller chercher dans Paramètres.</p></div><button className="btn btn-primary" disabled={busy==='save'} onClick={()=>void save()}><Save size={15}/>{busy==='save'?'Enregistrement…':'Enregistrer'}</button></div><div className="catalog-identity-grid"><label><span>Nom de la boutique</span><input className="input" value={business.name} onChange={e=>setBusiness({...business,name:e.target.value})}/></label><label><span>Numéro WhatsApp / contact</span><input className="input" value={business.whatsapp_number||''} onChange={e=>setBusiness({...business,whatsapp_number:e.target.value})} placeholder="Ex. +225 07 00 00 00 00"/></label><label className="wide"><span>Bio / description</span><textarea className="input" rows={3} value={business.description||''} onChange={e=>setBusiness({...business,description:e.target.value})}/></label><div className="catalog-media-control"><span>Logo</span>{business.logo_url?<img src={business.logo_url} alt="Logo"/>:<div className="catalog-media-empty"><ImagePlus/></div>}<button className="btn btn-ghost" onClick={()=>logoInput.current?.click()} disabled={busy==='logo'}>{busy==='logo'?'Import…':'Changer le logo'}</button><input ref={logoInput} hidden type="file" accept="image/*" onChange={e=>void upload('logo',e.target.files?.[0])}/></div><div className="catalog-media-control cover"><span>Bannière</span>{business.cover_url?<img src={business.cover_url} alt="Bannière"/>:<div className="catalog-media-empty"><ImagePlus/></div>}<button className="btn btn-ghost" onClick={()=>coverInput.current?.click()} disabled={busy==='cover'}>{busy==='cover'?'Import…':'Changer la bannière'}</button><input ref={coverInput} hidden type="file" accept="image/*" onChange={e=>void upload('cover',e.target.files?.[0])}/></div></div><div className="catalog-link-zone"><div><Link2/><div><b>Lien actuel du catalogue</b><code>https://qatalink.com/c/{catalog.public_slug}</code>{catalog.hub_public_slug&&<code>https://qatalink.com/h/{catalog.hub_public_slug}</code>}</div></div>{nameChanged&&<div className="catalog-link-proposal"><AlertTriangle/><div><b>Le nom a changé : voulez-vous aussi actualiser vos liens ?</b><p>Exemple de nouveau format : qatalink.com/c/{proposedBase}-xxxxxx. Cette action invalide les anciens liens et QR ; Qatalink génèrera de nouveaux identifiants permanents.</p><button className="btn btn-ghost" disabled={busy==='links'} onClick={()=>void regenerateLinks()}>{busy==='links'?'Création…':'Changer les liens et créer de nouveaux QR'}</button></div></div>}</div>{notice&&<p className="catalog-identity-notice">{notice}</p>}</section>,host);
}
