'use client';
import {useEffect,useMemo,useState} from 'react';
import {createPortal} from 'react-dom';
import {Gem} from 'lucide-react';
import {createSupabaseBrowserClient} from '@/lib/supabase';
const labels:Record<string,string>={free:'FREE',static:'STARTER',interactive:'PRO',linkhub:'BUSINESS'};
const buttonLabels:Record<string,string>={static:'Starter',interactive:'Pro',linkhub:'Business'};
export function DashboardPlanExperience(){
 const supabase=useMemo(()=>createSupabaseBrowserClient(),[]),[plan,setPlan]=useState(''),[active,setActive]=useState(false),[host,setHost]=useState<Element|null>(null);
 useEffect(()=>{if(location.pathname!='/dashboard')return;let cancelled=false;const locate=()=>setHost(document.querySelector('.dash-v3-actions'));locate();const obs=new MutationObserver(locate);obs.observe(document.body,{childList:true,subtree:true});void(async()=>{const {data:{session}}=await supabase.auth.getSession();if(!session)return;const {data:b}=await supabase.from('businesses').select('id').eq('owner_user_id',session.user.id).order('created_at',{ascending:true}).limit(1);if(!b?.[0]){if(!cancelled){setPlan('free');setActive(false)}return}const {data:s}=await supabase.from('subscriptions').select('plan_code,status,current_period_end').eq('business_id',b[0].id).order('created_at',{ascending:false}).limit(1);const row=s?.[0],valid=!!row&&row.status==='active'&&(!row.current_period_end||new Date(row.current_period_end)>new Date());if(!cancelled){setPlan(valid?String(row.plan_code||'free'):'free');setActive(valid)}})();return()=>{cancelled=true;obs.disconnect()}},[supabase]);
 useEffect(()=>{if(!plan)return;const basic=plan==='free'||plan==='static';const apply=()=>{const eyebrow=document.querySelector<HTMLElement>('.dash-v3-top .eyebrow');if(eyebrow&&labels[plan])eyebrow.textContent=labels[plan];const block=document.querySelector<HTMLElement>('.order-settings-block');if(!block)return;let note=block.querySelector<HTMLElement>('.q-plan-order-note');if(basic){if(!note){note=document.createElement('div');note.className='q-plan-order-note';note.innerHTML=`<b>${plan==='free'?'Free':'Starter'} · WhatsApp direct</b><span>Le client compose sa commande puis l’envoie sur WhatsApp. ${plan==='free'?'Free est limité à 10 commandes WhatsApp par jour. ':''}L’enregistrement privé et les accès équipe commencent avec Pro.</span>`;block.querySelector('.order-section-head')?.insertAdjacentElement('afterend',note)}block.querySelectorAll<HTMLLabelElement>('.order-checks label').forEach(label=>{const input=label.querySelector<HTMLInputElement>('input[type="checkbox"]');if(!input)return;if((label.textContent||'').includes('Enregistrer les commandes')){input.checked=false;input.disabled=true}if((label.textContent||'').includes('WhatsApp')){input.checked=true;input.disabled=true}});const access=block.querySelector<HTMLElement>('.order-access-box');if(access)access.style.display='none'}else{note?.remove();block.querySelectorAll<HTMLInputElement>('.order-checks input').forEach(i=>i.disabled=false);const access=block.querySelector<HTMLElement>('.order-access-box');if(access)access.style.removeProperty('display')}};apply();const interval=setInterval(apply,1200);const schedule=()=>setTimeout(apply,80);document.addEventListener('click',schedule,true);window.addEventListener('popstate',schedule);window.addEventListener('qatalink:catalog-change',schedule as EventListener);return()=>{clearInterval(interval);document.removeEventListener('click',schedule,true);window.removeEventListener('popstate',schedule);window.removeEventListener('qatalink:catalog-change',schedule as EventListener)}},[plan]);
 const pill=host?createPortal(<button type="button" className={`q-plan-header-pill ${active?'is-active':'is-upgrade'}`} onClick={()=>{window.location.href='/dashboard?tab=subscription'}} title={active?`Abonnement ${buttonLabels[plan]||plan} actif`:'Voir les formules Qatalink'}><Gem size={15}/><span>{active?(buttonLabels[plan]||'Abonnement actif'):'Passer en Pro'}</span></button>,host):null;
 return <>{pill}<style jsx global>{`.q-plan-header-pill{height:40px;border:0;border-radius:13px;padding:0 14px;display:inline-flex;align-items:center;gap:8px;font:800 13px/1 var(--font-jakarta),Arial,sans-serif;cursor:pointer;white-space:nowrap;box-shadow:0 8px 22px rgba(117,15,37,.18);transition:transform .18s ease,box-shadow .18s ease}.q-plan-header-pill:hover{transform:translateY(-1px);box-shadow:0 11px 26px rgba(117,15,37,.24)}.q-plan-header-pill.is-upgrade{color:#fff;background:linear-gradient(120deg,#891129 0%,#d42043 48%,#ff765d 100%)}.q-plan-header-pill.is-active{color:#7d1026;background:linear-gradient(120deg,#fff3d9,#fff,#f9dfe5);border:1px solid rgba(181,18,43,.16)}@media(max-width:680px){.q-plan-header-pill{height:36px;padding:0 11px;font-size:12px;border-radius:11px}.dash-v3-actions{gap:7px!important}.dash-v3-actions>.btn-primary{display:none!important}}`}</style></>;
}
