'use client';

import {Image as ImageIcon,Palette,Percent,Sparkles,Upload,X} from 'lucide-react';
import {useEffect,useMemo,useRef,useState} from 'react';
import {createSupabaseBrowserClient} from '@/lib/supabase';

type Item={id:string;name:string;price_minor:number|null;promo_price_minor:number|null;promo_starts_at:string|null;promo_ends_at:string|null};
type Theme={catalog_id:string;primary_color:string;secondary_color:string;background_color:string;background_mode:string;background_gradient:string;text_color:string;heading_font:string;body_font:string;border_radius:string;card_style:string;button_style:string;layout_style:string;logo_shape:string;show_business_name:boolean;show_logo:boolean;show_prices:boolean;header_alignment:string;background_image_url:string|null;background_image_overlay:number;background_image_blur:number;heading_bold:boolean;heading_italic:boolean;heading_underline:boolean;heading_case:string;body_bold:boolean;body_italic:boolean;body_underline:boolean;body_case:string};
const fonts=['Plus Jakarta Sans','Inter','Poppins','Montserrat','Playfair Display','DM Serif Display'];
const empty:Theme={catalog_id:'',primary_color:'#B5122B',secondary_color:'#F8DDE2',background_color:'#FFF9FA',background_mode:'gradient',background_gradient:'linear-gradient(160deg,#FFFDFD,#F8DDE2)',text_color:'#251317',heading_font:'Plus Jakarta Sans',body_font:'Plus Jakarta Sans',border_radius:'18px',card_style:'soft',button_style:'rounded',layout_style:'list',logo_shape:'rounded',show_business_name:true,show_logo:true,show_prices:true,header_alignment:'left',background_image_url:null,background_image_overlay:.18,background_image_blur:0,heading_bold:true,heading_italic:false,heading_underline:false,heading_case:'normal',body_bold:false,body_italic:false,body_underline:false,body_case:'normal'};
const toLocal=(v:string|null)=>v?new Date(v).toISOString().slice(0,16):'';
const toIso=(v:string)=>v?new Date(v).toISOString():null;

export function DashboardAdvancedControls(){
  const supabase=useMemo(()=>createSupabaseBrowserClient(),[]);
  const [open,setOpen]=useState(false);const [tab,setTab]=useState<'theme'|'promo'>('theme');const [session,setSession]=useState<any>(null);const [catalogId,setCatalogId]=useState('');const [business,setBusiness]=useState<any>(null);const [theme,setTheme]=useState<Theme>(empty);const [items,setItems]=useState<Item[]>([]);const [presets,setPresets]=useState<any[]>([]);const [busy,setBusy]=useState('');const [notice,setNotice]=useState('');const [bgPrompt,setBgPrompt]=useState('');const timer=useRef<ReturnType<typeof setTimeout>|null>(null);

  useEffect(()=>{(async()=>{const {data:{session:s}}=await supabase.auth.getSession();if(!s)return;setSession(s);const p=new URLSearchParams(location.search);let cid=p.get('catalog')||'';const {data:bs}=await supabase.from('businesses').select('id,name,business_type,logo_url').order('created_at',{ascending:true}).limit(1);const b=bs?.[0];setBusiness(b||null);if(!cid&&b){const {data:cs}=await supabase.from('catalogs').select('id').eq('business_id',b.id).order('created_at',{ascending:false}).limit(1);cid=cs?.[0]?.id||''}setCatalogId(cid);const [{data:t},{data:rows},{data:ps}]=await Promise.all([cid?supabase.from('catalog_theme_settings').select('*').eq('catalog_id',cid).maybeSingle():Promise.resolve({data:null}),cid?supabase.from('items').select('id,name,price_minor,promo_price_minor,promo_starts_at,promo_ends_at').eq('catalog_id',cid).order('sort_order'):Promise.resolve({data:[]}),supabase.from('sector_presets').select('id,label,business_type,default_theme').order('label')]);setTheme({...empty,catalog_id:cid,...(t||{})});setItems((rows||[]) as Item[]);setPresets(ps||[]);})();return()=>{if(timer.current)clearTimeout(timer.current)}},[]);

  async function publish(){if(!business?.id||!catalogId)return;await Promise.all([supabase.from('businesses').update({published:true}).eq('id',business.id),supabase.from('catalogs').update({is_active:true}).eq('id',catalogId)]);}
  async function saveTheme(next=theme){if(!catalogId)return;setBusy('theme');const payload={...next,catalog_id:catalogId,updated_at:new Date().toISOString()};const {error}=await supabase.from('catalog_theme_settings').upsert(payload,{onConflict:'catalog_id'});if(!error){await publish();setNotice('Apparence enregistrée et publiée sur le lien public.')}else setNotice(error.message);setBusy('')}
  async function applyPreset(p:any){const d=p.default_theme||{};const next={...theme,...d,catalog_id:catalogId};setTheme(next);if(business?.id)await supabase.from('businesses').update({business_type:p.business_type,theme_preset:p.id}).eq('id',business.id);await saveTheme(next)}

  async function analyzeThemeImage(imageUrl:string,label:string){if(!session||!imageUrl)return;setBusy('palette');const r=await fetch('/api/theme/from-logo',{method:'POST',headers:{'Content-Type':'application/json',Authorization:`Bearer ${session.access_token}`},body:JSON.stringify({image_url:imageUrl,business_type:business?.business_type||'other'})});const d=await r.json().catch(()=>({}));if(r.ok&&d.theme){const next={...theme,...d.theme,catalog_id:catalogId};setTheme(next);await saveTheme(next);setNotice(`Palette harmonieuse créée depuis ${label}.`)}else setNotice(d.error||'Analyse de l’image impossible.');setBusy('')}
  async function themeFromLogo(){if(!business?.logo_url)return setNotice('Ajoutez d’abord un logo dans Paramètres.');await analyzeThemeImage(business.logo_url,'votre logo')}
  async function paletteFromImage(file:File){if(!session||!catalogId)return;setBusy('palette-upload');const safe=file.name.replace(/[^a-zA-Z0-9._-]+/g,'-');const path=`${session.user.id}/palette-sources/${catalogId}/${Date.now()}-${safe}`;const up=await supabase.storage.from('catalog-assets').upload(path,file,{contentType:file.type||'image/jpeg'});if(up.error){setNotice(up.error.message);setBusy('');return}const {data:u}=supabase.storage.from('catalog-assets').getPublicUrl(path);setBusy('');await analyzeThemeImage(u.publicUrl,'l’image importée')}

  async function uploadBackground(file:File){if(!session||!catalogId)return;setBusy('bg');const safe=file.name.replace(/[^a-zA-Z0-9._-]+/g,'-');const path=`${session.user.id}/backgrounds/${catalogId}/${Date.now()}-${safe}`;const up=await supabase.storage.from('catalog-assets').upload(path,file,{contentType:file.type||'image/jpeg'});if(up.error){setNotice(up.error.message);setBusy('');return}const {data:u}=supabase.storage.from('catalog-assets').getPublicUrl(path);const next={...theme,background_image_url:u.publicUrl};setTheme(next);await saveTheme(next);setNotice('Image de fond appliquée et publiée.');setBusy('')}
  async function removeBackground(){const next={...theme,background_image_url:null,background_image_blur:0};setTheme(next);await saveTheme(next);setNotice('Image de fond retirée.')}
  async function generateBackground(){if(!session||!catalogId||!bgPrompt.trim())return;setBusy('genbg');const r=await fetch('/api/theme/background/submit',{method:'POST',headers:{'Content-Type':'application/json',Authorization:`Bearer ${session.access_token}`},body:JSON.stringify({catalog_id:catalogId,prompt:bgPrompt.trim()})});const d=await r.json().catch(()=>({}));if(!r.ok){setBusy('');setNotice(d.error==='INSUFFICIENT_CREDITS'?'Crédits insuffisants : une image de fond coûte 5 crédits.':d.error||'Génération impossible.');return}pollBackground(d.job_id)}
  async function pollBackground(jobId:string){if(!session)return;const r=await fetch('/api/theme/background/status',{method:'POST',headers:{'Content-Type':'application/json',Authorization:`Bearer ${session.access_token}`},body:JSON.stringify({job_id:jobId})});const d=await r.json().catch(()=>({}));if(d.status==='completed'){const next={...theme,background_image_url:d.image_url};setTheme(next);await saveTheme(next);setBusy('');setNotice('Image de fond générée, sauvegardée et publiée.');return}if(d.status==='failed'){setBusy('');setNotice(d.error||'Génération échouée.');return}timer.current=setTimeout(()=>pollBackground(jobId),3000)}
  async function savePromo(item:Item){setBusy(`promo-${item.id}`);const {error}=await supabase.from('items').update({promo_price_minor:item.promo_price_minor||null,promo_starts_at:item.promo_price_minor?item.promo_starts_at:null,promo_ends_at:item.promo_price_minor?item.promo_ends_at:null}).eq('id',item.id);if(!error){await publish();setNotice(`Promotion de ${item.name} enregistrée.`)}else setNotice(error.message);setBusy('')}

  if(!catalogId)return null;
  return <><button className="advanced-studio-trigger" onClick={()=>setOpen(true)}><Palette size={17}/>Studio avancé</button>{open&&<div className="advanced-studio-backdrop"><section className="advanced-studio"><header><div><span>QATALINK STUDIO</span><h2>Personnalisation avancée</h2></div><button onClick={()=>setOpen(false)}><X/></button></header><div className="advanced-tabs"><button className={tab==='theme'?'active':''} onClick={()=>setTab('theme')}><Palette size={15}/>Thème & layout</button><button className={tab==='promo'?'active':''} onClick={()=>setTab('promo')}><Percent size={15}/>Promotions</button></div>{notice&&<div className="advanced-notice">{notice}</div>}
  {tab==='theme'&&<div className="advanced-body"><div className="advanced-card"><h3>Preset métier</h3><div className="advanced-preset-grid">{presets.map(p=><button key={p.id} onClick={()=>applyPreset(p)}><b>{p.label}</b><small>{p.business_type}</small></button>)}</div></div><div className="advanced-card"><h3>Layout</h3><select className="input" value={theme.layout_style} onChange={e=>setTheme({...theme,layout_style:e.target.value})}><option value="list">Liste avec miniatures</option><option value="compact">Liste compacte</option><option value="cards">Cartes 2 colonnes</option><option value="grid">Grille visuelle</option><option value="showcase">Showcase image + texte</option></select></div><div className="advanced-card"><h3>Typographie des titres</h3><div className="advanced-grid"><select className="input" value={theme.heading_font} onChange={e=>setTheme({...theme,heading_font:e.target.value})}>{fonts.map(f=><option key={f}>{f}</option>)}</select><select className="input" value={theme.heading_case} onChange={e=>setTheme({...theme,heading_case:e.target.value})}><option value="normal">Casse normale</option><option value="uppercase">MAJUSCULES</option><option value="lowercase">minuscules</option><option value="capitalize">Capitales</option></select></div><div className="format-toggles"><label><input type="checkbox" checked={theme.heading_bold} onChange={e=>setTheme({...theme,heading_bold:e.target.checked})}/> Gras</label><label><input type="checkbox" checked={theme.heading_italic} onChange={e=>setTheme({...theme,heading_italic:e.target.checked})}/> Italique</label><label><input type="checkbox" checked={theme.heading_underline} onChange={e=>setTheme({...theme,heading_underline:e.target.checked})}/> Souligné</label></div></div><div className="advanced-card"><h3>Typographie du texte</h3><div className="advanced-grid"><select className="input" value={theme.body_font} onChange={e=>setTheme({...theme,body_font:e.target.value})}>{fonts.slice(0,4).map(f=><option key={f}>{f}</option>)}</select><select className="input" value={theme.body_case} onChange={e=>setTheme({...theme,body_case:e.target.value})}><option value="normal">Casse normale</option><option value="uppercase">MAJUSCULES</option><option value="lowercase">minuscules</option><option value="capitalize">Capitales</option></select></div><div className="format-toggles"><label><input type="checkbox" checked={theme.body_bold} onChange={e=>setTheme({...theme,body_bold:e.target.checked})}/> Gras</label><label><input type="checkbox" checked={theme.body_italic} onChange={e=>setTheme({...theme,body_italic:e.target.checked})}/> Italique</label><label><input type="checkbox" checked={theme.body_underline} onChange={e=>setTheme({...theme,body_underline:e.target.checked})}/> Souligné</label></div></div>
  <div className="advanced-card"><h3>Créer une palette harmonieuse depuis une image</h3><p>Utilisez votre logo, une façade, un flyer, un packaging ou une photo de votre univers visuel. Qatalink analyse les couleurs et construit automatiquement une combinaison fond/texte lisible et cohérente.</p><div className="advanced-palette-preview"><span style={{background:theme.primary_color}}/><span style={{background:theme.secondary_color}}/><span style={{background:theme.background_color}}/><span style={{background:theme.text_color}}/></div><div className="advanced-grid"><button className="btn btn-ghost" onClick={themeFromLogo} disabled={busy==='palette'}><Sparkles size={15}/>{busy==='palette'?'Analyse…':'Utiliser mon logo'}</button><label className="btn btn-ghost"><Upload size={15}/>Analyser une autre image<input hidden type="file" accept="image/*" onChange={e=>{const f=e.target.files?.[0];if(f)paletteFromImage(f)}}/></label></div></div>
  <div className="advanced-card"><h3>Fond d’écran du menu</h3><p>Importez une image qui sera réellement utilisée derrière votre menu public, ou générez-en une. Réglez ensuite l’assombrissement et le flou pour garder les textes lisibles.</p>{theme.background_image_url&&<img className="advanced-bg-preview" src={theme.background_image_url} alt="Fond actuel"/>}<div className="advanced-grid"><label className="btn btn-ghost"><Upload size={15}/>Choisir une image<input hidden type="file" accept="image/*" onChange={e=>{const f=e.target.files?.[0];if(f)uploadBackground(f)}}/></label>{theme.background_image_url&&<button className="btn btn-ghost" onClick={removeBackground}>Retirer le fond</button>}</div><div className="advanced-grid"><input className="input" value={bgPrompt} onChange={e=>setBgPrompt(e.target.value)} placeholder="Ex : marbre noir élégant, lumière douce…"/><button className="btn btn-ghost" onClick={generateBackground} disabled={busy==='genbg'}><ImageIcon size={15}/>{busy==='genbg'?'Génération…':'Générer · 5 crédits'}</button></div><label className="advanced-range">Assombrissement pour lisibilité <input type="range" min="0" max="0.75" step="0.05" value={theme.background_image_overlay} onChange={e=>setTheme({...theme,background_image_overlay:Number(e.target.value)})}/><b>{Math.round(theme.background_image_overlay*100)}%</b></label><label className="advanced-range">Flou du fond <input type="range" min="0" max="30" step="1" value={theme.background_image_blur} onChange={e=>setTheme({...theme,background_image_blur:Number(e.target.value)})}/><b>{theme.background_image_blur}px</b></label></div><button className="btn btn-primary advanced-save" onClick={()=>saveTheme()} disabled={busy==='theme'}>Enregistrer & publier</button></div>}
  {tab==='promo'&&<div className="advanced-body"><div className="advanced-card"><h3>Prix promotionnels</h3><p>Le prix normal revient automatiquement à la fin de la période.</p></div>{items.map((item,index)=><div className="advanced-card promo-editor" key={item.id}><div><b>{item.name}</b><small>Prix normal : {new Intl.NumberFormat('fr-FR').format(Number(item.price_minor||0))} F</small></div><div className="advanced-grid"><input className="input" type="number" min="0" placeholder="Prix promo" value={item.promo_price_minor??''} onChange={e=>setItems(x=>x.map((v,i)=>i===index?{...v,promo_price_minor:e.target.value===''?null:Number(e.target.value)}:v))}/><label>Début<input className="input" type="datetime-local" value={toLocal(item.promo_starts_at)} onChange={e=>setItems(x=>x.map((v,i)=>i===index?{...v,promo_starts_at:toIso(e.target.value)}:v))}/></label><label>Fin<input className="input" type="datetime-local" value={toLocal(item.promo_ends_at)} onChange={e=>setItems(x=>x.map((v,i)=>i===index?{...v,promo_ends_at:toIso(e.target.value)}:v))}/></label><button className="btn btn-ghost" onClick={()=>savePromo(item)} disabled={busy===`promo-${item.id}`}>Enregistrer</button></div></div>)}</div>}</section></div>}</>;
}
