'use client';

import {useEffect,useMemo,useState} from 'react';
import {AlertTriangle,BarChart3,CalendarDays,CloudRain,Database,PackageCheck,Sparkles,TrendingUp,Upload,X} from 'lucide-react';
import {createSupabaseBrowserClient} from '@/lib/supabase';

type Workspace={profile?:any;events?:any[];imports?:any[];run?:any;results?:any[];recommendations?:any[]};
const AUDIENCES=['Familles','Jeunes actifs','Étudiants','Entreprises','Touristes','Nightlife','Livraison','Quartier / proximité'];

function money(v:any){return `${new Intl.NumberFormat('fr-FR',{maximumFractionDigits:0}).format(Number(v||0)).replace(/\u202f/g,' ')} F CFA`}
function num(v:any,d=1){return new Intl.NumberFormat('fr-FR',{maximumFractionDigits:d}).format(Number(v||0))}

export function DashboardForecastBeta(){
  const supabase=useMemo(()=>createSupabaseBrowserClient(),[]);
  const [open,setOpen]=useState(false);const [businessId,setBusinessId]=useState('');const [workspace,setWorkspace]=useState<Workspace|null>(null);const [locked,setLocked]=useState(false);const [busy,setBusy]=useState('');const [error,setError]=useState('');const [tab,setTab]=useState<'overview'|'context'|'history'|'events'>('overview');
  const [profile,setProfile]=useState<any>({location_label:'',latitude:'',longitude:'',service_radius_km:5,audience_tags:[],locality_notes:'',weather_sensitivity:'medium',business_context:{delivery_heavy:false},external_research_enabled:true,default_horizon_days:7,safety_stock_days:2});
  const [event,setEvent]=useState<any>({event_type:'promotion',title:'',starts_at:'',ends_at:'',expected_direction:'up',expected_impact_pct:'',notes:''});
  const [importText,setImportText]=useState('');const [importFiles,setImportFiles]=useState<File[]>([]);const [preview,setPreview]=useState<any>(null);const [horizon,setHorizon]=useState(7);

  useEffect(()=>{
    if(location.pathname!='/dashboard')return;let stopped=false;let observer:MutationObserver|null=null;
    const mount=()=>{for(const selector of ['.dash-v3-nav','.dash-v3-mobile-tabs']){const host=document.querySelector(selector);if(!host||host.querySelector('[data-qforecast]'))continue;const wrap=document.createElement('div');wrap.setAttribute('data-qforecast','1');const btn=document.createElement('button');btn.type='button';btn.className='side-item qforecast-nav';btn.innerHTML='<span aria-hidden="true">◈</span><span>Prévisions</span><em>BETA</em>';btn.onclick=()=>setOpen(true);wrap.appendChild(btn);host.appendChild(wrap)}};
    mount();observer=new MutationObserver(()=>{if(!stopped)mount()});observer.observe(document.body,{childList:true,subtree:true});return()=>{stopped=true;observer?.disconnect();document.querySelectorAll('[data-qforecast]').forEach(x=>x.remove())};
  },[]);

  useEffect(()=>{if(!open)return;void resolveBusiness()},[open]);

  async function token(){const {data}=await supabase.auth.getSession();return data.session?.access_token||''}
  async function call(action:string,payload:any={}){const t=await token();const r=await fetch('/api/forecast',{method:'POST',headers:{'Content-Type':'application/json',Authorization:`Bearer ${t}`},body:JSON.stringify({action,business_id:businessId,...payload}),cache:'no-store'});const j=await r.json().catch(()=>({}));if(!r.ok)throw Object.assign(new Error(j?.error||'FORECAST_FAILED'),{status:r.status});return j}
  async function resolveBusiness(){setBusy('load');setError('');try{const {data:{user}}=await supabase.auth.getUser();if(!user)throw new Error('Session expirée');let bid='';const catalog=new URLSearchParams(location.search).get('catalog');if(catalog){const {data}=await supabase.from('catalogs').select('business_id').eq('id',catalog).maybeSingle();bid=String(data?.business_id||'')}if(!bid){const {data}=await supabase.from('businesses').select('id').eq('owner_user_id',user.id).order('created_at',{ascending:true}).limit(1);bid=String(data?.[0]?.id||'')}if(!bid)throw new Error('Entreprise introuvable');setBusinessId(bid);const t=await token();const r=await fetch('/api/forecast',{method:'POST',headers:{'Content-Type':'application/json',Authorization:`Bearer ${t}`},body:JSON.stringify({action:'workspace',business_id:bid}),cache:'no-store'});const j=await r.json().catch(()=>({}));if(r.status===403){setLocked(true);setWorkspace(null);return}if(!r.ok)throw new Error(j?.error||'FORECAST_FAILED');setLocked(false);setWorkspace(j);if(j.profile)setProfile((p:any)=>({...p,...j.profile,business_context:{...p.business_context,...(j.profile.business_context||{})}}));if(j.run?.horizon_days)setHorizon(Number(j.run.horizon_days))}catch(e:any){setError(e?.message||'Impossible de charger les prévisions.')}finally{setBusy('')}}
  async function refresh(){if(!businessId)return;try{const j=await call('workspace');setWorkspace(j);if(j.profile)setProfile((p:any)=>({...p,...j.profile,business_context:{...p.business_context,...(j.profile.business_context||{})}}))}catch(e:any){setError(e.message)}}
  async function saveProfile(){setBusy('profile');try{await call('profile',{profile});await refresh()}catch(e:any){setError(e.message)}finally{setBusy('')}}
  async function addEvent(){if(!event.title.trim()||!event.starts_at)return;setBusy('event');try{await call('event',{event});setEvent({event_type:'promotion',title:'',starts_at:'',ends_at:'',expected_direction:'up',expected_impact_pct:'',notes:''});await refresh()}catch(e:any){setError(e.message)}finally{setBusy('')}}
  async function run(){setBusy('run');setError('');try{const j=await call('run',{horizon_days:horizon});await refresh();if(j.results?.length===0)setError('Pas encore assez d’historique exploitable. Importez des ventes ou utilisez Qatalink quelques jours.')}catch(e:any){setError(e.message)}finally{setBusy('')}}
  function readFile(file:File){return new Promise<string>((resolve,reject)=>{const r=new FileReader();r.onload=()=>resolve(String(r.result||''));r.onerror=reject;r.readAsDataURL(file)})}
  async function previewImport(){if(!importText.trim()&&!importFiles.length)return;setBusy('preview');setError('');try{const images=await Promise.all(importFiles.slice(0,6).map(readFile));const j=await call('preview_import',{source_type:images.length?'ocr':'text',text:importText,image_data_urls:images,image_data_url:images[0]||''});setPreview(j)}catch(e:any){setError(e.message)}finally{setBusy('')}}
  async function commitImport(){if(!preview?.rows?.length)return;setBusy('commit');try{await call('commit_import',{source_type:importFiles.length?'ocr':'text',label:importFiles.length?`${importFiles.length} image(s) historique`:'Historique texte',rows:preview.rows,metadata:{warnings:preview.warnings||[],confidence:preview.confidence}});setPreview(null);setImportText('');setImportFiles([]);await refresh()}catch(e:any){setError(e.message)}finally{setBusy('')}}
  function toggleAudience(a:string){setProfile((p:any)=>({...p,audience_tags:(p.audience_tags||[]).includes(a)?p.audience_tags.filter((x:string)=>x!==a):[...(p.audience_tags||[]),a]}))}

  if(!open)return null;
  const results=workspace?.results||[], recs=workspace?.recommendations||[];const totalRevenue=results.reduce((s:number,r:any)=>s+Number(r.forecast_revenue_minor||0),0);const risky=recs.filter((r:any)=>['critical','high'].includes(r.risk_level));
  return <div className="qforecast-backdrop" onMouseDown={e=>{if(e.target===e.currentTarget)setOpen(false)}}><section className="qforecast-modal">
    <header className="qforecast-head"><div><span>QATALINK BUSINESS <b>BETA</b></span><h2>Prévisions & approvisionnement</h2><p>Anticipez la demande, les ruptures et les besoins d’achat à partir de vos ventes, du contexte et de facteurs externes.</p></div><button onClick={()=>setOpen(false)}><X/></button></header>
    {locked?<div className="qforecast-lock"><Sparkles/><h3>Fonctionnalité Business</h3><p>Les prévisions, recommandations d’approvisionnement et facteurs externes sont réservés à Business.</p><a href="/#pricing">Voir Business</a></div>:<>
      <nav className="qforecast-tabs"><button className={tab==='overview'?'active':''} onClick={()=>setTab('overview')}><TrendingUp/>Prévisions</button><button className={tab==='context'?'active':''} onClick={()=>setTab('context')}><CloudRain/>Contexte</button><button className={tab==='history'?'active':''} onClick={()=>setTab('history')}><Database/>Historique</button><button className={tab==='events'?'active':''} onClick={()=>setTab('events')}><CalendarDays/>Actions & événements</button></nav>
      {busy==='load'?<div className="qforecast-loading">Chargement…</div>:tab==='overview'?<div className="qforecast-view">
        <div className="qforecast-runbar"><label>Horizon<select value={horizon} onChange={e=>setHorizon(Number(e.target.value))}><option value={7}>7 jours</option><option value={14}>14 jours</option><option value={30}>30 jours</option></select></label><button onClick={run} disabled={busy==='run'}><Sparkles/>{busy==='run'?'Calcul…':'Actualiser les prévisions'}</button></div>
        <div className="qforecast-kpis"><article><span>CA prévu</span><b>{money(totalRevenue)}</b><small>{workspace?.run?`${workspace.run.horizon_days} prochains jours`:'Lancez un calcul'}</small></article><article><span>Risques de rupture</span><b>{risky.length}</b><small>{recs.length} composants analysés</small></article><article><span>Historique importé</span><b>{workspace?.imports?.reduce((s:number,x:any)=>s+Number(x.row_count||0),0)||0}</b><small>+ ventes Qatalink automatiques</small></article></div>
        <div className="qforecast-grid"><section><div className="qforecast-title"><BarChart3/><div><h3>Demande prévue</h3><p>Article par article, avec saisonnalité et tendance.</p></div></div>{results.length?<div className="qforecast-table">{results.slice(0,30).map((r:any)=><div key={r.id||r.item_id||r.item_name}><div><b>{r.item_name}</b><small>{r.explanation}</small></div><strong>{num(r.forecast_quantity)} u.</strong><span className={`confidence c${Math.round(Number(r.confidence||0)*10)}`}>{Math.round(Number(r.confidence||0)*100)} %</span></div>)}</div>:<div className="qforecast-empty">Aucune prévision calculée.</div>}</section>
        <section><div className="qforecast-title"><PackageCheck/><div><h3>Approvisionnement</h3><p>Besoin prévu + stock de sécurité − stock actuel.</p></div></div>{recs.length?<div className="qforecast-table">{recs.slice(0,30).map((r:any)=><div key={r.id||r.stock_item_id} className={`risk-${r.risk_level}`}><div><b>{r.stock_item_name}</b><small>{r.reason}</small></div><strong>{Number(r.recommended_quantity)>0?`+${num(r.recommended_quantity)}`:'OK'}</strong><span>{Number(r.coverage_days)>100?'—':`${num(r.coverage_days)} j`}</span></div>)}</div>:<div className="qforecast-empty">Reliez vos articles au stock pour obtenir les besoins nets.</div>}</section></div>
      </div>:tab==='context'?<div className="qforecast-view"><div className="qforecast-form-grid"><label>Localisation principale<input value={profile.location_label||''} onChange={e=>setProfile({...profile,location_label:e.target.value})} placeholder="Ex : Marcory Zone 4, Abidjan"/></label><label>Rayon de clientèle (km)<input type="number" value={profile.service_radius_km||5} onChange={e=>setProfile({...profile,service_radius_km:e.target.value})}/></label><label>Latitude<input type="number" step="0.000001" value={profile.latitude??''} onChange={e=>setProfile({...profile,latitude:e.target.value})}/></label><label>Longitude<input type="number" step="0.000001" value={profile.longitude??''} onChange={e=>setProfile({...profile,longitude:e.target.value})}/></label><label>Sensibilité météo<select value={profile.weather_sensitivity||'medium'} onChange={e=>setProfile({...profile,weather_sensitivity:e.target.value})}><option value="low">Faible</option><option value="medium">Moyenne</option><option value="high">Forte</option></select></label><label>Stock de sécurité<input type="number" step=".5" min="0" value={profile.safety_stock_days??2} onChange={e=>setProfile({...profile,safety_stock_days:e.target.value})}/><small>Nombre de jours de demande à garder en réserve.</small></label></div><div className="qforecast-audiences"><b>Clientèle habituelle / ciblée</b><div>{AUDIENCES.map(a=><button key={a} className={(profile.audience_tags||[]).includes(a)?'active':''} onClick={()=>toggleAudience(a)}>{a}</button>)}</div></div><label className="qforecast-wide">Contexte local et habitudes<textarea value={profile.locality_notes||''} onChange={e=>setProfile({...profile,locality_notes:e.target.value})} placeholder="Ex : clientèle de bureaux à midi, fort trafic vendredi soir, zone très sensible aux pluies…"/></label><label className="qforecast-check"><input type="checkbox" checked={!!profile.business_context?.delivery_heavy} onChange={e=>setProfile({...profile,business_context:{...(profile.business_context||{}),delivery_heavy:e.target.checked}})}/>Activité fortement orientée livraison</label><label className="qforecast-check"><input type="checkbox" checked={profile.external_research_enabled!==false} onChange={e=>setProfile({...profile,external_research_enabled:e.target.checked})}/>Autoriser l’analyse de facteurs externes pertinents</label><button className="qforecast-primary" onClick={saveProfile} disabled={busy==='profile'}>{busy==='profile'?'Enregistrement…':'Enregistrer le contexte'}</button><p className="qforecast-note">La météo locale structurée est intégrée dès qu’une latitude/longitude est renseignée. Les événements commerciaux saisis ci-dessous modulent aussi les calculs.</p></div>
      :tab==='history'?<div className="qforecast-view"><div className="qforecast-import"><div><Upload/><h3>Compléter l’historique</h3><p>Les ventes Qatalink sont utilisées automatiquement. Ajoutez en plus du texte brut, des captures, photos, rapports ou plusieurs pages OCR : toutes les sources sont consolidées.</p></div><textarea value={importText} onChange={e=>setImportText(e.target.value)} placeholder="Collez ici un historique de ventes, même non structuré…"/><label className="qforecast-file"><input type="file" accept="image/*" multiple onChange={e=>setImportFiles(Array.from(e.target.files||[]).slice(0,6))}/><span>Ajouter des images / captures ({importFiles.length}/6)</span></label><button onClick={previewImport} disabled={busy==='preview'||(!importText.trim()&&!importFiles.length)}>{busy==='preview'?'Analyse…':'Analyser avant import'}</button></div>{preview&&<section className="qforecast-preview"><header><div><h3>Aperçu détecté</h3><p>{preview.rows?.length||0} lignes · confiance {preview.confidence!=null?`${Math.round(Number(preview.confidence)*100)} %`:'—'}</p></div><button onClick={()=>setPreview(null)}><X/></button></header>{preview.warnings?.length>0&&<div className="qforecast-warning"><AlertTriangle/>{preview.warnings.join(' · ')}</div>}<div className="qforecast-preview-rows">{(preview.rows||[]).slice(0,80).map((r:any,i:number)=><div key={i}><span>{r.sold_on}</span><b>{r.item_name}</b><strong>{num(r.quantity)}</strong><em>{r.revenue_minor?money(r.revenue_minor):'—'}</em></div>)}</div><button className="qforecast-primary" onClick={commitImport} disabled={busy==='commit'}>{busy==='commit'?'Import…':'Valider et fusionner avec l’historique'}</button></section>}<div className="qforecast-import-list"><h3>Sources déjà intégrées</h3>{workspace?.imports?.length?workspace.imports.map((x:any)=><div key={x.id}><b>{x.label||x.source_type}</b><span>{x.row_count} lignes</span><small>{new Date(x.created_at).toLocaleString('fr-FR')}</small></div>):<p>Aucun import externe pour le moment.</p>}</div></div>
      :<div className="qforecast-view"><div className="qforecast-event-form"><h3>Ajouter une action ou un événement interne</h3><p>Promotion, changement de prix, campagne publicitaire, lancement, fermeture, rupture, influenceur ou événement spécial.</p><div className="qforecast-form-grid"><label>Type<select value={event.event_type} onChange={e=>setEvent({...event,event_type:e.target.value})}><option value="promotion">Promotion</option><option value="campaign">Campagne marketing</option><option value="price_change">Changement de prix</option><option value="launch">Nouveau produit</option><option value="closure">Fermeture / travaux</option><option value="stockout">Rupture exceptionnelle</option><option value="event">Événement</option><option value="other">Autre</option></select></label><label>Titre<input value={event.title} onChange={e=>setEvent({...event,title:e.target.value})} placeholder="Ex : promo -20 % burgers"/></label><label>Début<input type="datetime-local" value={event.starts_at} onChange={e=>setEvent({...event,starts_at:e.target.value})}/></label><label>Fin<input type="datetime-local" value={event.ends_at} onChange={e=>setEvent({...event,ends_at:e.target.value})}/></label><label>Impact attendu<select value={event.expected_direction} onChange={e=>setEvent({...event,expected_direction:e.target.value})}><option value="up">Hausse</option><option value="down">Baisse</option><option value="neutral">Neutre</option><option value="unknown">Inconnu</option></select></label><label>Amplitude estimée (%)<input type="number" value={event.expected_impact_pct} onChange={e=>setEvent({...event,expected_impact_pct:e.target.value})} placeholder="Ex : 15"/></label></div><label className="qforecast-wide">Notes<textarea value={event.notes} onChange={e=>setEvent({...event,notes:e.target.value})}/></label><button className="qforecast-primary" onClick={addEvent} disabled={busy==='event'||!event.title||!event.starts_at}>Ajouter à la timeline</button></div><div className="qforecast-events">{workspace?.events?.map((e:any)=><article key={e.id}><span>{e.event_type}</span><div><b>{e.title}</b><small>{new Date(e.starts_at).toLocaleString('fr-FR')}{e.ends_at?` → ${new Date(e.ends_at).toLocaleString('fr-FR')}`:''}</small>{e.notes&&<p>{e.notes}</p>}</div><strong>{e.expected_direction==='up'?'+':e.expected_direction==='down'?'-':''}{e.expected_impact_pct?`${Math.abs(Number(e.expected_impact_pct))} %`:'?'}</strong></article>)}</div></div>}
      {error&&<div className="qforecast-error">{error}</div>}
    </>}
  </section></div>;
}
