'use client';

import {useEffect,useMemo,useState} from 'react';
import {AlertTriangle,ArrowLeft,ArrowRight,BarChart3,CalendarDays,Check,CloudRain,Database,Globe2,PackageCheck,Sparkles,Upload,X} from 'lucide-react';
import {createSupabaseBrowserClient} from '@/lib/supabase';

type Workspace={profile?:any;events?:any[];external_factors?:any[];imports?:any[];run?:any;results?:any[];recommendations?:any[]};
const AUDIENCES=['Familles','Jeunes actifs','Étudiants','Entreprises','Touristes','Nightlife','Livraison','Quartier / proximité'];
const STEPS=['Contexte','Historique','Actions','Préférences','Résultats'];
function money(v:any){return `${new Intl.NumberFormat('fr-FR',{maximumFractionDigits:0}).format(Number(v||0)).replace(/\u202f/g,' ')} F CFA`}
function num(v:any,d=1){return new Intl.NumberFormat('fr-FR',{maximumFractionDigits:d}).format(Number(v||0))}

export function DashboardForecastWizard(){
  const supabase=useMemo(()=>createSupabaseBrowserClient(),[]);
  const [open,setOpen]=useState(false);const [businessId,setBusinessId]=useState('');const [workspace,setWorkspace]=useState<Workspace|null>(null);const [locked,setLocked]=useState(false);const [busy,setBusy]=useState('');const [error,setError]=useState('');const [step,setStep]=useState(0);
  const [profile,setProfile]=useState<any>({location_label:'',latitude:'',longitude:'',service_radius_km:5,audience_tags:[],locality_notes:'',weather_sensitivity:'medium',business_context:{delivery_heavy:false,sector:''},external_research_enabled:true,default_horizon_days:7,safety_stock_days:2});
  const [event,setEvent]=useState<any>({event_type:'promotion',title:'',starts_at:'',ends_at:'',expected_direction:'up',expected_impact_pct:'',notes:''});
  const [importText,setImportText]=useState('');const [importFiles,setImportFiles]=useState<File[]>([]);const [preview,setPreview]=useState<any>(null);const [horizon,setHorizon]=useState(7);const [scanMessage,setScanMessage]=useState('');

  useEffect(()=>{if(location.pathname!='/dashboard')return;let stopped=false;const mount=()=>{for(const selector of ['.dash-v3-nav','.dash-v3-mobile-tabs']){const host=document.querySelector(selector);if(!host||host.querySelector('[data-qforecast]'))continue;const wrap=document.createElement('div');wrap.dataset.qforecast='1';const btn=document.createElement('button');btn.type='button';btn.className='side-item qforecast-nav';btn.innerHTML='<span aria-hidden="true">◈</span><span>Prévisions</span><em>BETA</em>';btn.onclick=()=>{setStep(0);setOpen(true)};wrap.appendChild(btn);host.appendChild(wrap)}};mount();const o=new MutationObserver(()=>{if(!stopped)mount()});o.observe(document.body,{childList:true,subtree:true});return()=>{stopped=true;o.disconnect();document.querySelectorAll('[data-qforecast]').forEach(x=>x.remove())}},[]);
  useEffect(()=>{if(open)void resolveBusiness()},[open]);

  async function token(){const {data}=await supabase.auth.getSession();return data.session?.access_token||''}
  async function request(bid:string,action:string,payload:any={}){const t=await token();const r=await fetch('/api/forecast',{method:'POST',headers:{'Content-Type':'application/json',Authorization:`Bearer ${t}`},body:JSON.stringify({action,business_id:bid,...payload}),cache:'no-store'});const j=await r.json().catch(()=>({}));if(!r.ok)throw Object.assign(new Error(j?.error||'FORECAST_FAILED'),{status:r.status});return j}
  async function resolveBusiness(){setBusy('load');setError('');try{const {data:{user}}=await supabase.auth.getUser();if(!user)throw new Error('Session expirée');let bid='';const catalog=new URLSearchParams(location.search).get('catalog');if(catalog){const {data}=await supabase.from('catalogs').select('business_id').eq('id',catalog).maybeSingle();bid=String(data?.business_id||'')}if(!bid){const {data}=await supabase.from('businesses').select('id').eq('owner_user_id',user.id).order('created_at',{ascending:true}).limit(1);bid=String(data?.[0]?.id||'')}if(!bid)throw new Error('Entreprise introuvable');setBusinessId(bid);const t=await token();const r=await fetch('/api/forecast',{method:'POST',headers:{'Content-Type':'application/json',Authorization:`Bearer ${t}`},body:JSON.stringify({action:'workspace',business_id:bid}),cache:'no-store'});const j=await r.json().catch(()=>({}));if(r.status===403){setLocked(true);setWorkspace(null);return}if(!r.ok)throw new Error(j?.error||'FORECAST_FAILED');setLocked(false);setWorkspace(j);if(j.profile)setProfile((p:any)=>({...p,...j.profile,business_context:{...p.business_context,...(j.profile.business_context||{})}}));if(j.run?.horizon_days)setHorizon(Number(j.run.horizon_days))}catch(e:any){setError(e.message||'Impossible de charger les prévisions.')}finally{setBusy('')}}
  async function refresh(){if(!businessId)return;const j=await request(businessId,'workspace');setWorkspace(j);if(j.profile)setProfile((p:any)=>({...p,...j.profile,business_context:{...p.business_context,...(j.profile.business_context||{})}}))}
  function toggleAudience(a:string){setProfile((p:any)=>({...p,audience_tags:(p.audience_tags||[]).includes(a)?p.audience_tags.filter((x:string)=>x!==a):[...(p.audience_tags||[]),a]}))}
  async function saveContext(){setBusy('save');setError('');try{await request(businessId,'profile',{profile});await refresh();setStep(1)}catch(e:any){setError(e.message)}finally{setBusy('')}}
  function readFile(file:File){return new Promise<string>((resolve,reject)=>{const r=new FileReader();r.onload=()=>resolve(String(r.result||''));r.onerror=reject;r.readAsDataURL(file)})}
  async function previewImport(){if(!importText.trim()&&!importFiles.length){setStep(2);return}setBusy('preview');setError('');try{const images=await Promise.all(importFiles.slice(0,6).map(readFile));const j=await request(businessId,'preview_import',{source_type:images.length?'ocr':'text',text:importText,image_data_urls:images,image_data_url:images[0]||''});setPreview(j)}catch(e:any){setError(e.message)}finally{setBusy('')}}
  async function commitImport(){if(!preview?.rows?.length){setStep(2);return}setBusy('commit');try{await request(businessId,'commit_import',{source_type:importFiles.length?'ocr':'text',label:importFiles.length?`${importFiles.length} image(s) historique`:'Historique texte',rows:preview.rows,metadata:{warnings:preview.warnings||[],confidence:preview.confidence}});setPreview(null);setImportText('');setImportFiles([]);await refresh();setStep(2)}catch(e:any){setError(e.message)}finally{setBusy('')}}
  async function addEvent(){if(!event.title.trim()||!event.starts_at)return;setBusy('event');try{await request(businessId,'event',{event});setEvent({event_type:'promotion',title:'',starts_at:'',ends_at:'',expected_direction:'up',expected_impact_pct:'',notes:''});await refresh()}catch(e:any){setError(e.message)}finally{setBusy('')}}
  async function scanExternal(){setBusy('scan');setScanMessage('');setError('');try{await request(businessId,'profile',{profile});const j=await request(businessId,'external_scan');setScanMessage(`${j.articles_checked||0} sources récentes examinées · ${j.factors_saved||0} facteur(s) retenu(s).`);await refresh()}catch(e:any){setError(String(e.message).includes('LOCATION_REQUIRED')?'Renseignez une localisation précise avant la recherche.':e.message)}finally{setBusy('')}}
  async function runForecast(){setBusy('run');setError('');try{await request(businessId,'profile',{profile:{...profile,default_horizon_days:horizon}});const j=await request(businessId,'run',{horizon_days:horizon});await refresh();setStep(4);if(!j.results?.length)setError('Pas encore assez d’historique exploitable. Importez des ventes ou utilisez Qatalink quelques jours.')}catch(e:any){setError(e.message)}finally{setBusy('')}}

  if(!open)return null;
  const results=workspace?.results||[],recs=workspace?.recommendations||[],externals=workspace?.external_factors||[],imports=workspace?.imports||[],events=workspace?.events||[];const totalRevenue=results.reduce((s:number,r:any)=>s+Number(r.forecast_revenue_minor||0),0);const risky=recs.filter((r:any)=>['critical','high'].includes(r.risk_level));
  const nextLabel=step===3?'Calculer mes prévisions · 15 crédits':'Continuer';

  return <div className="qfw-backdrop" onMouseDown={e=>{if(e.target===e.currentTarget)setOpen(false)}}><section className="qfw-modal">
    <header className="qfw-head"><div><span>QATALINK BUSINESS <b>BETA</b></span><h2>Prévisions guidées</h2><p>Renseignez votre contexte étape par étape. Qatalink combine historique, saisonnalité, météo, actions commerciales et stock pour estimer la demande, le CA et les besoins d’approvisionnement.</p></div><button onClick={()=>setOpen(false)}><X/></button></header>
    {locked?<div className="qfw-lock"><Sparkles/><h3>Réservé à Business</h3><p>Vous pouvez découvrir le module, mais les calculs, recherches externes et recommandations d’approvisionnement nécessitent l’abonnement Business.</p><a href="/#pricing">Voir Business</a></div>:busy==='load'?<div className="qfw-loading">Chargement…</div>:<>
      <div className="qfw-progress">{STEPS.map((s,i)=><div key={s} className={i===step?'active':i<step?'done':''}><span>{i<step?<Check/>:i+1}</span><small>{s}</small></div>)}</div>
      <div className="qfw-body">
        {step===0&&<section className="qfw-step"><div className="qfw-title"><CloudRain/><div><h3>1. Votre contexte local</h3><p>Ces informations servent à chercher uniquement les facteurs externes réellement pertinents pour votre clientèle.</p></div></div><div className="qfw-grid"><label>Localisation principale<input value={profile.location_label||''} onChange={e=>setProfile({...profile,location_label:e.target.value})} placeholder="Marcory Zone 4, Abidjan"/></label><label>Secteur / activité<input value={profile.business_context?.sector||''} onChange={e=>setProfile({...profile,business_context:{...(profile.business_context||{}),sector:e.target.value}})} placeholder="Restaurant, boutique, lounge…"/></label><label>Rayon de clientèle (km)<input type="number" min="1" value={profile.service_radius_km||5} onChange={e=>setProfile({...profile,service_radius_km:e.target.value})}/></label><label>Sensibilité à la météo<select value={profile.weather_sensitivity||'medium'} onChange={e=>setProfile({...profile,weather_sensitivity:e.target.value})}><option value="low">Faible</option><option value="medium">Moyenne</option><option value="high">Forte</option></select></label></div><div className="qfw-audiences"><b>Clientèle habituelle / ciblée</b><div>{AUDIENCES.map(a=><button key={a} className={(profile.audience_tags||[]).includes(a)?'active':''} onClick={()=>toggleAudience(a)}>{a}</button>)}</div></div><label className="qfw-wide">Habitudes et contexte à connaître<textarea value={profile.locality_notes||''} onChange={e=>setProfile({...profile,locality_notes:e.target.value})} placeholder="Ex : clientèle de bureaux le midi, pic vendredi soir, dépend des événements de Zone 4, jours de paie importants…"/></label><label className="qfw-check"><input type="checkbox" checked={!!profile.business_context?.delivery_heavy} onChange={e=>setProfile({...profile,business_context:{...(profile.business_context||{}),delivery_heavy:e.target.checked}})}/>Activité fortement orientée livraison</label></section>}
        {step===1&&<section className="qfw-step"><div className="qfw-title"><Database/><div><h3>2. Votre historique de ventes</h3><p>Qatalink utilise déjà les ventes enregistrées dans l’application. Vous pouvez les compléter par du texte brut ou des photos/captures.</p></div></div><div className="qfw-history-summary"><b>{imports.length} import(s) externe(s)</b><span>+ historique Qatalink automatique</span></div><textarea className="qfw-textarea" value={importText} onChange={e=>setImportText(e.target.value)} placeholder="Collez ici un historique de ventes, même non structuré…"/><label className="qfw-file"><Upload/>Ajouter des photos / captures d’historique<input type="file" accept="image/*" multiple onChange={e=>setImportFiles(Array.from(e.target.files||[]).slice(0,6))}/></label>{importFiles.length>0&&<small>{importFiles.length} image(s) sélectionnée(s)</small>}{preview?.rows?.length>0&&<div className="qfw-preview"><b>{preview.rows.length} lignes reconnues</b>{preview.rows.slice(0,8).map((r:any,i:number)=><div key={i}><span>{r.sold_on||r.date||'—'}</span><strong>{r.item_name||r.product||'Article'}</strong><em>{r.quantity||0}</em></div>)}<button onClick={commitImport} disabled={busy==='commit'}>{busy==='commit'?'Import…':'Valider cet historique et continuer'}</button></div>}</section>}
        {step===2&&<section className="qfw-step"><div className="qfw-title"><CalendarDays/><div><h3>3. Promotions, événements et actualité</h3><p>Ajoutez ce que votre entreprise a fait récemment ou va faire. Qatalink peut ensuite chercher les facteurs externes locaux qui pourraient influencer la demande.</p></div></div><div className="qfw-event"><input placeholder="Ex : promo -10 %, soirée DJ, nouveau produit…" value={event.title} onChange={e=>setEvent({...event,title:e.target.value})}/><select value={event.event_type} onChange={e=>setEvent({...event,event_type:e.target.value})}><option value="promotion">Promotion</option><option value="campaign">Campagne</option><option value="price_change">Changement de prix</option><option value="launch">Lancement</option><option value="closure">Fermeture</option><option value="stockout">Rupture</option><option value="event">Événement</option></select><input type="date" value={event.starts_at} onChange={e=>setEvent({...event,starts_at:e.target.value})}/><input type="date" value={event.ends_at} onChange={e=>setEvent({...event,ends_at:e.target.value})}/><button onClick={addEvent} disabled={!event.title||!event.starts_at||busy==='event'}>Ajouter</button></div>{events.length>0&&<div className="qfw-list">{events.slice(0,6).map((x:any)=><div key={x.id}><b>{x.title}</b><small>{x.starts_at?.slice?.(0,10)} {x.ends_at?`→ ${x.ends_at.slice(0,10)}`:''}</small></div>)}</div>}<button className="qfw-scan" onClick={scanExternal} disabled={busy==='scan'}><Globe2/>{busy==='scan'?'Recherche en cours…':'Rechercher les facteurs externes pertinents'}</button>{scanMessage&&<p className="qfw-note">{scanMessage}</p>}{externals.length>0&&<div className="qfw-list">{externals.slice(0,5).map((x:any)=><div key={x.id}><b>{x.title}</b><small>{x.rationale}</small></div>)}</div>}</section>}
        {step===3&&<section className="qfw-step"><div className="qfw-title"><PackageCheck/><div><h3>4. Préférences de calcul</h3><p>Choisissez l’horizon et votre marge de sécurité. Le calcul final consomme 15 crédits IA.</p></div></div><div className="qfw-choice"><button className={horizon===7?'active':''} onClick={()=>setHorizon(7)}><b>7 jours</b><small>Opérationnel court terme</small></button><button className={horizon===14?'active':''} onClick={()=>setHorizon(14)}><b>14 jours</b><small>Approvisionnement</small></button><button className={horizon===30?'active':''} onClick={()=>setHorizon(30)}><b>30 jours</b><small>Vision mensuelle</small></button></div><label className="qfw-slider">Stock de sécurité : <b>{profile.safety_stock_days||2} jour(s)</b><input type="range" min="0" max="14" step="1" value={profile.safety_stock_days||2} onChange={e=>setProfile({...profile,safety_stock_days:Number(e.target.value)})}/></label><div className="qfw-info"><AlertTriangle/><p><b>Quand Qatalink peut vous dire quoi acheter ?</b><br/>Lorsque vos plats/produits sont reliés à leurs intrants dans la section Stock (ex. 1 burger = 1 pain + 1 steak + 30 ml de sauce). Qatalink transforme alors la demande prévue en besoin de chaque intrant, retire le stock disponible et ajoute votre stock de sécurité.</p></div></section>}
        {step===4&&<section className="qfw-step"><div className="qfw-title"><BarChart3/><div><h3>5. Vos estimations</h3><p>Demande par offre, chiffre d’affaires estimé et quantité de chaque intrant à prévoir.</p></div></div><div className="qfw-kpis"><article><span>CA estimé</span><b>{money(totalRevenue)}</b><small>{workspace?.run?.horizon_days||horizon} prochains jours</small></article><article><span>Risques de rupture</span><b>{risky.length}</b><small>{recs.length} intrant(s) analysé(s)</small></article><article><span>Facteurs externes</span><b>{externals.length}</b><small>météo + contexte + actualité</small></article></div><div className="qfw-results"><section><h4>Demande prévue par offre</h4>{results.length?results.slice(0,30).map((r:any)=><div key={r.id||r.item_id||r.item_name}><div><b>{r.item_name}</b><small>{r.explanation}</small></div><strong>{num(r.forecast_quantity)} u.</strong><span>{Math.round(Number(r.confidence||0)*100)}%</span></div>):<p>Aucune prévision calculée.</p>}</section><section><h4>Stock / intrants à prévoir</h4>{recs.length?recs.slice(0,30).map((r:any)=><div key={r.id||r.stock_item_id} className={`risk-${r.risk_level}`}><div><b>{r.stock_item_name}</b><small>Besoin prévu {num(r.projected_need)} · stock actuel {num(r.current_quantity)}</small></div><strong>{Number(r.recommended_quantity)>0?`Acheter ${num(r.recommended_quantity)}`:'Stock suffisant'}</strong><span>{Number(r.coverage_days)>100?'—':`${num(r.coverage_days)} j`}</span></div>):<p>Pour obtenir les quantités d’intrants, reliez d’abord les articles du menu à leurs composants dans Stock.</p>}</section></div></section>}
        {error&&<div className="qfw-error">{error}</div>}
      </div>
      <footer className="qfw-actions">{step>0&&<button className="secondary" onClick={()=>setStep(s=>Math.max(0,s-1))}><ArrowLeft/>Retour</button>}<div/><>{step===0?<button className="primary" onClick={saveContext} disabled={busy==='save'}>{busy==='save'?'Enregistrement…':nextLabel}<ArrowRight/></button>:step===1&&!preview?<button className="primary" onClick={previewImport} disabled={busy==='preview'}>{busy==='preview'?'Analyse…':importText.trim()||importFiles.length?'Analyser puis continuer':'Continuer sans import'}<ArrowRight/></button>:step===2?<button className="primary" onClick={()=>setStep(3)}>Continuer<ArrowRight/></button>:step===3?<button className="primary" onClick={runForecast} disabled={busy==='run'}><Sparkles/>{busy==='run'?'Calcul en cours…':nextLabel}</button>:<button className="primary" onClick={()=>setStep(0)}>Nouveau scénario</button>}</></footer>
    </>}
  </section></div>;
}
