'use client';

import {useEffect,useMemo,useRef,useState} from 'react';
import {Copy,Download,ExternalLink,Facebook,Globe2,ImagePlus,Instagram,Link2,MapPin,MessageCircle,Music2,Palette,Plus,QrCode,Save,Sparkles,Trash2,Upload,X,Youtube} from 'lucide-react';
import {createSupabaseBrowserClient} from '@/lib/supabase';

type Business={id:string;name:string;slug:string;description:string|null;profile_headline:string|null;profile_bio:string|null;linkhub_enabled:boolean;whatsapp_number:string|null;logo_url:string|null;cover_url:string|null};
type Catalog={id:string;title:string;public_slug:string;hub_public_slug:string};
type ButtonStyle='solid'|'gradient'|'glossy'|'metallic';
type LinkRow={id:string;business_id:string;kind:string;label:string;url:string;sort_order:number;is_visible:boolean;icon_url:string|null;button_style:ButtonStyle|null;button_color:string|null;button_color_2:string|null;button_text_color:string|null};
type MediaItem={id:string;name:string;catalog_id:string;image_url?:string|null};
type HubSettings={catalog_id:string;logo_url:string|null;cover_url:string|null;button_style:ButtonStyle;button_color:string;button_color_2:string;button_text_color:string;button_radius:string};
type BrandDefaults={style:ButtonStyle;a:string;b:string;text:string;iconUrl?:string};

const defaultHub:HubSettings={catalog_id:'',logo_url:null,cover_url:null,button_style:'solid',button_color:'#C7192F',button_color_2:'#7A0E1D',button_text_color:'#FFFFFF',button_radius:'18px'};
const kinds=[['instagram','Instagram'],['facebook','Facebook'],['x','X / Twitter'],['threads','Threads'],['google_reviews','Avis Google'],['tiktok','TikTok'],['youtube','YouTube'],['website','Site internet'],['maps','Google Maps'],['whatsapp','WhatsApp'],['wave','Wave'],['orange_money','Orange Money'],['custom','Autre lien']] as const;

function platformDefaults(kind:string):BrandDefaults|null{
  if(kind==='instagram')return{style:'gradient',a:'#833AB4',b:'#FD1D1D',text:'#FFFFFF',iconUrl:'https://cdn.simpleicons.org/instagram/ffffff'};
  if(kind==='facebook')return{style:'solid',a:'#1877F2',b:'#1877F2',text:'#FFFFFF',iconUrl:'https://cdn.simpleicons.org/facebook/ffffff'};
  if(kind==='x'||kind==='twitter')return{style:'solid',a:'#000000',b:'#000000',text:'#FFFFFF',iconUrl:'https://cdn.simpleicons.org/x/ffffff'};
  if(kind==='threads')return{style:'solid',a:'#000000',b:'#000000',text:'#FFFFFF',iconUrl:'https://cdn.simpleicons.org/threads/ffffff'};
  if(kind==='google_reviews')return{style:'solid',a:'#FFFFFF',b:'#FFFFFF',text:'#202124',iconUrl:'https://cdn.simpleicons.org/google/4285F4'};
  if(kind==='whatsapp')return{style:'solid',a:'#25D366',b:'#25D366',text:'#FFFFFF',iconUrl:'https://cdn.simpleicons.org/whatsapp/ffffff'};
  if(kind==='youtube')return{style:'solid',a:'#FF0000',b:'#FF0000',text:'#FFFFFF',iconUrl:'https://cdn.simpleicons.org/youtube/ffffff'};
  if(kind==='tiktok')return{style:'solid',a:'#000000',b:'#000000',text:'#FFFFFF',iconUrl:'https://cdn.simpleicons.org/tiktok/ffffff'};
  if(kind==='wave')return{style:'solid',a:'#54C8E8',b:'#54C8E8',text:'#071820'};
  if(kind==='orange_money')return{style:'solid',a:'#FF7900',b:'#FF7900',text:'#111111'};
  if(kind==='maps')return{style:'solid',a:'#4285F4',b:'#4285F4',text:'#FFFFFF'};
  return null;
}
function SocialIcon({kind,size=17}:{kind:string;size?:number}){if(kind==='instagram')return <Instagram size={size}/>;if(kind==='facebook')return <Facebook size={size}/>;if(kind==='tiktok')return <Music2 size={size}/>;if(kind==='youtube')return <Youtube size={size}/>;if(kind==='website')return <Globe2 size={size}/>;if(kind==='maps')return <MapPin size={size}/>;if(kind==='whatsapp')return <MessageCircle size={size}/>;return <Link2 size={size}/>}
function ButtonIcon({row,size=18}:{row:Partial<LinkRow>;size?:number}){const src=row.icon_url||platformDefaults(String(row.kind||''))?.iconUrl||'';if(src)return <img src={src} alt="" style={{width:size,height:size,objectFit:'contain'}}/>;return <SocialIcon kind={String(row.kind||'custom')} size={size}/>}
function buttonBackground(style:ButtonStyle,a:string,b:string){if(style==='gradient')return`linear-gradient(135deg,${a},${b})`;if(style==='glossy')return`linear-gradient(180deg,rgba(255,255,255,.42),rgba(255,255,255,.08) 40%,rgba(0,0,0,.15)),linear-gradient(135deg,${a},${b})`;if(style==='metallic')return`linear-gradient(125deg,${a} 0%,${b} 20%,rgba(255,255,255,.78) 38%,${a} 54%,rgba(20,20,22,.42) 72%,${b} 88%,${a} 100%)`;return a}

export function DashboardVitrineMedia(){
  const supabase=useMemo(()=>createSupabaseBrowserClient(),[]);
  const [open,setOpen]=useState(false);const [tab,setTab]=useState<'links'|'design'|'media'>('links');const [session,setSession]=useState<any>(null);const [businesses,setBusinesses]=useState<Business[]>([]);const [businessId,setBusinessId]=useState('');const [catalogs,setCatalogs]=useState<Catalog[]>([]);const [hubCatalogId,setHubCatalogId]=useState('');const [hub,setHub]=useState<HubSettings>(defaultHub);const [links,setLinks]=useState<LinkRow[]>([]);const [items,setItems]=useState<MediaItem[]>([]);const [credits,setCredits]=useState(0);const [plan,setPlan]=useState('');const [busy,setBusy]=useState('');const [notice,setNotice]=useState('');const [copied,setCopied]=useState(false);const [newLink,setNewLink]=useState({kind:'instagram',label:'Instagram',url:''});const pollTimer=useRef<ReturnType<typeof setTimeout>|null>(null);
  const selected=businesses.find(b=>b.id===businessId)||null;const selectedCatalog=catalogs.find(c=>c.id===hubCatalogId)||null;const missing=items.filter(i=>!i.image_url);const canHub=plan==='interactive'||plan==='linkhub'||plan==='trial';const hubUrl=selectedCatalog?`https://qatalink.com/h/${selectedCatalog.hub_public_slug}`:'';const hubQr=selectedCatalog?`/api/hub-qr/${selectedCatalog.hub_public_slug}`:'';

  useEffect(()=>{(async()=>{const {data:{session:s}}=await supabase.auth.getSession();if(!s)return;setSession(s);const {data:bs}=await supabase.from('businesses').select('id,name,slug,description,profile_headline,profile_bio,linkhub_enabled,whatsapp_number,logo_url,cover_url').order('created_at',{ascending:true});const list=(bs||[]) as Business[];setBusinesses(list);if(list[0])setBusinessId(list[0].id)})();return()=>{if(pollTimer.current)clearTimeout(pollTimer.current)}},[]);
  useEffect(()=>{if(businessId)void loadBusiness(businessId)},[businessId]);
  useEffect(()=>{if(hubCatalogId)void loadHub(hubCatalogId)},[hubCatalogId]);

  async function loadBusiness(id:string){setBusy('load');setNotice('');const [{data:ls},{data:cs},{data:w},{data:ss}]=await Promise.all([supabase.from('business_links').select('id,business_id,kind,label,url,sort_order,is_visible,icon_url,button_style,button_color,button_color_2,button_text_color').eq('business_id',id).order('sort_order'),supabase.from('catalogs').select('id,title,public_slug,hub_public_slug').eq('business_id',id).eq('is_active',true).order('created_at'),supabase.from('credit_wallets').select('balance').eq('business_id',id).maybeSingle(),supabase.from('subscriptions').select('plan_code,status,current_period_end').eq('business_id',id).in('status',['active','trialing']).order('created_at',{ascending:false}).limit(1)]);setLinks((ls||[]) as LinkRow[]);setCredits(Number(w?.balance||0));setPlan(String(ss?.[0]?.plan_code||''));const catList=(cs||[]) as Catalog[];setCatalogs(catList);const chosen=catList.some(c=>c.id===hubCatalogId)?hubCatalogId:catList[0]?.id||'';setHubCatalogId(chosen);const catalogIds=catList.map(c=>c.id);if(!catalogIds.length){setItems([]);setBusy('');return}const {data:rows}=await supabase.from('items').select('id,name,catalog_id').in('catalog_id',catalogIds).eq('is_available',true).order('sort_order');const base=(rows||[]) as MediaItem[];const imageMap:Record<string,string>={};if(base.length){const {data:imgs}=await supabase.from('item_images').select('item_id,image_url,is_primary,created_at').in('item_id',base.map(i=>i.id)).order('created_at',{ascending:false});for(const img of imgs||[])if(!imageMap[img.item_id])imageMap[img.item_id]=img.image_url}setItems(base.map(i=>({...i,image_url:imageMap[i.id]||null})));setBusy('')}
  async function loadHub(id:string){const {data}=await supabase.from('catalog_hub_settings').select('catalog_id,logo_url,cover_url,button_style,button_color,button_color_2,button_text_color,button_radius').eq('catalog_id',id).maybeSingle();setHub({...defaultHub,...(data||{}),catalog_id:id} as HubSettings)}
  function patchBusiness(patch:Partial<Business>){setBusinesses(x=>x.map(b=>b.id===businessId?{...b,...patch}:b))}
  function patchLink(index:number,patch:Partial<LinkRow>){setLinks(x=>x.map((v,i)=>i===index?{...v,...patch}:v))}
  function requireHub(){if(canHub)return true;setNotice('La page centrale est disponible avec Pro et Business.');return false}
  async function saveProfile(){if(!selected||!requireHub())return;setBusy('profile');const {error}=await supabase.from('businesses').update({profile_headline:selected.profile_headline,profile_bio:selected.profile_bio,linkhub_enabled:true,published:true,updated_at:new Date().toISOString()}).eq('id',selected.id);setBusy('');setNotice(error?'Impossible d’enregistrer pour le moment. Réessayez.':'Page centrale enregistrée et publiée.')}
  async function addLink(){if(!selected||!requireHub())return;if(!newLink.url.trim())return setNotice('Ajoutez une URL complète pour ce lien.');setBusy('link');const {error}=await supabase.from('business_links').insert({business_id:selected.id,kind:newLink.kind,label:newLink.label||kinds.find(k=>k[0]===newLink.kind)?.[1]||'Lien',url:newLink.url.trim(),sort_order:links.length+10,is_visible:true});if(!error){setNewLink({kind:'instagram',label:'Instagram',url:''});await loadBusiness(selected.id)}setBusy('');setNotice(error?'Impossible d’ajouter ce lien. Réessayez.':'Lien ajouté. Vous pouvez maintenant personnaliser son logo et ses couleurs.')}
  async function saveLink(row:LinkRow){if(!requireHub())return;setBusy(`link-${row.id}`);const {error}=await supabase.from('business_links').update({kind:row.kind,label:row.label,url:row.url,sort_order:row.sort_order,is_visible:row.is_visible,icon_url:row.icon_url||null,button_style:row.button_style||null,button_color:row.button_color||null,button_color_2:row.button_color_2||null,button_text_color:row.button_text_color||null,updated_at:new Date().toISOString()}).eq('id',row.id);setBusy('');setNotice(error?'Impossible d’enregistrer ce lien. Réessayez.':'Bouton enregistré avec son design propre.')}
  async function deleteLink(id:string){if(!requireHub()||!confirm('Supprimer ce lien de la page centrale ?'))return;await supabase.from('business_links').delete().eq('id',id);if(selected)await loadBusiness(selected.id)}
  async function uploadLinkIcon(row:LinkRow,index:number,file:File){if(!session||!requireHub())return;setBusy(`icon-${row.id}`);const safe=file.name.replace(/[^a-zA-Z0-9._-]+/g,'-');const path=`${session.user.id}/${hubCatalogId||'hub'}/hub-links/${row.id}/${Date.now()}-${safe}`;const up=await supabase.storage.from('catalog-assets').upload(path,file,{contentType:file.type||'image/png'});if(up.error){setBusy('');setNotice(up.error.message);return}const {data:url}=supabase.storage.from('catalog-assets').getPublicUrl(path);const iconUrl=url.publicUrl;patchLink(index,{icon_url:iconUrl});const {error}=await supabase.from('business_links').update({icon_url:iconUrl,updated_at:new Date().toISOString()}).eq('id',row.id);setBusy('');setNotice(error?error.message:'Logo du bouton enregistré.')}
  async function removeLinkIcon(row:LinkRow,index:number){patchLink(index,{icon_url:null});const {error}=await supabase.from('business_links').update({icon_url:null,updated_at:new Date().toISOString()}).eq('id',row.id);setNotice(error?error.message:'Logo personnalisé retiré : le logo par défaut de la plateforme sera utilisé.')}
  async function saveHub(){if(!selectedCatalog||!requireHub())return;setBusy('hub');const payload={...hub,catalog_id:selectedCatalog.id,updated_at:new Date().toISOString()};const {error}=await supabase.from('catalog_hub_settings').upsert(payload,{onConflict:'catalog_id'});setBusy('');setNotice(error?error.message:'Design général enregistré. Les personnalisations propres à chaque bouton restent prioritaires.')}
  async function uploadHubAsset(file:File,kind:'logo'|'cover'){if(!session||!selectedCatalog||!requireHub())return;setBusy(`hub-${kind}`);const safe=file.name.replace(/[^a-zA-Z0-9._-]+/g,'-');const path=`${session.user.id}/${selectedCatalog.id}/hub/${kind}-${Date.now()}-${safe}`;const up=await supabase.storage.from('catalog-assets').upload(path,file,{contentType:file.type||'image/png'});if(up.error){setBusy('');setNotice(up.error.message);return}const {data:url}=supabase.storage.from('catalog-assets').getPublicUrl(path);const next={...hub,catalog_id:selectedCatalog.id,[kind==='logo'?'logo_url':'cover_url']:url.publicUrl};setHub(next);const {error}=await supabase.from('catalog_hub_settings').upsert({...next,updated_at:new Date().toISOString()},{onConflict:'catalog_id'});setBusy('');setNotice(error?error.message:kind==='logo'?'Logo de la page centrale enregistré.':'Bannière de la page centrale enregistrée.')}
  async function copyHub(){if(!hubUrl)return;await navigator.clipboard.writeText(hubUrl);setCopied(true);setTimeout(()=>setCopied(false),1400)}

  async function generateMissing(){if(!session||!selected||!missing.length)return;const need=missing.length*5;if(credits<need)return setNotice(`Crédits insuffisants : ${need} nécessaires, ${credits} disponibles.`);setBusy('generate');setNotice(`Création de ${missing.length} illustration(s)…`);const r=await fetch('/api/images/generate',{method:'POST',headers:{'Content-Type':'application/json',Authorization:`Bearer ${session.access_token}`},body:JSON.stringify({item_ids:missing.map(i=>i.id)})});const d=await r.json().catch(()=>({}));if(!r.ok){setBusy('');setNotice('Impossible de lancer les illustrations. Réessayez.');return}const jobs=(d.jobs||[]).filter((j:any)=>j.job_id&&!j.error).map((j:any)=>j.job_id);setCredits(Number(d.balance??credits));if(!jobs.length){setBusy('');setNotice('Aucune illustration n’a pu être lancée. Réessayez.');return}setNotice(`${jobs.length} illustration(s) en cours de création.`);pollJobs(jobs)}
  async function pollJobs(jobIds:string[]){if(!session||!selected)return;const r=await fetch('/api/images/status',{method:'POST',headers:{'Content-Type':'application/json',Authorization:`Bearer ${session.access_token}`},body:JSON.stringify({job_ids:jobIds})});const d=await r.json().catch(()=>({}));const rows=Array.isArray(d.results)?d.results:[];const pending=rows.filter((x:any)=>x.status==='processing'||x.status==='pending').map((x:any)=>x.job_id);const done=rows.filter((x:any)=>x.status==='completed').length;const failed=rows.filter((x:any)=>x.status==='failed').length;if(pending.length){setNotice(`${done} terminée(s) · ${pending.length} en cours${failed?` · ${failed} à relancer`:''}`);pollTimer.current=setTimeout(()=>pollJobs(pending),3000);return}setBusy('');setNotice(`${done} illustration(s) terminée(s)${failed?` · ${failed} à relancer`:''}.`);await loadBusiness(selected.id)}

  if(!businesses.length)return null;
  const globalPreview={background:buttonBackground(hub.button_style,hub.button_color,hub.button_color_2),color:hub.button_text_color,borderRadius:hub.button_radius};
  const effective=(l:LinkRow)=>{const d=platformDefaults(l.kind);const style=l.button_style||d?.style||hub.button_style;const a=l.button_color||d?.a||hub.button_color;const b=l.button_color_2||d?.b||hub.button_color_2;const text=l.button_text_color||d?.text||hub.button_text_color;return{style,a,b,text,css:{background:buttonBackground(style,a,b),color:text,borderRadius:hub.button_radius} as React.CSSProperties}};

  return <><button className="vitrine-media-trigger" onClick={()=>setOpen(true)}><Link2 size={17}/><span>Page centrale & médias</span></button>{open&&<div className="vm-backdrop"><section className="vm-panel"><header><div><span className="eyebrow">QATALINK</span><h2>Page centrale & médias</h2></div><button onClick={()=>setOpen(false)}><X/></button></header><div className="vm-business"><label>Entreprise</label><select className="input" value={businessId} onChange={e=>setBusinessId(e.target.value)}>{businesses.map(b=><option key={b.id} value={b.id}>{b.name}</option>)}</select><span className="tag">{plan==='linkhub'?'Business':plan==='trial'?'Essai 7 jours':plan==='interactive'?'Pro':plan==='static'?'Starter':'Sans formule'}</span></div><div className="vm-tabs"><button className={tab==='links'?'active':''} onClick={()=>setTab('links')}><Link2 size={15}/>Contenu & liens</button><button className={tab==='design'?'active':''} onClick={()=>setTab('design')}><Palette size={15}/>Design & QR</button><button className={tab==='media'?'active':''} onClick={()=>setTab('media')}><ImagePlus size={15}/>Illustrations</button></div>{notice&&<div className="vm-notice">{notice}</div>}

  {tab==='links'&&<div className="vm-body">{!canHub&&<div className="vm-warning">La page centrale est disponible à partir de Pro. L’essai de 7 jours permet de la tester.</div>}<section className="vm-card"><div className="vm-card-head"><div><h3>Profil de la page centrale</h3><p>Présentez votre activité puis laissez le client ouvrir le menu/catalogue et vos liens utiles.</p></div></div><div className="field"><label>Titre affiché</label><input className="input" value={selected?.profile_headline||''} onChange={e=>patchBusiness({profile_headline:e.target.value})} placeholder={selected?.name||'Nom de votre entreprise'} disabled={!canHub}/></div><div className="field"><label>Bio courte</label><textarea className="input" rows={3} value={selected?.profile_bio||''} onChange={e=>patchBusiness({profile_bio:e.target.value})} placeholder="Présentez votre activité en quelques mots…" disabled={!canHub}/></div><button className="btn btn-primary" onClick={saveProfile} disabled={busy==='profile'||!canHub}><Save size={15}/>Enregistrer le profil</button></section>

  <section className="vm-card"><h3>Ajouter un bouton</h3><p>Chaque bouton peut ensuite avoir son propre logo, sa propre couleur de fond, sa couleur de texte et même son propre rendu gradient, glossy ou métallique.</p><div className="vm-add-link"><select className="input" value={newLink.kind} onChange={e=>{const k=e.target.value;setNewLink({...newLink,kind:k,label:kinds.find(x=>x[0]===k)?.[1]||'Lien'})}} disabled={!canHub}>{kinds.map(k=><option key={k[0]} value={k[0]}>{k[1]}</option>)}</select><input className="input" value={newLink.label} onChange={e=>setNewLink({...newLink,label:e.target.value})} placeholder="Libellé" disabled={!canHub}/><input className="input" value={newLink.url} onChange={e=>setNewLink({...newLink,url:e.target.value})} placeholder="https://…" disabled={!canHub}/><button className="btn btn-primary" onClick={addLink} disabled={busy==='link'||!canHub}><Plus size={15}/>Ajouter</button></div></section>

  <section className="vm-card"><h3>Boutons de la page centrale</h3><p>Instagram, Facebook, X, Threads, Avis Google, WhatsApp et les autres plateformes utilisent leur identité visuelle par défaut. Vous pouvez la remplacer bouton par bouton.</p><div className="vm-links-list">{links.length?links.map((l,index)=>{const e=effective(l);const d=platformDefaults(l.kind);return <div className={`vm-link-row platform-${l.kind}`} key={l.id} style={{display:'grid',gap:12}}><div style={{display:'flex',gap:12,alignItems:'center'}}><div className="vm-platform-icon" style={{background:e.a,color:e.text}}><ButtonIcon row={l}/></div><div className="vm-link-fields"><select className="input" value={l.kind} onChange={ev=>patchLink(index,{kind:ev.target.value})} disabled={!canHub}>{kinds.map(k=><option key={k[0]} value={k[0]}>{k[1]}</option>)}</select><input className="input" value={l.label} onChange={ev=>patchLink(index,{label:ev.target.value})} disabled={!canHub}/><input className="input" value={l.url} onChange={ev=>patchLink(index,{url:ev.target.value})} disabled={!canHub}/></div></div>
  <div style={{display:'grid',gridTemplateColumns:'repeat(auto-fit,minmax(145px,1fr))',gap:10}}><label>Rendu<select className="input" value={l.button_style||d?.style||''} onChange={ev=>patchLink(index,{button_style:(ev.target.value||null) as ButtonStyle|null})}><option value="">Défaut général</option><option value="solid">Couleur unie</option><option value="gradient">Gradient</option><option value="glossy">Glossy</option><option value="metallic">Métallique</option></select></label><label>Fond<input className="input vm-color" type="color" value={e.a} onChange={ev=>patchLink(index,{button_color:ev.target.value})}/></label><label>Fond 2<input className="input vm-color" type="color" value={e.b} onChange={ev=>patchLink(index,{button_color_2:ev.target.value})}/></label><label>Texte<input className="input vm-color" type="color" value={e.text} onChange={ev=>patchLink(index,{button_text_color:ev.target.value})}/></label></div>
  <div style={{display:'flex',gap:8,alignItems:'center',flexWrap:'wrap'}}><label className="btn btn-ghost"><Upload size={14}/>{busy===`icon-${l.id}`?'Import…':l.icon_url?'Changer le logo':'Ajouter un logo'}<input type="file" accept="image/*" hidden onChange={ev=>{const f=ev.target.files?.[0];if(f)void uploadLinkIcon(l,index,f);ev.currentTarget.value=''}}/></label>{l.icon_url&&<button className="btn btn-ghost" onClick={()=>removeLinkIcon(l,index)}>Logo par défaut</button>}<button className="btn btn-ghost" onClick={()=>patchLink(index,{button_style:null,button_color:null,button_color_2:null,button_text_color:null})}>Couleurs par défaut</button><label className="vm-visible"><input type="checkbox" checked={l.is_visible} onChange={ev=>patchLink(index,{is_visible:ev.target.checked})} disabled={!canHub}/>Visible</label></div>
  <div className="vm-hub-preview"><button style={e.css}><ButtonIcon row={l}/><span>{l.label||'Aperçu du bouton'}</span><ExternalLink size={14}/></button></div><div className="vm-row-actions"><button className="btn btn-primary" onClick={()=>saveLink(l)} disabled={!canHub||busy===`link-${l.id}`}><Save size={13}/>Enregistrer ce bouton</button><button className="btn btn-ghost" onClick={()=>deleteLink(l.id)} disabled={!canHub}><Trash2 size={13}/>Supprimer</button></div></div>}):<p>Aucun lien ajouté pour cette entreprise.</p>}</div></section></div>}

  {tab==='design'&&<div className="vm-body">{!canHub&&<div className="vm-warning">Le QR de page centrale et son design sont disponibles à partir de Pro.</div>}<section className="vm-card"><h3>Page centrale de quel catalogue ?</h3><select className="input" value={hubCatalogId} onChange={e=>setHubCatalogId(e.target.value)} disabled={!canHub}>{catalogs.map(c=><option key={c.id} value={c.id}>{c.title}</option>)}</select>{selectedCatalog&&<div className="vm-hub-share"><img src={hubQr} alt="QR page centrale"/><div><span>Lien permanent de la page centrale</span><strong>{hubUrl}</strong><small>Ce lien et ce QR restent identiques lorsque vous modifiez le design, les boutons, les liens ou le contenu.</small><div className="vm-hub-actions"><button className="btn btn-ghost" onClick={copyHub}><Copy size={14}/>{copied?'Copié':'Copier le lien'}</button><a className="btn btn-ghost" href={`${hubQr}?download=1`}><Download size={14}/>Télécharger le QR</a><a className="btn btn-ghost" href={hubUrl} target="_blank"><ExternalLink size={14}/>Voir</a></div></div></div>}</section>

  <section className="vm-card"><h3>Logo et bannière</h3><p>Par défaut, la page centrale reprend automatiquement le logo et la bannière du catalogue/entreprise. Vous pouvez les remplacer uniquement pour cette page centrale.</p><div className="vm-hub-logo-row">{(hub.logo_url||selected?.logo_url)?<img src={hub.logo_url||selected?.logo_url||''} alt="Logo page centrale"/>:<div className="vm-hub-logo-empty"><Upload size={19}/></div>}<label className="btn btn-ghost"><Upload size={14}/>{busy==='hub-logo'?'Import…':'Choisir un logo'}<input type="file" accept="image/*" hidden disabled={!canHub||busy==='hub-logo'} onChange={e=>{const f=e.target.files?.[0];if(f)void uploadHubAsset(f,'logo');e.currentTarget.value=''}}/></label>{hub.logo_url&&<button className="btn btn-ghost" onClick={()=>setHub({...hub,logo_url:null})}>Reprendre le logo du catalogue</button>}</div><div style={{marginTop:14}}>{(hub.cover_url||selected?.cover_url)&&<img src={hub.cover_url||selected?.cover_url||''} alt="Bannière page centrale" style={{width:'100%',maxHeight:180,objectFit:'cover',borderRadius:16}}/>}<div style={{display:'flex',gap:8,flexWrap:'wrap',marginTop:8}}><label className="btn btn-ghost"><Upload size={14}/>{busy==='hub-cover'?'Import…':'Choisir une bannière'}<input type="file" accept="image/*" hidden disabled={!canHub||busy==='hub-cover'} onChange={e=>{const f=e.target.files?.[0];if(f)void uploadHubAsset(f,'cover');e.currentTarget.value=''}}/></label>{hub.cover_url&&<button className="btn btn-ghost" onClick={()=>setHub({...hub,cover_url:null})}>Reprendre la bannière du catalogue</button>}</div></div></section>

  <section className="vm-card"><h3>Design général / bouton menu</h3><p>Ces réglages servent de design par défaut et au bouton principal « Voir le menu / catalogue ». Les autres boutons peuvent avoir leur propre design dans « Contenu & liens ».</p><div className="vm-hub-design-grid"><label>Rendu<select className="input" value={hub.button_style} onChange={e=>setHub({...hub,button_style:e.target.value as ButtonStyle})} disabled={!canHub}><option value="solid">Couleur unie</option><option value="gradient">Gradient</option><option value="glossy">Glossy brillant</option><option value="metallic">Métallique</option></select></label><label>Couleur principale<input className="input vm-color" type="color" value={hub.button_color} onChange={e=>setHub({...hub,button_color:e.target.value})} disabled={!canHub}/></label><label>Couleur secondaire<input className="input vm-color" type="color" value={hub.button_color_2} onChange={e=>setHub({...hub,button_color_2:e.target.value})} disabled={!canHub}/></label><label>Couleur du texte<input className="input vm-color" type="color" value={hub.button_text_color} onChange={e=>setHub({...hub,button_text_color:e.target.value})} disabled={!canHub}/></label><label>Arrondi<select className="input" value={hub.button_radius} onChange={e=>setHub({...hub,button_radius:e.target.value})} disabled={!canHub}><option value="12px">Léger</option><option value="18px">Moderne</option><option value="26px">Très arrondi</option><option value="999px">Pilule</option></select></label></div><div className={`vm-hub-preview vm-style-${hub.button_style}`}><button style={globalPreview}><QrCode size={17}/><span>Voir le menu / catalogue</span><ExternalLink size={14}/></button></div><button className="btn btn-primary" onClick={saveHub} disabled={!canHub||busy==='hub'}><Save size={15}/>{busy==='hub'?'Enregistrement…':'Enregistrer le design général'}</button></section></div>}

  {tab==='media'&&<div className="vm-body"><section className="vm-card"><div className="vm-media-summary"><div><span>Crédits disponibles</span><strong>{credits}</strong></div><div><span>Articles / services</span><strong>{items.length}</strong></div><div><span>Sans image</span><strong>{missing.length}</strong></div></div><button className="btn btn-primary vm-generate" onClick={generateMissing} disabled={busy==='generate'||!missing.length}><Sparkles size={16}/>{missing.length?`Illustrer les ${missing.length} éléments · ${missing.length*5} crédits`:'Tout est déjà illustré'}</button><p className="vm-help">Créez rapidement les visuels manquants pour compléter votre catalogue.</p></section><section className="vm-card"><h3>Éléments du catalogue</h3><div className="vm-media-list">{items.map(i=><div key={i.id} className="vm-media-row">{i.image_url?<img src={i.image_url} alt=""/>:<div className="vm-media-empty"><ImagePlus size={17}/></div>}<span>{i.name}</span><b>{i.image_url?'Illustré':'À générer'}</b></div>)}</div></section></div>}</section></div>}</>;
}
