'use client';
import {useEffect,useState} from 'react';import {createPortal} from 'react-dom';import {Check} from 'lucide-react';
const plans=[
{name:'Free',price:'Gratuit',annual:'',oldAnnual:'',saving:'',description:'Un vrai catalogue Qatalink permanent pour démarrer sans carte bancaire.',features:['1 catalogue','20 articles maximum','5 scans QR / jour','10 commandes WhatsApp / jour','Présence dans Explorer','Designs essentiels'],featured:false},
{name:'Starter',price:'4 900 F',annual:'53 900 F / an',oldAnnual:'58 800 F',saving:'4 900 F',description:'Pour vendre régulièrement sans limites quotidiennes de scans ou de commandes.',features:['85 articles maximum','Scans QR illimités','Commandes WhatsApp illimitées','QR permanent','Designs supplémentaires','Crédits IA rechargeables'],featured:false},
{name:'Pro',price:'14 900 F',annual:'163 900 F / an',oldAnnual:'178 800 F',saving:'14 900 F',description:'Pour centraliser commandes, équipe, caisse et opérations dans Qatalink.',features:['250 articles maximum','Tout Starter','Commandes privées Qatalink','Accès équipe et permissions','Caisse + tickets thermiques','Suivi livraison','Meilleure visibilité dans Explorer'],featured:true},
{name:'Business',price:'29 900 F',annual:'328 900 F / an',oldAnnual:'358 800 F',saving:'29 900 F',description:'Pour les activités structurées qui veulent exploiter Qatalink à plus grande échelle.',features:['Articles illimités','Tout Pro','Jusqu’à 15 catalogues','Stock avancé','Prévisions & projections avancées','Page centrale multi-catalogues','Priorité supérieure dans Explorer','IA et analytics avancés'],featured:false}];
function setText(node:Element|null,value:string){if(node&&(node.textContent||'').trim()!==value)node.textContent=value}
export function LandingPricingRefresh(){const [target,setTarget]=useState<Element|null>(null);useEffect(()=>{if(location.pathname!=='/')return;let timer:ReturnType<typeof setTimeout>|null=null;const apply=()=>{const pricing=document.querySelector('#pricing .pricing');setTarget(pricing);pricing?.querySelectorAll<HTMLElement>(':scope > .price-card:not(.q-new-plan)').forEach(x=>x.style.display='none');const section=document.querySelector('#pricing');setText(section?.querySelector('.section-head h2')||null,'Commencez gratuitement. Payez seulement quand votre activité grandit.');setText(section?.querySelector('.section-head p')||null,'Free reste actif sans limite de temps. Starter enlève les limites quotidiennes, Pro ajoute les opérations et l’équipe, Business déploie l’écosystème à plus grande échelle.');const pill=document.querySelector('.hero-conversion .pill');setText(pill,'Gratuit pour commencer · aucune carte requise');document.querySelectorAll('#faq details').forEach(d=>{const q=d.querySelector('summary'),a=d.querySelector('p');if(!q||!a)return;const text=(q.textContent||'').trim();if(text==='Quand commencent les 7 jours gratuits ?'){q.textContent='Existe-t-il une formule gratuite ?';a.textContent='Oui. Free reste actif sans limite de temps : 20 articles, 5 scans QR par jour et 10 commandes WhatsApp par jour.'}if(text==='Que se passe-t-il après l’essai ?'){q.textContent='Puis-je rester gratuitement ?';a.textContent='Oui. Votre catalogue reste en Free aussi longtemps que vous le souhaitez. Vous passez à une formule payante uniquement pour augmenter vos limites et débloquer plus d’outils.'}})};const schedule=()=>{if(timer)clearTimeout(timer);timer=setTimeout(apply,30)};apply();const mo=new MutationObserver(schedule);mo.observe(document.body,{childList:true,subtree:true});return()=>{if(timer)clearTimeout(timer);mo.disconnect()}},[]);if(!target)return null;return createPortal(<>{plans.map(p=><article className={`price-card q-new-plan ${p.featured?'featured':''}`} key={p.name}>{p.featured&&<span className="popular">LE PLUS CHOISI</span>}<h3>{p.name}</h3><div className="price">{p.price}<small>{p.name==='Free'?' pour toujours':'/ mois'}</small></div>{p.annual&&<div className="q-plan-annual"><b>{p.annual}</b><span><s>{p.oldAnnual}</s> · 1 mois offert</span><strong>Vous économisez {p.saving}</strong></div>}<p>{p.description}</p><div className="features">{p.features.map(f=><div className="feature" key={f}><Check size={16}/>{f}</div>)}</div><a className="btn btn-primary q-plan-cta" href="/create">{p.name==='Free'?'Commencer gratuitement':`Choisir ${p.name}`}</a></article>)}</>,target)}
