'use client';

import {Bell,BellRing} from 'lucide-react';
import {createPortal} from 'react-dom';
import {useEffect,useRef,useState} from 'react';

export function OpsOrderNotifications({accessKey}:{accessKey:string}){
 const [permission,setPermission]=useState<string>('default'),[host,setHost]=useState<Element|null>(null),[unread,setUnread]=useState(0);const known=useRef(new Set<string>()),initialized=useRef(false);
 useEffect(()=>{const supported='Notification'in window;setPermission(supported?Notification.permission:'unsupported');const locate=()=>setHost(document.querySelector('.ops-header-actions')||document.querySelector('.ops-header'));locate();const t=setTimeout(locate,500);return()=>clearTimeout(t)},[]);
 async function ask(){if(await window.qatalinkNativeNotificationPermission?.()){setPermission('granted');return true}if(!('Notification'in window))return false;const p=await Notification.requestPermission();setPermission(p);return p==='granted'}
 async function notify(order:any){const title=`Nouvelle commande ${order.order_number||''}`.trim(),body=[order.table_number?`Table ${order.table_number}`:'',order.total_minor!=null?`${new Intl.NumberFormat('fr-FR').format(Number(order.total_minor))} ${order.currency_code||'XOF'}`:''].filter(Boolean).join(' · ')||'Une nouvelle commande est à traiter.';setUnread(v=>v+1);navigator.vibrate?.([180,80,180]);if(await window.qatalinkNativeNotify?.(title,body,`/ops/${encodeURIComponent(accessKey)}`))return;if(!('Notification'in window)||Notification.permission!=='granted')return;const opts:NotificationOptions={body,icon:'/qatalink-icon.svg',badge:'/qatalink-icon.svg',tag:`qatalink-order-${order.id}`,requireInteraction:true,data:{url:`/ops/${encodeURIComponent(accessKey)}`}};try{const r=await navigator.serviceWorker?.ready;if(r){await r.showNotification(title,opts);return}}catch{}try{new Notification(title,opts)}catch{}}
 useEffect(()=>{let stop=false;async function poll(){let pin='';try{pin=sessionStorage.getItem(`qatalink_ops_pin_${accessKey}`)||''}catch{}if(!pin)return;try{const r=await fetch('/api/ops/orders',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({access_key:accessKey,pin,action:'list',limit:40}),cache:'no-store'});const d=await r.json().catch(()=>({}));if(!r.ok)return;const orders=Array.isArray(d.orders)?d.orders:[];if(!initialized.current){orders.forEach((o:any)=>known.current.add(String(o.id)));initialized.current=true;return}for(const o of orders){const id=String(o.id);if(known.current.has(id))continue;known.current.add(id);if(o.status==='new')void notify(o)}}catch{}}void poll();const t=setInterval(()=>{if(!stop)void poll()},5000);return()=>{stop=true;clearInterval(t)}},[accessKey]);
 async function click(){if(permission!=='granted'&&permission!=='unsupported')await ask();setUnread(0)}
 const button=<button type="button" onClick={()=>void click()} title={permission==='granted'?'Notifications de commandes actives':'Activer les notifications de commandes'} style={{position:'relative',width:42,height:42,border:'1px solid #dedee3',borderRadius:13,background:'#111',color:'#fff',display:'grid',placeItems:'center',flex:'0 0 auto'}}>{unread?<BellRing size={18}/>:<Bell size={18}/>} {unread>0&&<i style={{position:'absolute',right:-5,top:-6,minWidth:20,height:20,padding:'0 5px',borderRadius:99,background:'#d71936',color:'#fff',border:'2px solid #fff',font:'900 10px/16px sans-serif',fontStyle:'normal'}}>{Math.min(unread,99)}</i>}</button>;
 return host?createPortal(button,host):<div style={{position:'fixed',right:14,top:'max(14px,env(safe-area-inset-top))',zIndex:2147482600}}>{button}</div>;
}
