'use client';

import {useEffect,useMemo,useState} from 'react';
import {createPortal} from 'react-dom';
import {Download,Plus,ReceiptText,Trash2,X} from 'lucide-react';
import {createSupabaseBrowserClient} from '@/lib/supabase';

type Entry={id:string;client_name:string;business_name:string|null;amount_xof:number;revenue_type:string;payment_status:'paid'|'partial'|'pending';payment_method:string|null;channel:string|null;is_recurring:boolean;monthly_amount_xof:number|null;received_at:string;notes:string|null};
const money=(n:number)=>new Intl.NumberFormat('fr-FR').format(Math.round(n))+' F CFA';

export function OwnerRevenueCenter(){
  const supabase=useMemo(()=>createSupabaseBrowserClient(),[]);
  const [allowed,setAllowed]=useState(false);const [desktop,setDesktop]=useState<Element|null>(null);const [mobile,setMobile]=useState<Element|null>(null);const [open,setOpen]=useState(false);const [rows,setRows]=useState<Entry[]>([]);const [busy,setBusy]=useState(false);const [userId,setUserId]=useState('');
  const [form,setForm]=useState({client_name:'',business_name:'',amount_xof:'',revenue_type:'installation',payment_status:'paid',payment_method:'Mobile Money',channel:'QR Digital',is_recurring:false,monthly_amount_xof:'',received_at:new Date().toISOString().slice(0,10),notes:''});

  useEffect(()=>{let cancelled=false;(async()=>{const {data:{session}}=await supabase.auth.getSession();if(!session||cancelled)return;setUserId(session.user.id);const {data:o}=await supabase.from('account_access_overrides').select('all_features').eq('user_id',session.user.id).maybeSingle();if(cancelled||!o?.all_features)return;setAllowed(true);const resolve=()=>{setDesktop(document.querySelector('.dash-v3-nav'));setMobile(document.querySelector('.dash-v3-mobile-tabs'))};resolve();[150,500,1200].forEach(ms=>setTimeout(resolve,ms));await load()})();return()=>{cancelled=true}},[supabase]);

  async function load(){const {data}=await supabase.from('service_revenue_entries').select('*').order('received_at',{ascending:false}).order('created_at',{ascending:false});setRows((data||[]) as Entry[])}
  async function add(){if(!userId||!form.client_name.trim()||Number(form.amount_xof)<0)return;setBusy(true);const {error}=await supabase.from('service_revenue_entries').insert({owner_user_id:userId,client_name:form.client_name.trim(),business_name:form.business_name.trim()||null,amount_xof:Math.round(Number(form.amount_xof||0)),revenue_type:form.revenue_type,payment_status:form.payment_status,payment_method:form.payment_method||null,channel:form.channel||null,is_recurring:form.is_recurring,monthly_amount_xof:form.is_recurring?Math.round(Number(form.monthly_amount_xof||0)):null,received_at:form.received_at,notes:form.notes.trim()||null});setBusy(false);if(error){alert(error.message);return}setForm(v=>({...v,client_name:'',business_name:'',amount_xof:'',monthly_amount_xof:'',notes:''}));await load()}
  async function remove(id:string){if(!confirm('Supprimer cet encaissement ?'))return;await supabase.from('service_revenue_entries').delete().eq('id',id);await load()}
  function exportCsv(){const head=['Date','Client','Business','Montant XOF','Type','Statut','Paiement','Canal','Récurrent','MRR XOF','Notes'];const csv=[head,...rows.map(r=>[r.received_at,r.client_name,r.business_name||'',r.amount_xof,r.revenue_type,r.payment_status,r.payment_method||'',r.channel||'',r.is_recurring?'Oui':'Non',r.monthly_amount_xof||'',r.notes||''])].map(line=>line.map(v=>'"'+String(v).replace(/"/g,'""')+'"').join(';')).join('\n');const blob=new Blob(['\ufeff'+csv],{type:'text/csv;charset=utf-8'});const url=URL.createObjectURL(blob);const a=document.createElement('a');a.href=url;a.download='encaissements-qatalink.csv';a.click();setTimeout(()=>URL.revokeObjectURL(url),2000)}

  if(!allowed)return null;
  const total=rows.filter(r=>r.payment_status==='paid').reduce((s,r)=>s+Number(r.amount_xof||0),0);const now=new Date();const month=rows.filter(r=>{const d=new Date(r.received_at+'T00:00:00');return r.payment_status==='paid'&&d.getMonth()===now.getMonth()&&d.getFullYear()===now.getFullYear()}).reduce((s,r)=>s+Number(r.amount_xof||0),0);const mrr=rows.filter(r=>r.is_recurring&&r.payment_status==='paid').reduce((s,r)=>s+Number(r.monthly_amount_xof||0),0);const clients=new Set(rows.filter(r=>r.payment_status==='paid').map(r=>(r.business_name||r.client_name).toLowerCase())).size;
  const navButton=<button className="dash-tool-nav owner-revenue-nav" onClick={()=>setOpen(true)}><ReceiptText size={16}/><span>Encaissements</span></button>;
  return <>{desktop&&createPortal(navButton,desktop)}{mobile&&createPortal(navButton,mobile)}{open&&createPortal(<div style={{position:'fixed',inset:0,zIndex:10000,background:'rgba(0,0,0,.82)',backdropFilter:'blur(10px)',padding:'20px',overflow:'auto'}}><section style={{width:'min(1180px,100%)',margin:'20px auto',background:'var(--surface,#111)',color:'var(--text,#fff)',border:'1px solid var(--line,rgba(255,255,255,.12))',borderRadius:24,padding:24,boxShadow:'0 30px 100px rgba(0,0,0,.5)'}}>
    <header style={{display:'flex',justifyContent:'space-between',gap:20,alignItems:'flex-start',marginBottom:22}}><div><span className="eyebrow">ESPACE PERSONNEL</span><h2 style={{margin:'10px 0 6px'}}>Encaissements Service as a Software</h2><p style={{margin:0}}>Suivi privé des montants réellement encaissés via vos prestations clé-en-main.</p></div><button className="btn btn-ghost" onClick={()=>setOpen(false)} aria-label="Fermer"><X size={18}/></button></header>
    <div style={{display:'grid',gridTemplateColumns:'repeat(auto-fit,minmax(180px,1fr))',gap:12,marginBottom:22}}>{[[money(total),'Total encaissé'],[money(month),'Ce mois'],[money(mrr),'MRR déclaré'],[String(clients),'Clients payants']].map(([v,l])=><div key={l} className="dash-card" style={{padding:18}}><strong style={{display:'block',fontSize:24}}>{v}</strong><span style={{opacity:.7}}>{l}</span></div>)}</div>
    <section className="dash-card" style={{marginBottom:20}}><h3>Ajouter un encaissement</h3><div className="settings-v2-grid"><div className="field"><label>Client *</label><input className="input" value={form.client_name} onChange={e=>setForm({...form,client_name:e.target.value})}/></div><div className="field"><label>Business</label><input className="input" value={form.business_name} onChange={e=>setForm({...form,business_name:e.target.value})}/></div><div className="field"><label>Montant encaissé (F CFA) *</label><input className="input" type="number" min="0" value={form.amount_xof} onChange={e=>setForm({...form,amount_xof:e.target.value})}/></div><div className="field"><label>Date</label><input className="input" type="date" value={form.received_at} onChange={e=>setForm({...form,received_at:e.target.value})}/></div><div className="field"><label>Type</label><select className="input" value={form.revenue_type} onChange={e=>setForm({...form,revenue_type:e.target.value})}><option value="installation">Installation</option><option value="abonnement">Abonnement</option><option value="impression">Impression</option><option value="pos">POS / caisse</option><option value="seo_local">Visibilité locale</option><option value="design">Design imprimable</option><option value="option">Option</option><option value="autre">Autre</option></select></div><div className="field"><label>Statut</label><select className="input" value={form.payment_status} onChange={e=>setForm({...form,payment_status:e.target.value as any})}><option value="paid">Payé</option><option value="partial">Partiel</option><option value="pending">En attente</option></select></div><div className="field"><label>Paiement</label><input className="input" value={form.payment_method} onChange={e=>setForm({...form,payment_method:e.target.value})}/></div><div className="field"><label>Canal</label><input className="input" value={form.channel} onChange={e=>setForm({...form,channel:e.target.value})}/></div><div className="field"><label><input type="checkbox" checked={form.is_recurring} onChange={e=>setForm({...form,is_recurring:e.target.checked})}/> Revenu récurrent</label>{form.is_recurring&&<input className="input" type="number" min="0" placeholder="Montant mensuel" value={form.monthly_amount_xof} onChange={e=>setForm({...form,monthly_amount_xof:e.target.value})}/>}</div><div className="field wide"><label>Notes</label><textarea className="input" rows={2} value={form.notes} onChange={e=>setForm({...form,notes:e.target.value})}/></div></div><button className="btn btn-primary" onClick={add} disabled={busy||!form.client_name.trim()||!form.amount_xof}><Plus size={16}/>{busy?'Enregistrement…':'Enregistrer'}</button></section>
    <section className="dash-card"><div style={{display:'flex',justifyContent:'space-between',gap:12,alignItems:'center',marginBottom:14}}><h3 style={{margin:0}}>Historique</h3><button className="btn btn-ghost" onClick={exportCsv}><Download size={15}/>Exporter CSV</button></div><div style={{overflowX:'auto'}}><table style={{width:'100%',borderCollapse:'collapse',minWidth:820}}><thead><tr>{['Date','Client / Business','Montant','Type','Statut','Récurrent',''].map(h=><th key={h} style={{textAlign:'left',padding:'10px 8px',borderBottom:'1px solid var(--line)'}}>{h}</th>)}</tr></thead><tbody>{rows.map(r=><tr key={r.id}><td style={{padding:'11px 8px',borderBottom:'1px solid var(--line)'}}>{new Date(r.received_at+'T00:00:00').toLocaleDateString('fr-FR')}</td><td style={{padding:'11px 8px',borderBottom:'1px solid var(--line)'}}><b>{r.business_name||r.client_name}</b>{r.business_name&&<small style={{display:'block',opacity:.65}}>{r.client_name}</small>}</td><td style={{padding:'11px 8px',borderBottom:'1px solid var(--line)',fontWeight:800}}>{money(r.amount_xof)}</td><td style={{padding:'11px 8px',borderBottom:'1px solid var(--line)'}}>{r.revenue_type}</td><td style={{padding:'11px 8px',borderBottom:'1px solid var(--line)'}}>{r.payment_status}</td><td style={{padding:'11px 8px',borderBottom:'1px solid var(--line)'}}>{r.is_recurring?money(Number(r.monthly_amount_xof||0))+'/mois':'—'}</td><td style={{padding:'11px 8px',borderBottom:'1px solid var(--line)'}}><button className="mini-action" onClick={()=>remove(r.id)}><Trash2 size={13}/></button></td></tr>)}</tbody></table>{!rows.length&&<p style={{opacity:.7}}>Aucun encaissement enregistré pour le moment.</p>}</div></section>
  </section></div>,document.body)}</>;
}
