'use client';
import {Check,CreditCard,X} from 'lucide-react';import {useEffect,useState} from 'react';import {createSupabaseBrowserClient} from '@/lib/supabase';import {PaymentTrustBadge} from '@/components/payment-trust-badge';import {useSubscriptionPricing} from '@/components/use-subscription-pricing';
type Props={open:boolean;onClose?:()=>void;title?:string;trialExpiresAt?:string|null;trialActive?:boolean};type Paid='starter'|'pro'|'business';type Plan={id:'free'|Paid;name:string;monthlyPrice:number;annualPrice:number;description:string;features:string[];featured:boolean};
const plans:Plan[]=[
{id:'free',name:'Free',monthlyPrice:0,annualPrice:0,description:'Pour démarrer, tester le marché et garder un catalogue Qatalink actif sans limite de temps.',features:['1 catalogue','Jusqu’à 20 articles','5 scans QR par jour','10 commandes WhatsApp par jour','Présence dans Explorer','Designs essentiels'],featured:false},
{id:'starter',name:'Starter',monthlyPrice:4900,annualPrice:53900,description:'Pour vendre régulièrement avec un catalogue plus fourni et aucune limite quotidienne de scans ou commandes.',features:['Jusqu’à 85 articles','Scans QR illimités','Commandes WhatsApp illimitées','QR permanent','Designs supplémentaires','Crédits IA rechargeables'],featured:false},
{id:'pro',name:'Pro',monthlyPrice:14900,annualPrice:163900,description:'Le cœur de Qatalink pour les commerces qui centralisent commandes, équipe et opérations.',features:['Jusqu’à 250 articles','Tout Starter','Catalogue bilingue français / anglais','Commandes privées Qatalink','Accès équipe et permissions','Caisse et tickets thermiques','Suivi livraison','Meilleure visibilité dans Explorer'],featured:true},
{id:'business',name:'Business',monthlyPrice:29900,annualPrice:328900,description:'Pour les activités structurées qui veulent exploiter l’écosystème Qatalink à plus grande échelle.',features:['Articles illimités','Tout Pro','Catalogue bilingue français / anglais','Jusqu’à 15 catalogues','Stock avancé et déductions','Prévisions & projections avancées','Page centrale multi-catalogues','Priorité supérieure dans Explorer','Outils IA et analytics avancés'],featured:false}];
export function PricingGate({open,onClose,title='Choisissez votre formule Qatalink'}:Props){const [forced,setForced]=useState(false),[period,setPeriod]=useState<'monthly'|'annual'>('monthly'),[loading,setLoading]=useState<string|null>(null),[error,setError]=useState('');const {format,isUsd}=useSubscriptionPricing();useEffect(()=>{const sync=()=>setForced(new URLSearchParams(location.search).get('paywall')==='1');sync();addEventListener('popstate',sync);return()=>removeEventListener('popstate',sync)},[]);if(!(open||forced))return null;
 function close(){if(forced){const u=new URL(location.href);u.searchParams.delete('paywall');history.replaceState({},'',u.toString());setForced(false)}onClose?.()}
 async function checkout(plan:Paid){setLoading(plan);setError('');try{const supabase=createSupabaseBrowserClient();const {data:{session}}=await supabase.auth.getSession();if(!session){location.href='/login?next=/dashboard';return}const name=String(session.user.user_metadata?.full_name||'').trim().split(/\s+/);const r=await fetch('/api/checkout/maketou',{method:'POST',headers:{'Content-Type':'application/json',Authorization:`Bearer ${session.access_token}`},body:JSON.stringify({plan,firstName:name[0]||'Client',lastName:name.slice(1).join(' ')||'Qatalink',billingPeriod:period})});const d=await r.json();if(!r.ok)throw new Error(d?.message||'Impossible de lancer le paiement.');const url=d.redirectUrl||d.redirectURL,cart=d.cart?.id||d.id;if(cart)localStorage.setItem('qatalink_maketou_cart_id',cart);if(!url)throw new Error('Lien de paiement indisponible.');location.href=url}catch(e:any){setError(e?.message||'Paiement indisponible.');setLoading(null)}}
 return <div className="paywall-backdrop" role="dialog" aria-modal="true"><div className="paywall-modal"><button className="paywall-close" onClick={close}><X size={20}/></button><div className="paywall-head"><div className="eyebrow">QATALINK FREEMIUM</div><h2>{title}</h2><p>Restez gratuitement aussi longtemps que vous voulez, puis augmentez vos limites lorsque votre activité en a besoin.</p><div className="billing-toggle"><button className={period==='monthly'?'active':''} onClick={()=>setPeriod('monthly')}>Mensuel</button><button className={period==='annual'?'active':''} onClick={()=>setPeriod('annual')}>Annuel <span className="annual-badge">1 mois offert</span></button></div><PaymentTrustBadge compact/></div><div className="paywall-plans">{plans.map(p=>{const amount=period==='annual'?p.annualPrice:p.monthlyPrice;return <article className={`price-card ${p.featured?'featured':''}`} key={p.id}>{p.featured&&<span className="popular">LE PLUS CHOISI</span>}<h3>{p.name}</h3><div className="price">{p.id==='free'?'Gratuit':format(amount)}<small>{p.id==='free'?' pour toujours':period==='annual'?'/ an':'/ mois'}</small></div>{p.id!=='free'&&period==='annual'&&<div className="annual-equivalent"><s>{format(p.monthlyPrice*12)}</s> · économisez {format(p.monthlyPrice)}</div>}{p.id!=='free'&&<div className="plan-payment-method"><CreditCard size={14}/>{isUsd?'Paiement sécurisé par carte':'Paiement hors de l’app · Mobile Money ou carte'}</div>}<p>{p.description}</p><div className="features">{p.features.map(f=><div className="feature" key={f}><Check size={16}/>{f}</div>)}</div><button className="btn btn-primary" style={{width:'100%'}} disabled={loading!==null} onClick={()=>p.id==='free'?close():void checkout(p.id)}>{p.id==='free'?'Continuer avec Free':loading===p.id?'Ouverture du paiement…':`Choisir ${p.name}`}</button></article>})}</div>{error&&<div className="error" style={{textAlign:'center',marginTop:14}}>{error}</div>}</div></div>}
