'use client';
import {useEffect,useRef,useState} from 'react';import {ChevronUp,Download,Plus,X} from 'lucide-react';
type PromptEvent=Event&{prompt:()=>Promise<void>;userChoice:Promise<{outcome:string}>};
export function PublicFreePlanCta(){const [free,setFree]=useState(false),[open,setOpen]=useState(false),[prompt,setPrompt]=useState<PromptEvent|null>(null);const originalOpen=useRef<typeof window.open|null>(null);
 useEffect(()=>{if(!location.pathname.startsWith('/c/'))return;const slug=decodeURIComponent(location.pathname.split('/')[2]||'');if(!slug)return;fetch(`/api/public/quota?slug=${encodeURIComponent(slug)}`,{cache:'no-store'}).then(r=>r.json()).then(d=>setFree(d?.plan_code==='free')).catch(()=>{});const onPrompt=(e:Event)=>{e.preventDefault();setPrompt(e as PromptEvent)};window.addEventListener('beforeinstallprompt',onPrompt);return()=>window.removeEventListener('beforeinstallprompt',onPrompt)},[]);
 useEffect(()=>{if(!free)return;document.documentElement.dataset.qatalinkFreeCatalog='true';window.dispatchEvent(new Event('qatalink:free-catalog'));const hide=()=>document.querySelectorAll<HTMLElement>('.pwa-install-trigger,.pwa-install-card').forEach(x=>x.style.display='none');hide();const mo=new MutationObserver(hide);mo.observe(document.body,{childList:true,subtree:true});return()=>{delete document.documentElement.dataset.qatalinkFreeCatalog;mo.disconnect()}},[free]);
 useEffect(()=>{if(!free||!location.pathname.startsWith('/c/'))return;const slug=decodeURIComponent(location.pathname.split('/')[2]||'');originalOpen.current=window.open.bind(window);const patched=((url?:string|URL,target?:string,features?:string)=>{const raw=String(url||'');if(!/https:\/\/wa\.me\//i.test(raw))return originalOpen.current!(url as any,target,features);const popup=originalOpen.current!('about:blank',target||'_blank',features);void fetch('/api/public/quota',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({slug})}).then(r=>r.json()).then(d=>{if(d?.allowed){if(popup)popup.location.href=raw;else location.href=raw}else{popup?.close();alert('Ce vendeur a atteint sa limite gratuite de 10 commandes WhatsApp aujourd’hui. Les commandes seront de nouveau disponibles demain.')}}).catch(()=>{popup?.close();alert('Impossible de vérifier la limite WhatsApp. Réessayez.')});return popup}) as typeof window.open;window.open=patched;return()=>{if(originalOpen.current)window.open=originalOpen.current}},[free]);
 async function install(){if(prompt){await prompt.prompt();await prompt.userChoice;setPrompt(null);return}alert(/iPhone|iPad|iPod/i.test(navigator.userAgent)?'Dans Safari : Partager → Sur l’écran d’accueil → Ajouter.':'Dans le menu du navigateur, choisissez Installer l’application ou Ajouter à l’écran d’accueil.')}
 if(!free)return null;return <div style={{position:'fixed',right:16,bottom:'calc(82px + env(safe-area-inset-bottom))',zIndex:80,display:'grid',justifyItems:'end',gap:8}}>{open&&<div style={{width:'min(330px,calc(100vw - 32px))',padding:16,borderRadius:20,background:'#fff',boxShadow:'0 16px 50px rgba(0,0,0,.2)',border:'1px solid #eee'}}><div style={{display:'flex',justifyContent:'space-between',gap:10}}><div><b>Retrouvez cette adresse dans Qatalink</b><p style={{margin:'6px 0 12px',fontSize:13,opacity:.65,lineHeight:1.4}}>Ajoutez Qatalink à votre téléphone pour retrouver les catalogues déjà visités, explorer de nouvelles adresses et commander plus vite.</p></div><button onClick={()=>setOpen(false)} style={{border:0,background:'transparent'}}><X size={18}/></button></div><button onClick={install} style={{width:'100%',padding:11,border:0,borderRadius:13,background:'#111',color:'#fff',fontWeight:800,display:'flex',gap:8,justifyContent:'center'}}><Download size={17}/>Ajouter Qatalink</button><a href="/create" style={{marginTop:8,padding:10,borderRadius:12,display:'flex',gap:7,justifyContent:'center',textDecoration:'none',background:'#f3f3f5',color:'#111',fontSize:13,fontWeight:700}}><Plus size={16}/>Digitalisez votre business avec Qatalink</a></div>}<button onClick={()=>setOpen(v=>!v)} aria-label="Qatalink" style={{border:0,borderRadius:999,padding:8,background:'#fff',boxShadow:'0 8px 28px rgba(0,0,0,.22)',display:'flex',alignItems:'center',gap:8,fontWeight:800}}><img src="/qatalink-icon.svg" alt="" style={{width:42,height:42,animation:'qFreePulse 1.8s ease-in-out infinite'}}/>{open?<ChevronUp size={18}/>:<span style={{paddingRight:7,fontSize:12}}>Qatalink</span>}<style>{'@keyframes qFreePulse{0%,100%{transform:scale(1)}50%{transform:scale(1.09)}}'}</style></button></div>}
