'use client';

import {Minus,Plus,ShoppingBag,Trash2,X,ZoomIn} from 'lucide-react';
import {useMemo,useState} from 'react';

type AnyItem={id:string;name:string;description?:string|null;price_minor?:number|null;promo_price_minor?:number|null;promo_starts_at?:string|null;promo_ends_at?:string|null;image_url?:string|null};

function promoActive(item:AnyItem){if(item.promo_price_minor===null||item.promo_price_minor===undefined)return false;const now=Date.now();if(item.promo_starts_at&&new Date(item.promo_starts_at).getTime()>now)return false;if(item.promo_ends_at&&new Date(item.promo_ends_at).getTime()<=now)return false;return true}
function defaults(type:string){if(type==='restaurant')return ['dine_in','takeaway','delivery'];if(type==='retail')return ['pickup','delivery'];if(type==='hotel')return ['availability','reservation'];if(type==='spa_beauty')return ['appointment','information'];if(type==='real_estate')return ['availability','visit','reservation','deposit'];return ['contact']}
const LABELS:Record<string,string>={dine_in:'Sur place',takeaway:'À emporter',delivery:'Livraison',pickup:'Retrait sur place',availability:'Vérifier la disponibilité',reservation:'Réserver',appointment:'Prendre rendez-vous',information:'Demander des informations',visit:'Demander une visite',deposit:'Réserver avec acompte',contact:'Contacter l’entreprise'};

export function PublicCatalogV2({data}:{data:any}){
  const pages=Array.isArray(data?.pages)?data.pages:[];const categories=Array.isArray(data?.categories)?data.categories:[];const initialPage=pages?.[0]?.id||'';const initialCategory=(initialPage?categories.find((c:any)=>c.page_id===initialPage):categories[0])?.id||'';
  const [activePage,setActivePage]=useState(initialPage);const [cart,setCart]=useState<Record<string,number>>({});const [activeCategory,setActiveCategory]=useState(initialCategory);const [zoom,setZoom]=useState<{url:string;name:string}|null>(null);const [cartOpen,setCartOpen]=useState(false);const [flowOpen,setFlowOpen]=useState(false);const [flowMode,setFlowMode]=useState('');const [flowFields,setFlowFields]=useState<Record<string,string>>({});
  const plan=String(data?.plan_code||'');const interactive=['trial','interactive','linkhub'].includes(plan);const visibleCategories=activePage?categories.filter((c:any)=>c.page_id===activePage):categories;const allItems=categories.flatMap((c:any)=>Array.isArray(c.items)?c.items:[]);const currency=data?.business?.currency_code||'XOF';const businessType=String(data?.business?.business_type||'other');const flowSettings=data?.business?.customer_flow_settings||{};const flowModes=(Array.isArray(flowSettings.modes)&&flowSettings.modes.length?flowSettings.modes:defaults(businessType)) as string[];const effectiveFlowMode=flowMode||flowModes[0]||'contact';
  const theme=data?.theme||{};const primary=theme.primary_color||'#B5122B';const secondary=theme.secondary_color||'#F7E8EA';const bg=theme.background_color||'#FFFFFF';const bgMode=theme.background_mode||'solid';const bgGradient=theme.background_gradient||'';const bgImage=theme.background_image_url||'';const overlay=Math.max(0,Math.min(.85,Number(theme.background_image_overlay??.18)));const blur=Math.max(0,Math.min(40,Number(theme.background_image_blur??0)));const textColor=theme.text_color||'#171719';const headingFont=theme.heading_font||'Plus Jakarta Sans';const bodyFont=theme.body_font||'Plus Jakarta Sans';const radius=theme.border_radius||'18px';const layout=theme.layout_style||'list';const showName=theme.show_business_name!==false;const showLogo=theme.show_logo!==false;const showPrices=theme.show_prices!==false;const align=theme.header_alignment||'left';const logoShape=theme.logo_shape||'rounded';const isMenu=String(data?.catalog?.type||'menu')==='menu';
  const format=(v:number)=>currency==='XOF'?`${new Intl.NumberFormat('fr-FR').format(v).replace(/\u202f/g,' ')} F`:new Intl.NumberFormat('fr-FR',{style:'currency',currency}).format(v);const selected=allItems.filter((i:any)=>(cart[i.id]||0)>0);const unit=(i:AnyItem)=>promoActive(i)?Number(i.promo_price_minor||0):Number(i.price_minor||0);const total=selected.reduce((sum:number,i:any)=>sum+unit(i)*(cart[i.id]||0),0);const itemCount=selected.reduce((s:number,i:any)=>s+(cart[i.id]||0),0);const phone=String(data?.business?.whatsapp_number||'').replace(/\D/g,'');

  const flowLines=useMemo(()=>{const lines:string[]=[];const mode=effectiveFlowMode;if(mode)lines.push(`Option : ${LABELS[mode]||mode}`);if(mode==='dine_in'&&flowFields.table)lines.push(`Table : ${flowFields.table}`);if((mode==='delivery')&&flowFields.address)lines.push(`Adresse : ${flowFields.address}`);if((mode==='delivery')&&flowFields.area)lines.push(`Quartier / zone : ${flowFields.area}`);if((mode==='hotel'||businessType==='hotel')&&flowFields.arrival)lines.push(`Arrivée : ${flowFields.arrival}`);if((mode==='hotel'||businessType==='hotel')&&flowFields.departure)lines.push(`Départ : ${flowFields.departure}`);if(businessType==='hotel'&&flowFields.guests)lines.push(`Personnes : ${flowFields.guests}`);if((mode==='appointment'||mode==='visit')&&flowFields.date)lines.push(`Date souhaitée : ${flowFields.date}`);if((mode==='appointment'||mode==='visit')&&flowFields.time)lines.push(`Heure souhaitée : ${flowFields.time}`);if(flowFields.note)lines.push(`Précision : ${flowFields.note}`);if(mode==='deposit'&&showPrices&&total>0){const pct=Math.max(1,Math.min(100,Number(flowSettings.deposit_percent||10)));lines.push(`Acompte indicatif (${pct} %) : ${format(Math.round(total*pct/100))}`)}return lines},[effectiveFlowMode,flowFields,businessType,total,showPrices,flowSettings.deposit_percent]);

  const message=useMemo(()=>{if(interactive&&selected.length){const lines=selected.map((i:any)=>{const qty=cart[i.id]||0;return `• ${qty} × ${i.name}${showPrices?` — ${format(unit(i))} l’unité`:''}`});const intent=businessType==='restaurant'?'je souhaite commander':businessType==='retail'?'je souhaite commander':businessType==='hotel'?'je souhaite faire une demande':businessType==='spa_beauty'?'je souhaite réserver':businessType==='real_estate'?'je suis intéressé par cette sélection':'je vous contacte';return `Bonjour ${data?.business?.name||''}, ${intent} depuis votre Qatalink :\n\n${lines.join('\n')}${showPrices?`\n\nTotal : ${format(total)}`:''}${flowLines.length?`\n\n${flowLines.join('\n')}`:''}`;}return `Bonjour ${data?.business?.name||''}, je vous contacte depuis votre catalogue Qatalink.`},[cart,selected,total,interactive,showPrices,data?.business?.name,businessType,flowLines]);
  const whatsapp=phone?`https://wa.me/${phone}?text=${encodeURIComponent(message)}`:'#';const change=(id:string,delta:number)=>setCart(prev=>({...prev,[id]:Math.max(0,(prev[id]||0)+delta)}));const remove=(id:string)=>setCart(prev=>({...prev,[id]:0}));const jump=(id:string)=>{setActiveCategory(id);document.getElementById(`cat-${id}`)?.scrollIntoView({behavior:'smooth',block:'start'})};const choosePage=(pageId:string)=>{setActivePage(pageId);setActiveCategory(categories.find((c:any)=>c.page_id===pageId)?.id||'');window.scrollTo({top:0,behavior:'smooth'})};
  const needsTable=effectiveFlowMode==='dine_in';const needsAddress=effectiveFlowMode==='delivery';const needsHotel=businessType==='hotel'&&(effectiveFlowMode==='availability'||effectiveFlowMode==='reservation');const needsSlot=effectiveFlowMode==='appointment'||effectiveFlowMode==='visit';const flowValid=(!needsTable||!!flowFields.table)&&(!needsAddress||!!flowFields.address)&&(!needsHotel||(!!flowFields.arrival&&!!flowFields.departure&&!!flowFields.guests))&&(!needsSlot||(!!flowFields.date&&!!flowFields.time));
  const openFlow=()=>{if(!interactive||!selected.length)return;setFlowMode(m=>m||flowModes[0]||'contact');setCartOpen(false);setFlowOpen(true)};
  const headingStyle:React.CSSProperties={fontFamily:`${headingFont}, sans-serif`,fontWeight:theme.heading_bold===false?400:700,fontStyle:theme.heading_italic?'italic':'normal',textDecoration:theme.heading_underline?'underline':'none',textTransform:(theme.heading_case==='normal'?'none':theme.heading_case||'none') as any};const bodyStyle:React.CSSProperties={fontFamily:`${bodyFont}, sans-serif`,fontWeight:theme.body_bold?700:400,fontStyle:theme.body_italic?'italic':'normal',textDecoration:theme.body_underline?'underline':'none',textTransform:(theme.body_case==='normal'?'none':theme.body_case||'none') as any};const baseBackground=bgMode==='gradient'&&bgGradient?bgGradient:bg;const cssVars={'--catalog-primary':primary,'--catalog-secondary':secondary,'--catalog-bg':bg,'--catalog-text':textColor,'--catalog-radius':radius,'--catalog-bg-blur':`${blur}px`} as React.CSSProperties;

  return <main className={`public-v2 layout-${layout} ${isMenu?'menu-mode':'catalog-mode'} ${bgImage?'has-background-image':''}`} style={{...cssVars,...bodyStyle,background:baseBackground,color:textColor}}>
    {bgImage&&<div className="public-v2-bg-layer" aria-hidden="true" style={{backgroundImage:`linear-gradient(rgba(0,0,0,${overlay}),rgba(0,0,0,${overlay})),url("${bgImage}")`}}/>}
    <header className="public-v2-hero" style={data?.business?.cover_url?{backgroundImage:`linear-gradient(180deg,rgba(0,0,0,.08),rgba(0,0,0,.58)),url(${data.business.cover_url})`}:undefined}><div className="public-v2-brand" style={{textAlign:align as any,justifyContent:align==='center'?'center':align==='right'?'flex-end':'flex-start'}}>{showLogo&&data?.business?.logo_url&&<div className={`public-v2-logo ${logoShape}`}><img src={data.business.logo_url} alt={`Logo ${data?.business?.name||''}`}/></div>}<div><span className="public-v2-kicker">QATALINK</span>{showName&&<h1 style={headingStyle}>{data?.business?.name||data?.catalog?.title}</h1>}<p>{data?.business?.description||data?.catalog?.title}</p></div></div></header>
    {pages.length>1&&<nav className="public-v2-page-tabs">{pages.map((p:any)=><button key={p.id} className={activePage===p.id?'active':''} onClick={()=>choosePage(p.id)}>{p.title}</button>)}</nav>}{visibleCategories.length>1&&<nav className="public-v2-tabs">{visibleCategories.map((cat:any)=><button key={cat.id} className={activeCategory===cat.id?'active':''} onClick={()=>jump(cat.id)}>{cat.name}</button>)}</nav>}
    <div className="public-v2-inner"><div className="public-v2-title"><div><span className="public-v2-kicker">{pages.length>1?(pages.find((p:any)=>p.id===activePage)?.title||'PAGE'):(isMenu?'MENU':'CATALOGUE')}</span><h2 style={headingStyle}>{data?.catalog?.title}</h2></div>{interactive&&<button className="public-v2-cart-count" onClick={()=>setCartOpen(true)}><ShoppingBag size={17}/>{itemCount}</button>}</div>{visibleCategories.map((cat:any)=><section id={`cat-${cat.id}`} className="public-v2-category" key={cat.id}><div className="public-v2-category-head"><h3 style={headingStyle}>{cat.name}</h3>{cat.description&&<p>{cat.description}</p>}</div><div className="public-v2-items">{(cat.items||[]).map((item:AnyItem)=>{const promo=promoActive(item),current=unit(item);return <article className={`public-v2-item ${item.image_url?'has-image':'no-image'}`} key={item.id}>{item.image_url&&<button className="public-v2-image-wrap" onClick={()=>setZoom({url:item.image_url!,name:item.name})}><img src={item.image_url} alt={item.name}/><span><ZoomIn size={17}/></span></button>}<div className="public-v2-copy"><div className="public-v2-name-price"><h4 style={headingStyle}>{item.name}</h4>{showPrices&&<div className="public-v2-price">{promo&&<del>{format(Number(item.price_minor||0))}</del>}<strong>{format(current)}</strong>{promo&&item.promo_ends_at&&<small>Promo jusqu’au {new Date(item.promo_ends_at).toLocaleDateString('fr-FR')}</small>}</div>}</div>{item.description&&<p>{item.description}</p>}</div>{interactive&&<div className="public-v2-qty">{(cart[item.id]||0)>0&&<><button onClick={()=>change(item.id,-1)}><Minus size={15}/></button><span>{cart[item.id]}</span></>}<button onClick={()=>change(item.id,1)}><Plus size={15}/></button></div>}</article>})}</div></section>)}</div>
    <div className="public-v2-whatsapp">{interactive&&selected.length?<button onClick={openFlow}>{showPrices?`Continuer · ${format(total)}`:'Continuer'}</button>:<a href={whatsapp} target="_blank" rel="noreferrer">Contacter sur WhatsApp</a>}</div>
    {cartOpen&&<div className="public-v2-cart-backdrop" onClick={()=>setCartOpen(false)}><section className="public-v2-cart" onClick={e=>e.stopPropagation()}><header><div><span className="public-v2-kicker">MON PANIER</span><h3 style={headingStyle}>{itemCount?`${itemCount} article${itemCount>1?'s':''}`:'Votre panier est vide'}</h3></div><button onClick={()=>setCartOpen(false)}><X/></button></header><div className="public-v2-cart-lines">{selected.length?selected.map((item:AnyItem)=>{const qty=cart[item.id]||0;return <div className="public-v2-cart-line" key={item.id}>{item.image_url&&<img src={item.image_url} alt=""/>}<div className="public-v2-cart-copy"><b>{item.name}</b><small>{showPrices?`${format(unit(item))} l’unité`:''}</small><div className="public-v2-cart-qty"><button onClick={()=>change(item.id,-1)}><Minus size={14}/></button><span>{qty}</span><button onClick={()=>change(item.id,1)}><Plus size={14}/></button></div></div><div className="public-v2-cart-side">{showPrices&&<strong>{format(unit(item)*qty)}</strong>}<button className="public-v2-remove" onClick={()=>remove(item.id)}><Trash2 size={15}/></button></div></div>}):<div className="public-v2-cart-empty"><ShoppingBag size={28}/><p>Ajoutez des articles depuis le catalogue pour les retrouver ici.</p></div>}</div>{selected.length>0&&<footer><div><span>Total</span>{showPrices&&<strong>{format(total)}</strong>}</div><button onClick={openFlow}>Continuer</button></footer>}</section></div>}
    {flowOpen&&<div className="public-v2-flow-backdrop" onClick={()=>setFlowOpen(false)}><section className="public-v2-flow" onClick={e=>e.stopPropagation()}><header><div><span className="public-v2-kicker">VOTRE DEMANDE</span><h3 style={headingStyle}>Comment souhaitez-vous continuer ?</h3></div><button onClick={()=>setFlowOpen(false)}><X/></button></header><div className="public-v2-flow-modes">{flowModes.map((m:string)=><button key={m} className={effectiveFlowMode===m?'active':''} onClick={()=>{setFlowMode(m);setFlowFields({})}}>{LABELS[m]||m}</button>)}</div><div className="public-v2-flow-fields">{needsTable&&<label>Numéro de table<input value={flowFields.table||''} onChange={e=>setFlowFields({...flowFields,table:e.target.value})} placeholder="Ex : 12"/></label>}{needsAddress&&<><label>Adresse de livraison<input value={flowFields.address||''} onChange={e=>setFlowFields({...flowFields,address:e.target.value})} placeholder="Adresse ou repère"/></label><label>Quartier / zone<input value={flowFields.area||''} onChange={e=>setFlowFields({...flowFields,area:e.target.value})} placeholder="Ex : Cocody, Marcory…"/></label></>}{needsHotel&&<><label>Date d’arrivée<input type="date" value={flowFields.arrival||''} onChange={e=>setFlowFields({...flowFields,arrival:e.target.value})}/></label><label>Date de départ<input type="date" value={flowFields.departure||''} onChange={e=>setFlowFields({...flowFields,departure:e.target.value})}/></label><label>Nombre de personnes<input type="number" min="1" value={flowFields.guests||''} onChange={e=>setFlowFields({...flowFields,guests:e.target.value})}/></label></>}{needsSlot&&<><label>Date souhaitée<input type="date" value={flowFields.date||''} onChange={e=>setFlowFields({...flowFields,date:e.target.value})}/></label><label>Heure souhaitée<input type="time" value={flowFields.time||''} onChange={e=>setFlowFields({...flowFields,time:e.target.value})}/></label></>}<label>Précision facultative<textarea value={flowFields.note||''} onChange={e=>setFlowFields({...flowFields,note:e.target.value})} placeholder="Ajoutez une précision si nécessaire"/></label>{effectiveFlowMode==='deposit'&&showPrices&&<div className="public-v2-deposit"><span>Acompte indicatif</span><strong>{format(Math.round(total*Math.max(1,Math.min(100,Number(flowSettings.deposit_percent||10)))/100))}</strong><small>Le règlement est confirmé avec l’entreprise.</small></div>}</div><a className={!flowValid?'disabled':''} href={flowValid?whatsapp:undefined} target="_blank" rel="noreferrer" aria-disabled={!flowValid}>Continuer sur WhatsApp</a></section></div>}
    {zoom&&<div className="public-v2-lightbox" onClick={()=>setZoom(null)}><button onClick={()=>setZoom(null)}><X/></button><img src={zoom.url} alt={zoom.name}/><strong>{zoom.name}</strong></div>}
  </main>;
}
