'use client';

import {useEffect,useState} from 'react';
import {createPortal} from 'react-dom';
import {Copy,ExternalLink,MapPin,Share2} from 'lucide-react';

type GpsPoint={lat:number;lng:number;accuracy:number;capturedAt:string};
type Anchor={left:number;top:number;width:number}|null;

function deliverySelected(){const active=document.querySelector<HTMLElement>('.public-v2-flow-modes button.active');return !!active&&/livraison/i.test(active.textContent||'')}
function findFieldInput(kind:'phone'|'address'){const labels=[...document.querySelectorAll<HTMLLabelElement>('.public-v2-flow-fields label')];const rx=kind==='phone'?/téléphone|telephone/i:/adresse/i;const label=labels.find(row=>rx.test(row.textContent||''));return label?.querySelector<HTMLInputElement|HTMLTextAreaElement>('input,textarea')||null}
function setReactInputValue(input:HTMLInputElement|HTMLTextAreaElement,value:string){const proto=input instanceof HTMLTextAreaElement?HTMLTextAreaElement.prototype:HTMLInputElement.prototype;const setter=Object.getOwnPropertyDescriptor(proto,'value')?.set;if(setter)setter.call(input,value);else input.value=value;input.dispatchEvent(new Event('input',{bubbles:true}));input.dispatchEvent(new Event('change',{bubbles:true}))}
function gpsMapsUrl(point:GpsPoint){return `https://maps.google.com/?q=${point.lat.toFixed(6)},${point.lng.toFixed(6)}`}
function mergeAddressWithGps(current:string,point:GpsPoint){const clean=current.replace(/\s*[—|·]?\s*Position GPS exacte\s*:\s*https:\/\/maps\.google\.com\/\?q=[^\s]+/gi,'').replace(/^Position GPS exacte enregistrée$/i,'').trim();const gps=`Position GPS exacte : ${gpsMapsUrl(point)}`;return clean?`${clean} — ${gps}`:gps}
function withGpsInWhatsapp(url:string,point:GpsPoint){try{const parsed=new URL(url,location.origin);if(!/(^|\.)wa\.me$/i.test(parsed.hostname)&&!/(^|\.)whatsapp\.com$/i.test(parsed.hostname))return url;const text=parsed.searchParams.get('text')||'';const maps=gpsMapsUrl(point);if(text.includes(maps)||/Position GPS (exacte|client)/i.test(text)&&text.includes('maps.google.com'))return parsed.toString();parsed.searchParams.set('text',`${text}${text?'\n\n':''}📍 Position GPS client : ${maps}`);return parsed.toString()}catch{return url}}
function isIOS(){return /iPad|iPhone|iPod/.test(navigator.userAgent)||(navigator.platform==='MacIntel'&&navigator.maxTouchPoints>1)}
function isLikelyInApp(){const ua=navigator.userAgent;return /WhatsApp|Instagram|FBAN|FBAV|Messenger|Line\//i.test(ua)||isIOS()&&!/Safari\//i.test(ua)}
async function permissionState(){try{if(!navigator.permissions?.query)return'unknown';const result=await navigator.permissions.query({name:'geolocation' as PermissionName});return result.state}catch{return'unknown'}}

export function PublicDeliveryLocationCapture(){
  const [mounted,setMounted]=useState(false);const [deliveryActive,setDeliveryActive]=useState(false);const [point,setPoint]=useState<GpsPoint|null>(null);const [locating,setLocating]=useState(false);const [status,setStatus]=useState('');const [statusType,setStatusType]=useState<'idle'|'success'|'error'>('idle');const [anchor,setAnchor]=useState<Anchor>(null);const [recovery,setRecovery]=useState(false);const [copied,setCopied]=useState(false);
  useEffect(()=>{setMounted(true);return()=>setMounted(false)},[]);
  useEffect(()=>{if(!location.pathname.startsWith('/c/'))return;let frame=0;const sync=()=>{cancelAnimationFrame(frame);frame=requestAnimationFrame(()=>{const active=deliverySelected();setDeliveryActive(active);document.body.classList.toggle('q-gps-inline-active',active);if(!active){setAnchor(null);return}const input=findFieldInput('address');if(!input){setAnchor(null);return}const r=input.getBoundingClientRect();setAnchor({left:r.left,top:r.bottom+6,width:r.width})})};sync();const observer=new MutationObserver(sync);observer.observe(document.body,{subtree:true,childList:true,attributes:true,attributeFilter:['class']});document.addEventListener('click',sync,true);document.addEventListener('scroll',sync,true);window.addEventListener('resize',sync);return()=>{cancelAnimationFrame(frame);observer.disconnect();document.removeEventListener('click',sync,true);document.removeEventListener('scroll',sync,true);window.removeEventListener('resize',sync);document.body.classList.remove('q-gps-inline-active')}} ,[]);
  useEffect(()=>{if(!location.pathname.startsWith('/c/'))return;const originalFetch=window.fetch.bind(window);const originalOpen=window.open;window.fetch=(async(input:RequestInfo|URL,init?:RequestInit)=>{const url=typeof input==='string'?input:input instanceof URL?input.toString():input.url;if(url.includes('/api/orders/public')&&init?.method?.toUpperCase()==='POST'&&typeof init.body==='string'){try{const body=JSON.parse(init.body);if(String(body?.flow_mode||'')==='delivery'&&point){if(!body.flow_fields||typeof body.flow_fields!=='object')body.flow_fields={};body.flow_fields.gps_lat=String(point.lat);body.flow_fields.gps_lng=String(point.lng);body.flow_fields.gps_accuracy=String(point.accuracy);body.flow_fields.gps_captured_at=point.capturedAt;body.flow_fields.gps_maps_url=gpsMapsUrl(point);body.flow_fields.address=mergeAddressWithGps(String(body.flow_fields.address||''),point);init={...init,body:JSON.stringify(body)}}}catch{}}return originalFetch(input,init)}) as typeof window.fetch;window.open=(function(url?:string|URL,target?:string,features?:string){let next=url;if(point&&deliverySelected()&&typeof url==='string')next=withGpsInWhatsapp(url,point);return originalOpen.call(window,next as any,target,features)}) as typeof window.open;return()=>{window.fetch=originalFetch;window.open=originalOpen}},[point]);
  useEffect(()=>{if(!location.pathname.startsWith('/c/'))return;const clickGuard=(event:MouseEvent)=>{if(!deliverySelected())return;const target=event.target;if(!(target instanceof Element))return;const submit=target.closest('.public-v2-confirm-order');if(!submit)return;const phoneInput=findFieldInput('phone');const addressInput=findFieldInput('address');const missingPhone=!!phoneInput?.required&&!phoneInput.value.trim();const missingAddress=!!addressInput?.required&&!addressInput.value.trim();if(!missingPhone&&!missingAddress)return;event.preventDefault();event.stopImmediatePropagation();if(missingPhone&&missingAddress)alert('Renseignez les champs obligatoires : téléphone et adresse de livraison.');else if(missingPhone)alert('Le numéro de téléphone est obligatoire pour cette livraison.');else alert('L’adresse de livraison est obligatoire. Vous pouvez aussi utiliser votre position GPS exacte.')};document.addEventListener('click',clickGuard,true);return()=>document.removeEventListener('click',clickGuard,true)},[]);
  async function copyLink(){try{await navigator.clipboard.writeText(location.href);setCopied(true);setTimeout(()=>setCopied(false),1800)}catch{window.prompt('Copiez ce lien puis ouvrez-le dans Safari :',location.href)}}
  async function shareLink(){try{if(navigator.share){await navigator.share({title:'Qatalink',url:location.href});return}}catch{}await copyLink()}
  async function locate(){
    if(!navigator.geolocation){setStatus('La géolocalisation n’est pas disponible sur cet appareil.');setStatusType('error');setRecovery(isIOS());return}
    setLocating(true);setRecovery(false);setStatus('Demande de localisation à votre téléphone…');setStatusType('idle');
    const state=await permissionState();
    if(state==='denied'){setLocating(false);setRecovery(true);setStatus(isLikelyInApp()?'Ce navigateur intégré bloque déjà l’accès à la localisation. Ouvrez ce même lien dans Safari.':'La localisation est bloquée pour Qatalink sur cet iPhone. Réactivez-la dans les réglages du site puis réessayez.');setStatusType('error');return}
    navigator.geolocation.getCurrentPosition(pos=>{const next={lat:pos.coords.latitude,lng:pos.coords.longitude,accuracy:pos.coords.accuracy,capturedAt:new Date().toISOString()};setPoint(next);const address=findFieldInput('address');if(address)setReactInputValue(address,mergeAddressWithGps(address.value,next));setStatus(`Position enregistrée · précision ≈ ${Math.round(pos.coords.accuracy)} m · le lien GPS sera transmis dans la commande et dans WhatsApp`);setStatusType('success');setLocating(false);setRecovery(false)},err=>{const denied=err.code===1;setStatus(denied?(isLikelyInApp()?'L’iPhone n’a pas affiché la demande de localisation dans ce navigateur. Ouvrez le lien dans Safari pour autoriser le GPS.':'Accès à la localisation refusé. Dans Safari, ouvrez les réglages du site Qatalink et autorisez Localisation.'):err.code===3?'Le GPS met trop de temps à répondre. Réessayez dans une zone plus dégagée.':'Impossible de récupérer votre position. Vous pouvez saisir l’adresse manuellement.');setStatusType('error');setLocating(false);setRecovery(denied&&isIOS())},{enableHighAccuracy:true,maximumAge:0,timeout:18000});
  }
  if(!mounted||!deliveryActive||!anchor)return null;
  return createPortal(<><style>{`.q-gps-inline-active .public-v2-flow-fields label:has(input[placeholder="Adresse ou repère"]){margin-bottom:${recovery?'250px':'72px'}}.q-ios-gps-recovery{margin-top:8px;padding:12px;border-radius:14px;background:#fff7f7;border:1px solid #f0c9cf;display:grid;gap:8px;font-size:12px;line-height:1.45}.q-ios-gps-recovery b{font-size:13px}.q-ios-gps-actions{display:flex;gap:8px;flex-wrap:wrap}.q-ios-gps-actions button{border:1px solid #d9d9df;background:#fff;border-radius:10px;padding:8px 10px;font-weight:700;display:flex;align-items:center;gap:6px}`}</style><div className="q-delivery-gps-inline" style={{position:'fixed',left:anchor.left,top:anchor.top,width:anchor.width,zIndex:10001}}><button type="button" className="q-delivery-gps-button-inline" disabled={locating} onClick={()=>void locate()}><MapPin size={16}/><span>{locating?'Demande au téléphone…':point?'Actualiser ma position GPS':'Utiliser ma position GPS exacte'}</span></button>{status&&<small className={`q-delivery-gps-status-inline ${statusType}`}>{status}</small>}{recovery&&<div className="q-ios-gps-recovery"><b>Sur iPhone : ouvrez Qatalink dans Safari</b><span>Depuis WhatsApp/WA Business, utilisez le menu de la page pour « Ouvrir dans Safari ». Dans Safari, touchez à nouveau « Utiliser ma position GPS exacte », puis choisissez « Autoriser une fois » ou « Autoriser lors de l’utilisation » avec Localisation précise activée.</span><span>Si Safari a déjà été refusé : menu de page Safari → Réglages du site → Localisation → Autoriser, ou Réglages iPhone → Confidentialité et sécurité → Service de localisation → Sites web Safari.</span><div className="q-ios-gps-actions"><button type="button" onClick={()=>void shareLink()}><Share2 size={14}/>Partager le lien</button><button type="button" onClick={()=>void copyLink()}><Copy size={14}/>{copied?'Lien copié':'Copier le lien'}</button><button type="button" onClick={()=>location.reload()}><ExternalLink size={14}/>Réessayer ici</button></div></div>}</div></>,document.body);
}
