'use client';

import {useEffect,useMemo,useRef,useState} from 'react';
import {createPortal} from 'react-dom';
import {Download,FileImage,FileText,Loader2,Sparkles} from 'lucide-react';
import {QRCodeSVG} from 'qrcode.react';
import {createSupabaseBrowserClient} from '@/lib/supabase';

type CatalogInfo={id:string;business_id:string;title:string;public_slug:string;hub_public_slug:string|null;description:string|null;display_name:string|null;logo_url:string|null;catalog_type:string|null};
type BusinessInfo={name:string;description:string|null;business_type:string;logo_url:string|null};
type CatalogTheme={primary_color:string;secondary_color:string;background_color:string;text_color:string;heading_font:string;body_font:string;background_mode:string|null;background_gradient:string|null};
type RefItem={id:string;name:string;image_url:string};
type AssetType='flyer'|'tent_card'|'simple_card';
type Mode='auto'|'custom';
type QrMode='catalog'|'hub'|'both';
type FlyerFormat='png'|'jpeg';
type PrintFormat='a4'|'a5';

const PUBLIC_ORIGIN='https://qatalink.com';
const AUTO_COST=30;
const CUSTOM_COST=40;
const defaultTheme:CatalogTheme={primary_color:'#B5122B',secondary_color:'#F7E8EA',background_color:'#FFFFFF',text_color:'#171719',heading_font:'Plus Jakarta Sans',body_font:'Plus Jakarta Sans',background_mode:'solid',background_gradient:null};

function sleep(ms:number){return new Promise(resolve=>setTimeout(resolve,ms))}
function clean(value:unknown,max=600){return String(value??'').replace(/\s+/g,' ').trim().slice(0,max)}
function fallbackBio(type:string){if(type==='restaurant')return 'Découvrez notre carte, nos spécialités et nos offres du moment.';if(type==='hotel')return 'Découvrez nos chambres, services et expériences.';if(type==='spa_beauty')return 'Découvrez nos prestations, nos tarifs et notre univers.';if(type==='real_estate')return 'Découvrez nos biens et opportunités disponibles.';return 'Découvrez notre sélection, nos services et nos offres.'}
function ctaFor(type:string){if(type==='restaurant')return 'Scannez, découvrez la carte et commandez';if(type==='hotel')return 'Scannez pour découvrir chambres et services';if(type==='spa_beauty')return 'Scannez pour découvrir prestations et tarifs';if(type==='real_estate')return 'Scannez pour découvrir les biens disponibles';return 'Scannez pour découvrir nos offres'}
function catalogTypeLabel(value:unknown){const raw=clean(value,40).toLowerCase();if(raw==='menu')return'Menu';if(raw==='catalog'||raw==='catalogue')return'Catalogue';if(raw==='services'||raw==='service')return'Services';if(raw==='rooms'||raw==='chambres')return'Chambres';return raw?raw.charAt(0).toUpperCase()+raw.slice(1):'Catalogue'}
function wrapLines(ctx:CanvasRenderingContext2D,text:string,maxWidth:number,maxLines:number){const words=text.split(/\s+/).filter(Boolean);const lines:string[]=[];let line='';for(const word of words){const next=line?`${line} ${word}`:word;if(ctx.measureText(next).width<=maxWidth){line=next;continue}if(line)lines.push(line);line=word;if(lines.length>=maxLines-1)break}if(line&&lines.length<maxLines)lines.push(line);if(lines.length===maxLines){while(ctx.measureText(lines[maxLines-1]+'…').width>maxWidth&&lines[maxLines-1].length>2)lines[maxLines-1]=lines[maxLines-1].slice(0,-2);lines[maxLines-1]=lines[maxLines-1].replace(/[,. ]+$/,'')+'…'}return lines}
function loadImage(src:string){return new Promise<HTMLImageElement>((resolve,reject)=>{const img=new Image();img.crossOrigin='anonymous';img.onload=()=>resolve(img);img.onerror=reject;img.src=src})}
function svgImage(svg:SVGSVGElement){return new Promise<HTMLImageElement>((resolve,reject)=>{const xml=new XMLSerializer().serializeToString(svg);const img=new Image();img.onload=()=>resolve(img);img.onerror=reject;img.src='data:image/svg+xml;charset=utf-8,'+encodeURIComponent(xml)})}
function drawCover(ctx:CanvasRenderingContext2D,img:CanvasImageSource&{width:number;height:number},x:number,y:number,w:number,h:number){const scale=Math.max(w/img.width,h/img.height);const dw=img.width*scale,dh=img.height*scale;ctx.drawImage(img,x+(w-dw)/2,y+(h-dh)/2,dw,dh)}
function ascii(value:string){return new TextEncoder().encode(value)}
function concat(parts:Uint8Array[]){const size=parts.reduce((sum,p)=>sum+p.length,0);const out=new Uint8Array(size);let offset=0;for(const p of parts){out.set(p,offset);offset+=p.length}return out}
function dataUrlBytes(url:string){const b64=url.split(',')[1]||'';const bin=atob(b64);const out=new Uint8Array(bin.length);for(let i=0;i<bin.length;i++)out[i]=bin.charCodeAt(i);return out}
function safeHex(value:string,fallback:string){return /^#[0-9a-f]{6}$/i.test(value||'')?value:fallback}
function rgb(hex:string){const h=safeHex(hex,'#ffffff').slice(1);return [parseInt(h.slice(0,2),16),parseInt(h.slice(2,4),16),parseInt(h.slice(4,6),16)]}
function luminance(hex:string){const [r,g,b]=rgb(hex).map(v=>{const n=v/255;return n<=.03928?n/12.92:Math.pow((n+.055)/1.055,2.4)});return .2126*r+.7152*g+.0722*b}
function contrast(a:string,b:string){const l1=luminance(a),l2=luminance(b);return (Math.max(l1,l2)+.05)/(Math.min(l1,l2)+.05)}
function readableText(bg:string,preferred:string){const p=safeHex(preferred,'#171719');if(contrast(bg,p)>=4.5)return p;return contrast(bg,'#ffffff')>=contrast(bg,'#111111')?'#ffffff':'#111111'}

function canvasesPdf(canvases:HTMLCanvasElement[],page:'a4'|'a5'){
  const pw=page==='a4'?595.28:419.53,ph=page==='a4'?841.89:595.28;
  const n=canvases.length;const parts:Uint8Array[]=[];const offsets:number[]=[0];let length=0;
  const push=(part:Uint8Array)=>{parts.push(part);length+=part.length};
  const obj=(id:number,body:string|Uint8Array)=>{offsets[id]=length;push(ascii(`${id} 0 obj\n`));push(typeof body==='string'?ascii(body):body);push(ascii('\nendobj\n'))};
  push(ascii('%PDF-1.4\n%QATALINK\n'));
  obj(1,'<< /Type /Catalog /Pages 2 0 R >>');
  obj(2,`<< /Type /Pages /Kids [${canvases.map((_,i)=>`${3+i} 0 R`).join(' ')}] /Count ${n} >>`);
  canvases.forEach((canvas,i)=>{const pageId=3+i,imgId=3+n+i,contentId=3+2*n+i;obj(pageId,`<< /Type /Page /Parent 2 0 R /MediaBox [0 0 ${pw} ${ph}] /Resources << /XObject << /Im0 ${imgId} 0 R >> >> /Contents ${contentId} 0 R >>`)});
  canvases.forEach((canvas,i)=>{const jpg=dataUrlBytes(canvas.toDataURL('image/jpeg',.96));const imgId=3+n+i;offsets[imgId]=length;push(ascii(`${imgId} 0 obj\n<< /Type /XObject /Subtype /Image /Width ${canvas.width} /Height ${canvas.height} /ColorSpace /DeviceRGB /BitsPerComponent 8 /Filter /DCTDecode /Length ${jpg.length} >>\nstream\n`));push(jpg);push(ascii('\nendstream\nendobj\n'))});
  canvases.forEach((_,i)=>{const contentId=3+2*n+i;const stream=`q\n${pw} 0 0 ${ph} 0 0 cm\n/Im0 Do\nQ`;obj(contentId,`<< /Length ${stream.length} >>\nstream\n${stream}\nendstream`)});
  const total=2+3*n,xref=length;push(ascii(`xref\n0 ${total+1}\n0000000000 65535 f \n`));for(let i=1;i<=total;i++)push(ascii(String(offsets[i]).padStart(10,'0')+' 00000 n \n'));push(ascii(`trailer\n<< /Size ${total+1} /Root 1 0 R >>\nstartxref\n${xref}\n%%EOF`));return new Blob([concat(parts) as unknown as BlobPart],{type:'application/pdf'});
}
function downloadBlob(blob:Blob,name:string){const url=URL.createObjectURL(blob);const a=document.createElement('a');a.href=url;a.download=name;document.body.appendChild(a);a.click();a.remove();setTimeout(()=>URL.revokeObjectURL(url),5000)}

export function QrMarketingAssets(){
  const supabase=useMemo(()=>createSupabaseBrowserClient(),[]);
  const activeCatalogRef=useRef('');
  const [host,setHost]=useState<Element|null>(null);const [catalog,setCatalog]=useState<CatalogInfo|null>(null);const [business,setBusiness]=useState<BusinessInfo|null>(null);const [theme,setTheme]=useState<CatalogTheme>(defaultTheme);const [session,setSession]=useState<any>(null);const [wallet,setWallet]=useState(0);const [refs,setRefs]=useState<RefItem[]>([]);
  const [assetType,setAssetType]=useState<AssetType>('flyer');const [mode,setMode]=useState<Mode>('auto');const [qrMode,setQrMode]=useState<QrMode>('catalog');const [flyerFormat,setFlyerFormat]=useState<FlyerFormat>('png');const [printFormat,setPrintFormat]=useState<PrintFormat>('a4');const [customPrompt,setCustomPrompt]=useState('');const [selected,setSelected]=useState<string[]>([]);
  const [busy,setBusy]=useState(false);const [progress,setProgress]=useState('');const [error,setError]=useState('');const [baseImage,setBaseImage]=useState('');const [jobId,setJobId]=useState('');const [lastCost,setLastCost]=useState(0);const previewRef=useRef<HTMLCanvasElement|null>(null);
  const catalogUrl=catalog?`${PUBLIC_ORIGIN}/c/${catalog.public_slug}`:'';const hubUrl=catalog?.hub_public_slug?`${PUBLIC_ORIGIN}/h/${catalog.hub_public_slug}`:'';const cost=mode==='custom'?CUSTOM_COST:AUTO_COST;

  useEffect(()=>{
    let cancelled=false;
    async function loadCatalog(catalogId:string){
      if(!catalogId||catalogId===activeCatalogRef.current)return;activeCatalogRef.current=catalogId;
      const {data:{session:s}}=await supabase.auth.getSession();if(cancelled||!s)return;setSession(s);
      const {data:c}=await supabase.from('catalogs').select('id,business_id,title,public_slug,hub_public_slug,description,display_name,logo_url,catalog_type').eq('id',catalogId).maybeSingle();if(cancelled||!c)return;
      const [{data:b},{data:w},{data:items},{data:t},{data:lastJob}]=await Promise.all([
        supabase.from('businesses').select('name,description,business_type,logo_url').eq('id',c.business_id).maybeSingle(),
        supabase.from('credit_wallets').select('balance').eq('business_id',c.business_id).maybeSingle(),
        supabase.from('items').select('id,name').eq('catalog_id',catalogId).eq('is_available',true).order('sort_order'),
        supabase.from('catalog_theme_settings').select('primary_color,secondary_color,background_color,text_color,heading_font,body_font,background_mode,background_gradient').eq('catalog_id',catalogId).maybeSingle(),
        supabase.from('marketing_asset_generation_jobs').select('id,result_image_url,credit_cost').eq('catalog_id',catalogId).eq('status','completed').not('result_image_url','is',null).order('completed_at',{ascending:false}).limit(1).maybeSingle()
      ]);if(cancelled)return;
      setCatalog(c as CatalogInfo);setBusiness(b as BusinessInfo|null);setTheme({...defaultTheme,...(t||{})} as CatalogTheme);setWallet(Number(w?.balance||0));
      const ids=(items||[]).map((item:any)=>item.id);if(ids.length){const {data:images}=await supabase.from('item_images').select('item_id,image_url,is_primary,created_at').in('item_id',ids).order('is_primary',{ascending:false}).order('created_at',{ascending:false});const imageMap=new Map<string,string>();for(const image of images||[])if(image.image_url&&!imageMap.has(String(image.item_id)))imageMap.set(String(image.item_id),String(image.image_url));setRefs((items||[]).filter((item:any)=>imageMap.has(String(item.id))).map((item:any)=>({id:String(item.id),name:String(item.name),image_url:imageMap.get(String(item.id))!})).slice(0,60))}else setRefs([]);
      setSelected([]);setError('');setProgress('');setBaseImage(String(lastJob?.result_image_url||''));setJobId(String(lastJob?.id||''));setLastCost(Number(lastJob?.credit_cost||0));
    }
    const resolve=async()=>{const title=document.querySelector('.dash-v3-top h1')?.textContent?.trim()||'';const wrap=document.querySelector('.qr-v3-wrap');if(title!=='QR & partage'||!wrap){setHost(null);return}setHost(wrap);const params=new URLSearchParams(window.location.search);let id=params.get('catalog')||'';if(!id){const src=(wrap.querySelector('.qr-v3-card img') as HTMLImageElement|null)?.getAttribute('src')||'';const match=src.match(/\/api\/qr\/([^?]+)/);if(match){const {data}=await supabase.from('catalogs').select('id').eq('public_slug',decodeURIComponent(match[1])).maybeSingle();id=String(data?.id||'')}}if(id)await loadCatalog(id)};
    void resolve();const interval=setInterval(()=>void resolve(),2200);const onChange=()=>{activeCatalogRef.current='';void resolve()};window.addEventListener('popstate',onChange);window.addEventListener('qatalink:catalog-change',onChange as EventListener);return()=>{cancelled=true;clearInterval(interval);window.removeEventListener('popstate',onChange);window.removeEventListener('qatalink:catalog-change',onChange as EventListener)};
  },[supabase]);

  function toggleRef(id:string){setSelected(current=>current.includes(id)?current.filter(value=>value!==id):current.length<6?[...current,id]:current)}
  async function generate(){if(!catalog||!session||busy)return;if(wallet<cost){setError(`Solde insuffisant : ${cost} crédits requis, ${wallet} disponibles.`);return}if(mode==='custom'&&!customPrompt.trim()){setError('Ajoutez une direction créative pour le mode personnalisé.');return}setBusy(true);setError('');setProgress('Préparation du support…');try{const response=await fetch('/api/marketing-assets/generate',{method:'POST',headers:{'Content-Type':'application/json',Authorization:`Bearer ${session.access_token}`},body:JSON.stringify({catalog_id:catalog.id,asset_type:assetType,generation_mode:mode,qr_mode:qrMode,custom_prompt:customPrompt,reference_item_ids:selected})});const data=await response.json().catch(()=>({}));if(!response.ok)throw new Error(data.message||data.error||'Impossible de lancer la génération.');setWallet(Number(data.balance??wallet-cost));setLastCost(Number(data.credit_cost||cost));setJobId(String(data.job_id||''));setProgress('Création du design…');for(let attempt=0;attempt<75;attempt++){await sleep(2200);const statusResponse=await fetch('/api/marketing-assets/status',{method:'POST',headers:{'Content-Type':'application/json',Authorization:`Bearer ${session.access_token}`},body:JSON.stringify({job_id:data.job_id})});const statusData=await statusResponse.json().catch(()=>({}));if(statusData.status==='completed'&&statusData.image_url){setBaseImage(String(statusData.image_url));setProgress('Support prêt.');return}if(statusData.status==='failed'||(!statusResponse.ok&&statusResponse.status===409)){if(statusData.balance!==undefined)setWallet(Number(statusData.balance));throw new Error('La génération a échoué. Les crédits ont été recrédités.')}setProgress(statusData.progress?`Création du design… ${Math.round(Number(statusData.progress))}%`:'Création du design…')}throw new Error('La génération prend plus de temps que prévu. Elle reste enregistrée et réapparaîtra automatiquement dès qu’elle sera terminée.')}catch(e:any){setError(e?.message||'Impossible de générer le support.');setProgress('')}finally{setBusy(false)}}

  async function compose(width=1080,height=1350){
    if(!baseImage||!catalog||!business)return null;const canvas=document.createElement('canvas');canvas.width=width;canvas.height=height;const ctx=canvas.getContext('2d');if(!ctx)return null;const unit=Math.min(width,height);const primary=safeHex(theme.primary_color,'#B5122B'),secondary=safeHex(theme.secondary_color,'#F7E8EA'),surface=safeHex(theme.background_color,'#FFFFFF'),text=readableText(surface,theme.text_color),muted=contrast(surface,'#666666')>=3?'#666666':text;const imageH=Math.round(height*.43);const bg=await loadImage(baseImage);drawCover(ctx,bg,0,0,width,imageH);
    const shade=ctx.createLinearGradient(0,0,0,imageH*.72);shade.addColorStop(0,'rgba(0,0,0,.70)');shade.addColorStop(1,'rgba(0,0,0,.04)');ctx.fillStyle=shade;ctx.fillRect(0,0,width,imageH*.78);ctx.textAlign='center';ctx.fillStyle='#fff';ctx.font=`800 ${Math.round(unit*.061)}px "${theme.heading_font||'Plus Jakarta Sans'}",Arial,sans-serif`;ctx.fillText(clean(catalog.display_name||business.name,50),width/2,imageH*.20);ctx.fillStyle='rgba(255,255,255,.94)';ctx.font=`600 ${Math.round(unit*.024)}px "${theme.body_font||'Plus Jakarta Sans'}",Arial,sans-serif`;ctx.fillText(clean(catalog.title,70),width/2,imageH*.29);
    const panelY=imageH,panelH=height-panelY;ctx.fillStyle=surface;ctx.fillRect(0,panelY,width,panelH);ctx.fillStyle=secondary;ctx.fillRect(0,panelY,width,Math.max(8,Math.round(unit*.012)));ctx.fillStyle=text;ctx.font=`800 ${Math.round(unit*.034)}px "${theme.heading_font||'Plus Jakarta Sans'}",Arial,sans-serif`;ctx.fillText(ctaFor(business.business_type),width/2,panelY+panelH*.105);
    const bio=clean(catalog.description||business.description||fallbackBio(business.business_type),380);ctx.fillStyle=muted;ctx.font=`500 ${Math.round(unit*.019)}px "${theme.body_font||'Plus Jakarta Sans'}",Arial,sans-serif`;wrapLines(ctx,bio,width*.82,2).forEach((line,index)=>ctx.fillText(line,width/2,panelY+panelH*.18+index*Math.round(unit*.026)));
    const directLabel=catalogTypeLabel(catalog.catalog_type);const targets:{url:string;label:string;kind:'catalog'|'hub'}[]=[];if(qrMode==='catalog'||qrMode==='both')targets.push({url:catalogUrl,label:directLabel,kind:'catalog'});if((qrMode==='hub'||qrMode==='both')&&hubUrl)targets.push({url:hubUrl,label:'Page centrale',kind:'hub'});
    const qrSize=targets.length===2?Math.round(unit*.235):Math.round(unit*.34),gap=Math.round(unit*.085),total=targets.length*qrSize+(targets.length-1)*gap;let x=(width-total)/2;const qrY=panelY+panelH*.285;
    for(const target of targets){const svg=document.querySelector(`.qr-hidden-codes [data-qr-kind="${target.kind}"] svg`) as SVGSVGElement|null;if(svg){const image=await svgImage(svg);const frame=Math.round(unit*.022),pad=Math.round(unit*.014);ctx.fillStyle=primary;ctx.fillRect(x-frame-pad,qrY-frame-pad,qrSize+(frame+pad)*2,qrSize+(frame+pad)*2);ctx.fillStyle='#fff';ctx.fillRect(x-pad,qrY-pad,qrSize+pad*2,qrSize+pad*2);ctx.drawImage(image,x,qrY,qrSize,qrSize)}ctx.fillStyle=text;ctx.font=`800 ${Math.round(unit*.018)}px "${theme.heading_font||'Plus Jakarta Sans'}",Arial,sans-serif`;ctx.fillText(target.label,x+qrSize/2,qrY+qrSize+Math.round(unit*.034));x+=qrSize+gap}
    ctx.fillStyle=primary;ctx.font=`800 ${Math.round(unit*.014)}px "${theme.body_font||'Plus Jakarta Sans'}",Arial,sans-serif`;ctx.fillText('Propulsé par Qatalink',width/2,height-Math.round(unit*.023));return canvas;
  }

  async function refreshPreview(){try{const composed=await compose();if(!composed||!previewRef.current)return;previewRef.current.width=composed.width;previewRef.current.height=composed.height;previewRef.current.getContext('2d')?.drawImage(composed,0,0)}catch{}}
  useEffect(()=>{if(baseImage)void refreshPreview()},[baseImage,qrMode,catalog,business,theme]);
  async function downloadFlyer(){const composed=await compose();if(!composed)return;const mime=flyerFormat==='png'?'image/png':'image/jpeg';composed.toBlob(blob=>{if(blob)downloadBlob(blob,`qatalink-${catalog?.public_slug||'flyer'}.${flyerFormat==='jpeg'?'jpg':'png'}`)},mime,flyerFormat==='jpeg'?.94:undefined)}
  async function createPrintPage(){const width=printFormat==='a4'?1754:1240,height=printFormat==='a4'?2480:1754;return compose(width,height)}
  async function downloadSimpleCard(){const page=await createPrintPage();if(!page)return;downloadBlob(canvasesPdf([page],printFormat),`qatalink-carte-${catalog?.public_slug||'catalogue'}-${printFormat.toUpperCase()}.pdf`)}
  async function downloadTent(){const normal=await createPrintPage();if(!normal)return;const rotated=document.createElement('canvas');rotated.width=normal.width;rotated.height=normal.height;const rctx=rotated.getContext('2d');if(!rctx)return;rctx.fillStyle='#fff';rctx.fillRect(0,0,rotated.width,rotated.height);rctx.translate(rotated.width,rotated.height);rctx.rotate(Math.PI);rctx.drawImage(normal,0,0);downloadBlob(canvasesPdf([normal,rotated],printFormat),`qatalink-menu-catalogue-chevalet-${catalog?.public_slug||'catalogue'}-${printFormat.toUpperCase()}.pdf`)}

  if(!host||!catalog||!business)return null;
  return createPortal(<section className="dash-card qr-marketing-studio">
    <div className="qr-marketing-head"><div><div className="eyebrow">STUDIO QR · V1</div><h2>Créer le design imprimable de votre carte à scanner</h2><p>Flyer, menu/catalogue chevalet ou carte simple avec vos vrais QR actifs. Le design reprend automatiquement la palette du catalogue sélectionné.</p></div><div className="qr-credit-pill"><b>{wallet>=100000000?'∞':wallet}</b><span>crédits</span></div></div>
    <div className="qr-marketing-grid"><div className="qr-marketing-controls">
      <div className="qr-choice-row"><button className={assetType==='flyer'?'active':''} onClick={()=>setAssetType('flyer')}><FileImage size={17}/>Flyer</button><button className={assetType==='tent_card'?'active':''} onClick={()=>setAssetType('tent_card')}><FileText size={17}/>Menu/catalogue chevalet</button><button className={assetType==='simple_card'?'active':''} onClick={()=>setAssetType('simple_card')}><FileText size={17}/>Carte simple</button></div>
      <div className="field"><label>Mode de création</label><select className="input" value={mode} onChange={event=>setMode(event.target.value as Mode)}><option value="auto">Automatique · {AUTO_COST} crédits</option><option value="custom">Personnalisé · {CUSTOM_COST} crédits</option></select></div>
      <div className="field"><label>QR à afficher</label><select className="input" value={qrMode} onChange={event=>setQrMode(event.target.value as QrMode)}><option value="catalog">{catalogTypeLabel(catalog.catalog_type)} direct</option>{hubUrl&&<option value="hub">Page centrale</option>}{hubUrl&&<option value="both">Les deux QR</option>}</select></div>
      {assetType==='flyer'?<div className="field"><label>Format de téléchargement</label><select className="input" value={flyerFormat} onChange={event=>setFlyerFormat(event.target.value as FlyerFormat)}><option value="png">PNG</option><option value="jpeg">JPEG</option></select></div>:<div className="field"><label>Format d’impression</label><select className="input" value={printFormat} onChange={event=>setPrintFormat(event.target.value as PrintFormat)}><option value="a4">PDF A4</option><option value="a5">PDF A5</option></select></div>}
      {mode==='custom'&&<><div className="field"><label>Direction créative</label><textarea className="input" rows={4} value={customPrompt} onChange={event=>setCustomPrompt(event.target.value)} placeholder="Ex. ambiance lounge élégante, priorité aux grillades…"/></div><div className="field"><label>Références · {selected.length}/6</label><div className="qr-reference-grid">{refs.slice(0,24).map(ref=><button key={ref.id} className={selected.includes(ref.id)?'selected':''} onClick={()=>toggleRef(ref.id)} title={ref.name}><img src={ref.image_url} alt=""/><span>{ref.name}</span></button>)}</div></div></>}
      <button className="btn btn-primary qr-generate-btn" onClick={generate} disabled={busy||wallet<cost}>{busy?<Loader2 className="spin" size={17}/>:<Sparkles size={17}/>}Générer · {cost} crédits</button>{wallet<cost&&<small className="qr-credit-warning">Il vous manque {cost-wallet} crédits.</small>}{progress&&<div className="qr-progress">{progress}</div>}{error&&<div className="qr-error">{error}</div>}
    </div><div className="qr-marketing-preview">{baseImage?<><canvas ref={previewRef}/><div className="qr-download-row">{assetType==='flyer'?<button className="btn btn-primary" onClick={downloadFlyer}><Download size={16}/>Télécharger {flyerFormat.toUpperCase()}</button>:assetType==='tent_card'?<button className="btn btn-primary" onClick={downloadTent}><Download size={16}/>Télécharger PDF {printFormat.toUpperCase()} · 2 pages</button>:<button className="btn btn-primary" onClick={downloadSimpleCard}><Download size={16}/>Télécharger PDF {printFormat.toUpperCase()}</button>}<button className="btn btn-ghost" onClick={generate}><Sparkles size={15}/>Créer une variante · {cost}</button></div><small>Le QR est ajouté après la génération du visuel, reste scannable et encode exactement le lien actif. Les créations terminées sont conservées et rechargées depuis votre historique.</small></>:<div className="qr-empty-preview"><Sparkles size={34}/><b>Votre support apparaîtra ici</b><span>Palette du catalogue · QR agrandi · CTA rapproché · composition symétrique</span></div>}</div></div>
    <div className="qr-hidden-codes" aria-hidden="true"><div data-qr-kind="catalog"><QRCodeSVG value={catalogUrl} size={520} level="M" marginSize={4}/></div>{hubUrl&&<div data-qr-kind="hub"><QRCodeSVG value={hubUrl} size={520} level="M" marginSize={4}/></div>}</div>{jobId&&lastCost>0&&<div className="qr-job-note">Dernière création : {lastCost} crédits · génération #{jobId.slice(0,8)}</div>}
  </section>,host);
}
