'use client';

import {useEffect,useMemo,useRef,useState} from 'react';
import {createPortal} from 'react-dom';
import {Download,FileImage,FileText,Loader2,Sparkles} from 'lucide-react';
import {QRCodeSVG} from 'qrcode.react';
import {createSupabaseBrowserClient} from '@/lib/supabase';

type CatalogInfo={id:string;business_id:string;title:string;public_slug:string;hub_public_slug:string|null;description:string|null;display_name:string|null;logo_url:string|null};
type BusinessInfo={name:string;description:string|null;business_type:string;logo_url:string|null};
type RefItem={id:string;name:string;image_url:string};
type AssetType='flyer'|'tent_card';type Mode='auto'|'custom';type QrMode='catalog'|'hub'|'both';type FlyerFormat='png'|'jpeg';type TentFormat='a4'|'a5';

const PUBLIC_ORIGIN='https://qatalink.com';
const AUTO_COST=30;const CUSTOM_COST=40;
function sleep(ms:number){return new Promise(r=>setTimeout(r,ms))}
function clean(v:unknown,max=600){return String(v??'').replace(/\s+/g,' ').trim().slice(0,max)}
function wrapLines(ctx:CanvasRenderingContext2D,text:string,maxWidth:number,maxLines:number){const words=text.split(/\s+/).filter(Boolean);const lines:string[]=[];let line='';for(const word of words){const next=line?`${line} ${word}`:word;if(ctx.measureText(next).width<=maxWidth){line=next;continue}if(line)lines.push(line);line=word;if(lines.length>=maxLines-1)break}if(line&&lines.length<maxLines)lines.push(line);if(words.length&&lines.length===maxLines){while(ctx.measureText(lines[maxLines-1]+'…').width>maxWidth&&lines[maxLines-1].length>2)lines[maxLines-1]=lines[maxLines-1].slice(0,-2);lines[maxLines-1]=lines[maxLines-1].replace(/[,. ]+$/,'')+'…'}return lines}
function loadImage(src:string){return new Promise<HTMLImageElement>((resolve,reject)=>{const img=new Image();img.crossOrigin='anonymous';img.onload=()=>resolve(img);img.onerror=reject;img.src=src})}
function svgImage(svg:SVGSVGElement){return new Promise<HTMLImageElement>((resolve,reject)=>{const xml=new XMLSerializer().serializeToString(svg);const img=new Image();img.onload=()=>resolve(img);img.onerror=reject;img.src='data:image/svg+xml;charset=utf-8,'+encodeURIComponent(xml)})}
function drawCover(ctx:CanvasRenderingContext2D,img:HTMLImageElement,x:number,y:number,w:number,h:number){const scale=Math.max(w/img.width,h/img.height);const dw=img.width*scale,dh=img.height*scale;ctx.drawImage(img,x+(w-dw)/2,y+(h-dh)/2,dw,dh)}
function ascii(s:string){return new TextEncoder().encode(s)}
function concat(parts:Uint8Array[]){const n=parts.reduce((a,b)=>a+b.length,0);const out=new Uint8Array(n);let o=0;for(const p of parts){out.set(p,o);o+=p.length}return out}
function dataUrlBytes(url:string){const b64=url.split(',')[1]||'';const bin=atob(b64);const out=new Uint8Array(bin.length);for(let i=0;i<bin.length;i++)out[i]=bin.charCodeAt(i);return out}
function canvasPdf(canvas:HTMLCanvasElement,page:'a4'|'a5'){
  const jpg=dataUrlBytes(canvas.toDataURL('image/jpeg',.94));const pw=page==='a4'?841.89:595.28,ph=page==='a4'?595.28:419.53;
  const parts:Uint8Array[]=[];const offsets:number[]=[0];let len=0;const push=(p:Uint8Array)=>{parts.push(p);len+=p.length};const obj=(id:number,body:string|Uint8Array)=>{offsets[id]=len;push(ascii(`${id} 0 obj\n`));push(typeof body==='string'?ascii(body):body);push(ascii('\nendobj\n'))};
  push(ascii('%PDF-1.4\n%QATALINK\n'));
  obj(1,'<< /Type /Catalog /Pages 2 0 R >>');obj(2,'<< /Type /Pages /Kids [3 0 R] /Count 1 >>');
  obj(3,`<< /Type /Page /Parent 2 0 R /MediaBox [0 0 ${pw} ${ph}] /Resources << /XObject << /Im0 4 0 R >> >> /Contents 5 0 R >>`);
  offsets[4]=len;push(ascii(`4 0 obj\n<< /Type /XObject /Subtype /Image /Width ${canvas.width} /Height ${canvas.height} /ColorSpace /DeviceRGB /BitsPerComponent 8 /Filter /DCTDecode /Length ${jpg.length} >>\nstream\n`));push(jpg);push(ascii('\nendstream\nendobj\n'));
  const stream=`q\n${pw} 0 0 ${ph} 0 0 cm\n/Im0 Do\nQ`;obj(5,`<< /Length ${stream.length} >>\nstream\n${stream}\nendstream`);
  const xref=len;push(ascii(`xref\n0 6\n0000000000 65535 f \n`));for(let i=1;i<=5;i++)push(ascii(String(offsets[i]).padStart(10,'0')+' 00000 n \n'));push(ascii(`trailer\n<< /Size 6 /Root 1 0 R >>\nstartxref\n${xref}\n%%EOF`));return new Blob([concat(parts)],{type:'application/pdf'});
}
function downloadBlob(blob:Blob,name:string){const url=URL.createObjectURL(blob);const a=document.createElement('a');a.href=url;a.download=name;document.body.appendChild(a);a.click();a.remove();setTimeout(()=>URL.revokeObjectURL(url),1500)}

export function QrMarketingAssets(){
  const supabase=useMemo(()=>createSupabaseBrowserClient(),[]);const [host,setHost]=useState<Element|null>(null);const [catalog,setCatalog]=useState<CatalogInfo|null>(null);const [business,setBusiness]=useState<BusinessInfo|null>(null);const [session,setSession]=useState<any>(null);const [wallet,setWallet]=useState(0);const [refs,setRefs]=useState<RefItem[]>([]);
  const [assetType,setAssetType]=useState<AssetType>('flyer');const [mode,setMode]=useState<Mode>('auto');const [qrMode,setQrMode]=useState<QrMode>('catalog');const [flyerFormat,setFlyerFormat]=useState<FlyerFormat>('png');const [tentFormat,setTentFormat]=useState<TentFormat>('a4');const [customPrompt,setCustomPrompt]=useState('');const [selected,setSelected]=useState<string[]>([]);const [busy,setBusy]=useState(false);const [progress,setProgress]=useState('');const [error,setError]=useState('');const [baseImage,setBaseImage]=useState('');const [jobId,setJobId]=useState('');const [lastCost,setLastCost]=useState(0);const previewRef=useRef<HTMLCanvasElement|null>(null);
  const catalogQrRef=useRef<SVGSVGElement|null>(null);const hubQrRef=useRef<SVGSVGElement|null>(null);
  const catalogUrl=catalog?`${PUBLIC_ORIGIN}/c/${catalog.public_slug}`:'';const hubUrl=catalog?.hub_public_slug?`${PUBLIC_ORIGIN}/h/${catalog.hub_public_slug}`:'';const cost=mode==='custom'?CUSTOM_COST:AUTO_COST;

  useEffect(()=>{let cancelled=false;let current='';const sync=async()=>{const title=document.querySelector('.dash-v3-top h1')?.textContent?.trim()||'';const wrap=document.querySelector('.qr-v3-wrap');if(title!=='QR & partage'||!wrap){setHost(null);return}setHost(wrap);const p=new URLSearchParams(window.location.search);let catalogId=p.get('catalog')||'';if(!catalogId){const src=(wrap.querySelector('.qr-v3-card img') as HTMLImageElement|null)?.getAttribute('src')||'';const m=src.match(/\/api\/qr\/([^?]+)/);if(m){const {data}=await supabase.from('catalogs').select('id').eq('public_slug',decodeURIComponent(m[1])).maybeSingle();catalogId=String(data?.id||'')}}if(!catalogId||catalogId===current)return;current=catalogId;const {data:{session:s}}=await supabase.auth.getSession();if(cancelled||!s)return;setSession(s);const {data:c}=await supabase.from('catalogs').select('id,business_id,title,public_slug,hub_public_slug,description,display_name,logo_url').eq('id',catalogId).maybeSingle();if(cancelled||!c)return;setCatalog(c as CatalogInfo);const [{data:b},{data:w},{data:items}]=await Promise.all([supabase.from('businesses').select('name,description,business_type,logo_url').eq('id',c.business_id).maybeSingle(),supabase.from('credit_wallets').select('balance').eq('business_id',c.business_id).maybeSingle(),supabase.from('items').select('id,name').eq('catalog_id',catalogId).eq('is_available',true).order('sort_order')]);if(cancelled)return;setBusiness(b as BusinessInfo|null);setWallet(Number(w?.balance||0));const ids=(items||[]).map((i:any)=>i.id);if(ids.length){const {data:imgs}=await supabase.from('item_images').select('item_id,image_url,is_primary,created_at').in('item_id',ids).order('is_primary',{ascending:false}).order('created_at',{ascending:false});const map=new Map<string,string>();for(const x of imgs||[])if(x.image_url&&!map.has(String(x.item_id)))map.set(String(x.item_id),String(x.image_url));setRefs((items||[]).filter((i:any)=>map.has(String(i.id))).map((i:any)=>({id:String(i.id),name:String(i.name),image_url:map.get(String(i.id))!})).slice(0,60))}else setRefs([]);setBaseImage('');setSelected([]);setError('')};void sync();const id=setInterval(()=>void sync(),1200);const onChange=()=>{current='';void sync()};document.addEventListener('click',onChange,true);window.addEventListener('popstate',onChange);window.addEventListener('qatalink:catalog-change',onChange as EventListener);return()=>{cancelled=true;clearInterval(id);document.removeEventListener('click',onChange,true);window.removeEventListener('popstate',onChange);window.removeEventListener('qatalink:catalog-change',onChange as EventListener)}},[supabase]);

  function toggleRef(id:string){setSelected(x=>x.includes(id)?x.filter(v=>v!==id):x.length<6?[...x,id]:x)}
  async function generate(){if(!catalog||!session||busy)return;if(wallet<cost){setError(`Solde insuffisant : ${cost} crédits requis, ${wallet} disponibles.`);return}if(mode==='custom'&&!customPrompt.trim()){setError('Ajoutez une direction créative pour le mode personnalisé.');return}setBusy(true);setError('');setProgress('Préparation du support…');setBaseImage('');try{const r=await fetch('/api/marketing-assets/generate',{method:'POST',headers:{'Content-Type':'application/json',Authorization:`Bearer ${session.access_token}`},body:JSON.stringify({catalog_id:catalog.id,asset_type:assetType,generation_mode:mode,qr_mode:qrMode,custom_prompt:customPrompt,reference_item_ids:selected})});const d=await r.json().catch(()=>({}));if(!r.ok)throw new Error(d.message||d.error||'Impossible de lancer la génération.');setWallet(Number(d.balance??wallet-cost));setLastCost(Number(d.credit_cost||cost));setJobId(String(d.job_id||''));setProgress('Création du design…');for(let i=0;i<75;i++){await sleep(2200);const s=await fetch('/api/marketing-assets/status',{method:'POST',headers:{'Content-Type':'application/json',Authorization:`Bearer ${session.access_token}`},body:JSON.stringify({job_id:d.job_id})});const sd=await s.json().catch(()=>({}));if(sd.status==='completed'&&sd.image_url){setBaseImage(sd.image_url);setProgress('Composition du QR et des textes…');await sleep(50);break}if(sd.status==='failed'||(!s.ok&&s.status===409)){if(sd.balance!==undefined)setWallet(Number(sd.balance));throw new Error('La génération a échoué. Les crédits ont été recrédités.')}setProgress(sd.progress?`Création du design… ${Math.round(Number(sd.progress))}%`:'Création du design…')}if(!baseImage&&i===74)throw new Error('La génération prend plus de temps que prévu. Réessayez dans quelques instants.')}catch(e:any){setError(e?.message||'Impossible de générer le support.');setProgress('')}finally{setBusy(false)}}

  async function compose(width=1080,height=1350){if(!baseImage||!catalog||!business)return null;const canvas=document.createElement('canvas');canvas.width=width;canvas.height=height;const ctx=canvas.getContext('2d');if(!ctx)return null;const bg=await loadImage(baseImage);drawCover(ctx,bg,0,0,width,height);const topGrad=ctx.createLinearGradient(0,0,0,height*.34);topGrad.addColorStop(0,'rgba(0,0,0,.72)');topGrad.addColorStop(1,'rgba(0,0,0,0)');ctx.fillStyle=topGrad;ctx.fillRect(0,0,width,height*.38);ctx.fillStyle='#fff';ctx.textAlign='center';ctx.font=`700 ${Math.round(width*.062)}px Arial`;ctx.fillText(clean(catalog.display_name||business.name,50),width/2,height*.105);ctx.font=`500 ${Math.round(width*.025)}px Arial`;ctx.fillStyle='rgba(255,255,255,.92)';ctx.fillText(clean(catalog.title,70),width/2,height*.145);
    const panelY=Math.round(height*.65),panelH=height-panelY;ctx.fillStyle='rgba(255,255,255,.96)';ctx.fillRect(0,panelY,width,panelH);ctx.fillStyle='#151515';ctx.textAlign='center';ctx.font=`700 ${Math.round(width*.034)}px Arial`;const cta=business.business_type==='restaurant'?'Scannez, découvrez la carte et commandez':business.business_type==='hotel'?'Scannez pour découvrir chambres et services':business.business_type==='spa_beauty'?'Scannez pour découvrir prestations et tarifs':'Scannez pour découvrir nos offres';ctx.fillText(cta,width/2,panelY+Math.round(panelH*.13));const bio=clean(catalog.description||business.description,380);if(bio){ctx.font=`400 ${Math.round(width*.022)}px Arial`;ctx.fillStyle='#4a4a4a';const lines=wrapLines(ctx,bio,width*.82,2);lines.forEach((line,i)=>ctx.fillText(line,width/2,panelY+Math.round(panelH*.22)+i*Math.round(width*.031)))}
    const targets:({kind:'catalog'|'hub';url:string;label:string;svg:SVGSVGElement|null})[]=[];if(qrMode==='catalog'||qrMode==='both')targets.push({kind:'catalog',url:catalogUrl,label:'Catalogue / menu',svg:catalogQrRef.current});if((qrMode==='hub'||qrMode==='both')&&hubUrl)targets.push({kind:'hub',url:hubUrl,label:'Page centrale',svg:hubQrRef.current});const qrSize=targets.length===2?Math.round(width*.18):Math.round(width*.23);const gap=Math.round(width*.09);const total=targets.length*qrSize+(targets.length-1)*gap;let x=(width-total)/2;const qy=panelY+Math.round(panelH*.39);for(const t of targets){if(t.svg){const qi=await svgImage(t.svg);ctx.fillStyle='#fff';ctx.fillRect(x-12,qy-12,qrSize+24,qrSize+24);ctx.drawImage(qi,x,qy,qrSize,qrSize)}ctx.fillStyle='#161616';ctx.font=`700 ${Math.round(width*.019)}px Arial`;ctx.fillText(t.label,x+qrSize/2,qy+qrSize+Math.round(width*.035));ctx.font=`400 ${Math.round(width*.013)}px Arial`;ctx.fillStyle='#666';ctx.fillText(t.url.replace(/^https?:\/\//,''),x+qrSize/2,qy+qrSize+Math.round(width*.059));x+=qrSize+gap}ctx.fillStyle='#8f1022';ctx.font=`700 ${Math.round(width*.016)}px Arial`;ctx.fillText('Propulsé par Qatalink',width/2,height-Math.round(width*.025));return canvas}

  async function refreshPreview(){try{const c=await compose();if(!c||!previewRef.current)return;previewRef.current.width=c.width;previewRef.current.height=c.height;previewRef.current.getContext('2d')?.drawImage(c,0,0)}catch{}}
  useEffect(()=>{if(baseImage)void refreshPreview()},[baseImage,qrMode,catalog,business]);
  async function downloadFlyer(){const c=await compose();if(!c)return;const type=flyerFormat==='png'?'image/png':'image/jpeg';c.toBlob(blob=>{if(blob)downloadBlob(blob,`qatalink-${catalog?.public_slug||'flyer'}.${flyerFormat==='jpeg'?'jpg':'png'}`)},type,flyerFormat==='jpeg'?.94:undefined)}
  async function downloadTent(){const design=await compose(1080,1350);if(!design)return;const w=tentFormat==='a4'?1754:1240,h=tentFormat==='a4'?1240:874;const page=document.createElement('canvas');page.width=w;page.height=h;const ctx=page.getContext('2d');if(!ctx)return;ctx.fillStyle='#fff';ctx.fillRect(0,0,w,h);const half=w/2;ctx.save();ctx.translate(half/2,h/2);ctx.rotate(Math.PI);ctx.translate(-half/2,-h/2);drawCover(ctx,design as any,0,0,half,h);ctx.restore();drawCover(ctx,design as any,half,0,half,h);ctx.strokeStyle='#999';ctx.setLineDash([14,12]);ctx.beginPath();ctx.moveTo(half,0);ctx.lineTo(half,h);ctx.stroke();downloadBlob(canvasPdf(page,tentFormat),`qatalink-chevalet-${catalog?.public_slug||'catalogue'}-${tentFormat.toUpperCase()}.pdf`)}

  if(!host||!catalog||!business)return null;
  return createPortal(<section className="dash-card qr-marketing-studio">
    <div className="qr-marketing-head"><div><div className="eyebrow">STUDIO QR · V1</div><h2>Créer un support de vente</h2><p>Flyer PNG/JPEG ou chevalet PDF avec vos vrais QR actifs. Le logo est toujours utilisé lorsqu’il existe et le mode automatique sélectionne jusqu’à 6 visuels d’articles.</p></div><div className="qr-credit-pill"><b>{wallet}</b><span>crédits</span></div></div>
    <div className="qr-marketing-grid">
      <div className="qr-marketing-controls">
        <div className="qr-choice-row"><button className={assetType==='flyer'?'active':''} onClick={()=>setAssetType('flyer')}><FileImage size={17}/>Flyer</button><button className={assetType==='tent_card'?'active':''} onClick={()=>setAssetType('tent_card')}><FileText size={17}/>Chevalet</button></div>
        <div className="field"><label>Mode de création</label><select className="input" value={mode} onChange={e=>setMode(e.target.value as Mode)}><option value="auto">Automatique · {AUTO_COST} crédits</option><option value="custom">Personnalisé · {CUSTOM_COST} crédits</option></select></div>
        <div className="field"><label>QR à afficher</label><select className="input" value={qrMode} onChange={e=>setQrMode(e.target.value as QrMode)}><option value="catalog">Catalogue direct</option>{hubUrl&&<option value="hub">Page centrale</option>}{hubUrl&&<option value="both">Les deux QR</option>}</select></div>
        {assetType==='flyer'?<div className="field"><label>Format de téléchargement</label><select className="input" value={flyerFormat} onChange={e=>setFlyerFormat(e.target.value as FlyerFormat)}><option value="png">PNG</option><option value="jpeg">JPEG</option></select></div>:<div className="field"><label>Format du chevalet</label><select className="input" value={tentFormat} onChange={e=>setTentFormat(e.target.value as TentFormat)}><option value="a4">PDF A4</option><option value="a5">PDF A5</option></select></div>}
        {mode==='custom'&&<><div className="field"><label>Direction créative</label><textarea className="input" rows={4} value={customPrompt} onChange={e=>setCustomPrompt(e.target.value)} placeholder="Ex. ambiance lounge rouge et or, élégante, priorité aux grillades…"/></div><div className="field"><label>Références · {selected.length}/6</label><div className="qr-reference-grid">{refs.slice(0,24).map(r=><button key={r.id} className={selected.includes(r.id)?'selected':''} onClick={()=>toggleRef(r.id)} title={r.name}><img src={r.image_url} alt=""/><span>{r.name}</span></button>)}</div></div></>}
        <button className="btn btn-primary qr-generate-btn" onClick={generate} disabled={busy||wallet<cost}>{busy?<Loader2 className="spin" size={17}/>:<Sparkles size={17}/>}Générer · {cost} crédits</button>{wallet<cost&&<small className="qr-credit-warning">Il vous manque {cost-wallet} crédits.</small>}{progress&&<div className="qr-progress">{progress}</div>}{error&&<div className="qr-error">{error}</div>}
      </div>
      <div className="qr-marketing-preview">{baseImage?<><canvas ref={previewRef}/><div className="qr-download-row">{assetType==='flyer'?<button className="btn btn-primary" onClick={downloadFlyer}><Download size={16}/>Télécharger {flyerFormat.toUpperCase()}</button>:<button className="btn btn-primary" onClick={downloadTent}><Download size={16}/>Télécharger PDF {tentFormat.toUpperCase()}</button>}<button className="btn btn-ghost" onClick={generate}><Sparkles size={15}/>Créer une variante · {cost}</button></div><small>Le QR est ajouté après la génération du visuel : il encode exactement le lien Qatalink actif et reste scannable.</small></>:<div className="qr-empty-preview"><Sparkles size={34}/><b>Votre support apparaîtra ici</b><span>Bio incluse automatiquement · CTA séparé du QR · {mode==='auto'?'sélection automatique des meilleurs visuels':'références choisies par vous'}</span></div>}</div>
    </div>
    <div className="qr-hidden-codes" aria-hidden="true"><QRCodeSVG ref={catalogQrRef} value={catalogUrl} size={360} level="M" marginSize={4}/>{hubUrl&&<QRCodeSVG ref={hubQrRef} value={hubUrl} size={360} level="M" marginSize={4}/>}</div>
    {jobId&&lastCost>0&&<div className="qr-job-note">Dernière création : {lastCost} crédits · génération #{jobId.slice(0,8)}</div>}
  </section>,host);
}
