import {createClient} from '@supabase/supabase-js';
const SUPABASE_URL=process.env.NEXT_PUBLIC_SUPABASE_URL||'https://rifjsvbbhsnpifgooenl.supabase.co';const SUPABASE_KEY=process.env.NEXT_PUBLIC_SUPABASE_PUBLISHABLE_KEY||'';
export function publicDb(){return createClient(SUPABASE_URL,SUPABASE_KEY,{auth:{persistSession:false,autoRefreshToken:false,detectSessionInUrl:false}})}
export async function getPublicCatalogSeo(slug:string){const {data,error}=await publicDb().rpc('get_public_catalog',{p_slug:slug});if(error||!data)return null;return data as any}
export function cleanSeoText(v:unknown,max=260){return String(v||'').replace(/\s+/g,' ').trim().slice(0,max)}
export function itemImage(item:any){return item?.image_url||item?.primary_image_url||item?.image||item?.images?.find?.((x:any)=>x?.is_primary)?.image_url||item?.images?.[0]?.image_url||null}
export function catalogEffective(data:any){const c=data?.catalog||{},b=data?.business||{},categories=Array.isArray(data?.categories)?data.categories:[];const items=Array.isArray(data?.items)?data.items:categories.flatMap((cat:any)=>(Array.isArray(cat?.items)?cat.items:[]).map((item:any)=>({...item,category_name:item.category_name||cat.name,category_id:item.category_id||cat.id})));return {catalog:c,business:{...b,name:c.display_name||b.name,description:c.description||b.description,logo_url:c.logo_url||b.logo_url,cover_url:c.cover_url||b.cover_url},items,categories}}
export function businessSchemaType(type:string){return type==='restaurant'?'Restaurant':type==='retail'?'Store':type==='spa_beauty'?'BeautySalon':type==='hotel'?'Hotel':type==='real_estate'?'RealEstateAgent':'LocalBusiness'}
export function catalogDescription(data:any){const {catalog,business,items}=catalogEffective(data);const names=items.slice(0,7).map((x:any)=>cleanSeoText(x.name,60)).filter(Boolean);const local=[business.neighborhood,business.city].filter(Boolean).join(', ');const base=cleanSeoText(catalog.description||business.description,170);return cleanSeoText(`${base||`Découvrez ${catalog.title||business.name||'ce catalogue'} sur Qatalink.`}${names.length?` Produits et offres : ${names.join(', ')}.`:''}${local?` Disponible à ${local}.`:''}`,300)}
