'use client';

import {useEffect,useMemo,useState} from 'react';
import Link from 'next/link';
import {ArrowLeft,Bell,BellOff,RefreshCw,Send} from 'lucide-react';
import {createSupabaseBrowserClient} from '@/lib/supabase';

type Thread={id:string;user_id:string;user_email:string|null;business_name:string|null;status:string;updated_at:string;last_message:string|null;last_sender:string|null};
type Msg={id:string;thread_id:string;sender_role:'client'|'support';body:string;created_at:string};
const ADMIN_EMAIL='kouameismael@gmail.com';

async function showAdminNotification(body:string){
  if(typeof window==='undefined'||!('Notification'in window)||Notification.permission!=='granted')return;
  try{if('serviceWorker'in navigator){const reg=await navigator.serviceWorker.ready;await reg.showNotification('Nouveau message support',{body,icon:'/qatalink-icon.svg',badge:'/qatalink-icon.svg',data:{url:'/admin/support'}});return}new Notification('Nouveau message support',{body,icon:'/qatalink-icon.svg'})}catch{}
}

export default function AdminSupportPage(){
  const supabase=useMemo(()=>createSupabaseBrowserClient(),[]);
  const [ready,setReady]=useState(false);const [threads,setThreads]=useState<Thread[]>([]);const [selected,setSelected]=useState<Thread|null>(null);const [messages,setMessages]=useState<Msg[]>([]);const [text,setText]=useState('');const [userId,setUserId]=useState('');const [busy,setBusy]=useState(false);const [notifications,setNotifications]=useState(false);const [notice,setNotice]=useState('');
  async function loadThreads(){const {data}=await supabase.rpc('qatalink_support_inbox');const list=(data||[]) as Thread[];setThreads(list);if(selected){const fresh=list.find(t=>t.id===selected.id)||null;setSelected(fresh)}else if(list[0])setSelected(list[0])}
  async function loadMessages(threadId:string){const {data}=await supabase.from('support_messages').select('id,thread_id,sender_role,body,created_at').eq('thread_id',threadId).order('created_at',{ascending:true});setMessages((data||[]) as Msg[])}
  useEffect(()=>{(async()=>{const {data:{session}}=await supabase.auth.getSession();if(!session){window.location.replace('/login');return}if(session.user.email?.toLowerCase()!==ADMIN_EMAIL){window.location.replace('/dashboard');return}setUserId(session.user.id);const {data:p}=await supabase.from('profiles').select('support_notifications_enabled').eq('id',session.user.id).maybeSingle();setNotifications(Boolean(p?.support_notifications_enabled));await loadThreads();setReady(true)})()},[]);
  useEffect(()=>{if(selected)loadMessages(selected.id)},[selected?.id]);
  useEffect(()=>{if(!ready)return;const channel=supabase.channel('support-admin-inbox').on('postgres_changes',{event:'INSERT',schema:'public',table:'support_messages'},(payload:any)=>{const msg=payload.new as Msg;if(msg.sender_role==='client'){void loadThreads();if(selected?.id===msg.thread_id)setMessages(prev=>prev.some(x=>x.id===msg.id)?prev:[...prev,msg]);if(notifications){const thread=threads.find(t=>t.id===msg.thread_id);void showAdminNotification(thread?.business_name?`${thread.business_name} vous a écrit.`:'Un client vous a écrit.')}}}).subscribe();return()=>{void supabase.removeChannel(channel)}},[supabase,ready,selected?.id,notifications,threads]);
  async function toggleNotifications(){if(!userId)return;if(notifications){await supabase.from('profiles').update({support_notifications_enabled:false}).eq('id',userId);setNotifications(false);setNotice('Notifications désactivées.');return}if(typeof window==='undefined'||!('Notification'in window)){setNotice('Les notifications ne sont pas disponibles sur ce navigateur.');return}const permission=await Notification.requestPermission();if(permission!=='granted'){setNotice('Autorisez les notifications dans votre navigateur.');return}const {error}=await supabase.from('profiles').update({support_notifications_enabled:true}).eq('id',userId);if(error){setNotice('Impossible d’activer les notifications pour le moment.');return}setNotifications(true);setNotice('Notifications support activées.')}
  async function send(){if(!selected||!text.trim()||!userId)return;setBusy(true);await supabase.from('support_messages').insert({thread_id:selected.id,sender_user_id:userId,sender_role:'support',body:text.trim()});setText('');await loadMessages(selected.id);await loadThreads();setBusy(false)}
  if(!ready)return <div className="admin-loading">Chargement du support…</div>;
  return <main className="admin-shell"><header className="admin-top"><div><span className="eyebrow">QATALINK ADMIN</span><h1>Support</h1><p>Répondez aux utilisateurs sans exposer votre identité personnelle. Ils voient uniquement « Support Qatalink ».</p></div><div className="admin-actions"><Link className="btn btn-ghost" href="/admin"><ArrowLeft size={15}/>Administration</Link><button className={'btn btn-ghost '+(notifications?'active':'')} onClick={toggleNotifications}>{notifications?<Bell size={15}/>:<BellOff size={15}/>} {notifications?'Notifications activées':'Activer les notifications'}</button><button className="btn btn-primary" onClick={loadThreads}><RefreshCw size={15}/>Actualiser</button></div></header>
    {notice&&<div className="admin-error">{notice}</div>}
    <section style={{display:'grid',gridTemplateColumns:'minmax(260px,.8fr) minmax(0,1.6fr)',gap:16,minHeight:'65vh'}}>
      <div className="admin-card" style={{padding:12,overflow:'auto'}}>{threads.length?threads.map(t=><button key={t.id} onClick={()=>setSelected(t)} style={{width:'100%',textAlign:'left',padding:'12px',borderRadius:14,border:selected?.id===t.id?'1px solid #c7192f':'1px solid var(--line)',background:selected?.id===t.id?'rgba(199,25,47,.06)':'transparent',marginBottom:8}}><b>{t.business_name||'Utilisateur Qatalink'}</b><small style={{display:'block',color:'var(--muted)',marginTop:3}}>{t.user_email||'Compte utilisateur'}</small><span style={{display:'block',marginTop:7,fontSize:12,whiteSpace:'nowrap',overflow:'hidden',textOverflow:'ellipsis'}}>{t.last_message||'Aucun message'}</span></button>):<p>Aucune conversation pour le moment.</p>}</div>
      <div className="admin-card" style={{display:'grid',gridTemplateRows:'auto minmax(260px,1fr) auto',padding:0,overflow:'hidden'}}>{selected?<><div style={{padding:'16px 18px',borderBottom:'1px solid var(--line)'}}><b>{selected.business_name||'Utilisateur Qatalink'}</b><small style={{display:'block',color:'var(--muted)'}}>{selected.user_email}</small></div><div style={{padding:18,overflow:'auto',display:'flex',flexDirection:'column',gap:10}}>{messages.map(m=><div key={m.id} style={{alignSelf:m.sender_role==='support'?'flex-end':'flex-start',maxWidth:'82%',padding:'11px 13px',borderRadius:14,background:m.sender_role==='support'?'rgba(199,25,47,.10)':'var(--surface-2)'}}><b style={{fontSize:12}}>{m.sender_role==='support'?'Support Qatalink':'Client'}</b><p style={{margin:'5px 0',whiteSpace:'pre-wrap'}}>{m.body}</p><small style={{color:'var(--muted)'}}>{new Date(m.created_at).toLocaleString('fr-FR')}</small></div>)}</div><div style={{display:'grid',gridTemplateColumns:'minmax(0,1fr) 48px',gap:8,padding:14,borderTop:'1px solid var(--line)'}}><textarea className="input" rows={2} value={text} onChange={e=>setText(e.target.value)} placeholder="Répondre en tant que Support Qatalink…"/><button className="btn btn-primary" onClick={send} disabled={busy||!text.trim()}><Send size={16}/></button></div></>:<div style={{padding:30}}>Sélectionnez une conversation.</div>}</div>
    </section>
  </main>;
}
