'use client';

import {useEffect,useMemo,useState} from 'react';
import Link from 'next/link';
import {ArrowLeft,Bell,BellOff,Bot,Headphones,RefreshCw,Send} from 'lucide-react';
import {createSupabaseBrowserClient} from '@/lib/supabase';

type Thread={id:string;user_id:string|null;visitor_id:string|null;user_email:string|null;business_name:string|null;status:string;mode:'ai'|'human';source:string;ai_handoff_requested:boolean;updated_at:string;last_message:string|null;last_sender:string|null};
type Msg={id:string;thread_id:string;sender_role:'client'|'support'|'assistant'|'system';body:string;created_at:string};
type Filter='all'|'ai'|'human'|'handoff';
const ADMIN_EMAIL='kouameismael@gmail.com';

async function showAdminNotification(body:string){
  if(typeof window==='undefined'||!('Notification'in window)||Notification.permission!=='granted')return;
  try{if('serviceWorker'in navigator){const reg=await navigator.serviceWorker.ready;await reg.showNotification('Nouveau message Qatalink',{body,icon:'/qatalink-icon.svg',badge:'/qatalink-icon.svg',data:{url:'/admin/support'}});return}new Notification('Nouveau message Qatalink',{body,icon:'/qatalink-icon.svg'})}catch{}
}
function senderLabel(role:Msg['sender_role']){if(role==='support')return'Support Qatalink';if(role==='assistant')return'Assistant Qatalink';if(role==='system')return'Qatalink';return'Client'}

export default function AdminSupportPage(){
  const supabase=useMemo(()=>createSupabaseBrowserClient(),[]);
  const [ready,setReady]=useState(false);const [threads,setThreads]=useState<Thread[]>([]);const [selected,setSelected]=useState<Thread|null>(null);const [messages,setMessages]=useState<Msg[]>([]);const [text,setText]=useState('');const [userId,setUserId]=useState('');const [busy,setBusy]=useState(false);const [notifications,setNotifications]=useState(false);const [notice,setNotice]=useState('');const [filter,setFilter]=useState<Filter>('all');
  async function loadThreads(){const {data}=await supabase.rpc('qatalink_support_inbox');const list=(data||[]) as Thread[];setThreads(list);if(selected){const fresh=list.find(t=>t.id===selected.id)||null;setSelected(fresh)}else if(list[0])setSelected(list[0])}
  async function loadMessages(threadId:string){const {data}=await supabase.from('support_messages').select('id,thread_id,sender_role,body,created_at').eq('thread_id',threadId).order('created_at',{ascending:true});setMessages((data||[]) as Msg[])}
  useEffect(()=>{(async()=>{const {data:{session}}=await supabase.auth.getSession();if(!session){window.location.replace('/login');return}if(session.user.email?.toLowerCase()!==ADMIN_EMAIL){window.location.replace('/dashboard');return}setUserId(session.user.id);const {data:p}=await supabase.from('profiles').select('support_notifications_enabled').eq('id',session.user.id).maybeSingle();setNotifications(Boolean(p?.support_notifications_enabled));await loadThreads();setReady(true)})()},[]);
  useEffect(()=>{if(selected)loadMessages(selected.id)},[selected?.id]);
  useEffect(()=>{if(!ready)return;const channel=supabase.channel('support-admin-inbox').on('postgres_changes',{event:'INSERT',schema:'public',table:'support_messages'},(payload:any)=>{const msg=payload.new as Msg;if(msg.sender_role==='client'){void loadThreads();if(selected?.id===msg.thread_id)setMessages(prev=>prev.some(x=>x.id===msg.id)?prev:[...prev,msg]);if(notifications){const thread=threads.find(t=>t.id===msg.thread_id);void showAdminNotification(thread?.business_name?`${thread.business_name} vous a écrit.`:'Un utilisateur Qatalink vous a écrit.')}}else if(selected?.id===msg.thread_id)setMessages(prev=>prev.some(x=>x.id===msg.id)?prev:[...prev,msg])}).subscribe();return()=>{void supabase.removeChannel(channel)}},[supabase,ready,selected?.id,notifications,threads]);
  async function toggleNotifications(){if(!userId)return;if(notifications){await supabase.from('profiles').update({support_notifications_enabled:false}).eq('id',userId);setNotifications(false);setNotice('Notifications désactivées.');return}if(typeof window==='undefined'||!('Notification'in window)){setNotice('Les notifications ne sont pas disponibles sur ce navigateur.');return}const permission=await Notification.requestPermission();if(permission!=='granted'){setNotice('Autorisez les notifications dans votre navigateur pour les recevoir.');return}const {error}=await supabase.from('profiles').update({support_notifications_enabled:true}).eq('id',userId);if(error){setNotice('Impossible d’activer les notifications pour le moment.');return}setNotifications(true);setNotice('Notifications support activées.')}
  async function send(){if(!selected||!text.trim()||!userId)return;setBusy(true);await supabase.from('support_threads').update({mode:'human',ai_handoff_requested:false,status:'open'}).eq('id',selected.id);await supabase.from('support_messages').insert({thread_id:selected.id,sender_user_id:userId,sender_role:'support',body:text.trim()});setText('');await loadMessages(selected.id);await loadThreads();setBusy(false)}
  if(!ready)return <div className="admin-loading">Chargement des conversations…</div>;
  const filtered=threads.filter(t=>filter==='all'||(filter==='handoff'?t.ai_handoff_requested:t.mode===filter));
  const aiCount=threads.filter(t=>t.mode==='ai').length;const humanCount=threads.filter(t=>t.mode==='human').length;const handoffCount=threads.filter(t=>t.ai_handoff_requested).length;
  return <main className="admin-shell"><header className="admin-top"><div><span className="eyebrow">QATALINK ADMIN</span><h1>Conversations & support</h1><p>Vous voyez ici les conversations de l’Assistant Qatalink et celles reprises par le support humain. Une réponse de votre part bascule automatiquement la conversation en mode humain.</p></div><div className="admin-actions"><Link className="btn btn-ghost" href="/admin"><ArrowLeft size={15}/>Administration</Link><button className={'btn btn-ghost '+(notifications?'active':'')} onClick={toggleNotifications}>{notifications?<Bell size={15}/>:<BellOff size={15}/>} {notifications?'Notifications activées':'Activer les notifications'}</button><button className="btn btn-primary" onClick={loadThreads}><RefreshCw size={15}/>Actualiser</button></div></header>
    {notice&&<div className="admin-error">{notice}</div>}
    <div className="admin-periods" style={{marginBottom:14}}><button className={filter==='all'?'active':''} onClick={()=>setFilter('all')}>Toutes · {threads.length}</button><button className={filter==='ai'?'active':''} onClick={()=>setFilter('ai')}><Bot size={13}/> IA · {aiCount}</button><button className={filter==='human'?'active':''} onClick={()=>setFilter('human')}><Headphones size={13}/> Humain · {humanCount}</button><button className={filter==='handoff'?'active':''} onClick={()=>setFilter('handoff')}>À reprendre · {handoffCount}</button></div>
    <section style={{display:'grid',gridTemplateColumns:'minmax(280px,.82fr) minmax(0,1.6fr)',gap:16,minHeight:'65vh'}}>
      <div className="admin-card" style={{padding:12,overflow:'auto'}}>{filtered.length?filtered.map(t=><button key={t.id} onClick={()=>setSelected(t)} style={{width:'100%',textAlign:'left',padding:'12px',borderRadius:14,border:selected?.id===t.id?'1px solid #c7192f':'1px solid var(--line)',background:selected?.id===t.id?'rgba(199,25,47,.06)':'transparent',marginBottom:8}}><div style={{display:'flex',alignItems:'center',justifyContent:'space-between',gap:8}}><b>{t.business_name||t.user_email||'Visiteur Qatalink'}</b><span style={{fontSize:10,fontWeight:850,padding:'4px 7px',borderRadius:999,background:t.mode==='ai'?'rgba(124,58,237,.10)':'rgba(199,25,47,.10)',color:t.mode==='ai'?'#6d28d9':'#a91428'}}>{t.mode==='ai'?'IA':'HUMAIN'}</span></div><small style={{display:'block',color:'var(--muted)',marginTop:3}}>{t.user_email||`${t.source==='landing'?'Visiteur landing':'Visiteur'} · ${t.visitor_id?.slice(-8)||'anonyme'}`}</small>{t.ai_handoff_requested&&<small style={{display:'block',color:'#a91428',fontWeight:800,marginTop:5}}>Intervention humaine recommandée</small>}<span style={{display:'block',marginTop:7,fontSize:12,whiteSpace:'nowrap',overflow:'hidden',textOverflow:'ellipsis'}}>{t.last_message||'Aucun message'}</span></button>):<p>Aucune conversation dans ce filtre.</p>}</div>
      <div className="admin-card" style={{display:'grid',gridTemplateRows:'auto minmax(260px,1fr) auto',padding:0,overflow:'hidden'}}>{selected?<><div style={{padding:'16px 18px',borderBottom:'1px solid var(--line)',display:'flex',justifyContent:'space-between',gap:12,alignItems:'center'}}><div><b>{selected.business_name||selected.user_email||'Visiteur Qatalink'}</b><small style={{display:'block',color:'var(--muted)'}}>{selected.user_email||`Source : ${selected.source||'web'}`}</small></div><span style={{fontSize:11,fontWeight:850,padding:'6px 9px',borderRadius:999,background:selected.mode==='ai'?'rgba(124,58,237,.10)':'rgba(199,25,47,.10)',color:selected.mode==='ai'?'#6d28d9':'#a91428'}}>{selected.mode==='ai'?'ASSISTANT IA':'SUPPORT HUMAIN'}</span></div><div style={{padding:18,overflow:'auto',display:'flex',flexDirection:'column',gap:10}}>{messages.map(m=><div key={m.id} style={{alignSelf:m.sender_role==='client'?'flex-start':'flex-end',maxWidth:'84%',padding:'11px 13px',borderRadius:14,background:m.sender_role==='support'?'rgba(199,25,47,.10)':m.sender_role==='assistant'?'rgba(124,58,237,.09)':'var(--surface-2)',border:m.sender_role==='assistant'?'1px solid rgba(124,58,237,.14)':'none'}}><b style={{fontSize:12}}>{senderLabel(m.sender_role)}</b><p style={{margin:'5px 0',whiteSpace:'pre-wrap',lineHeight:1.5}}>{m.body}</p><small style={{color:'var(--muted)'}}>{new Date(m.created_at).toLocaleString('fr-FR')}</small></div>)}</div><div style={{display:'grid',gridTemplateColumns:'minmax(0,1fr) 48px',gap:8,padding:14,borderTop:'1px solid var(--line)'}}><textarea className="input" rows={2} value={text} onChange={e=>setText(e.target.value)} placeholder="Répondre en tant que Support Qatalink…"/><button className="btn btn-primary" onClick={send} disabled={busy||!text.trim()}><Send size={16}/></button></div></>:<div style={{padding:30}}>Sélectionnez une conversation.</div>}</div>
    </section>
  </main>;
}
