import type {Metadata} from 'next';
import Link from 'next/link';
import {notFound} from 'next/navigation';
import {createClient} from '@supabase/supabase-js';
import {SeoMarkdown} from '@/components/seo-markdown';

export const revalidate=300;
const SUPABASE_URL=process.env.NEXT_PUBLIC_SUPABASE_URL||'https://rifjsvbbhsnpifgooenl.supabase.co';const SUPABASE_KEY=process.env.NEXT_PUBLIC_SUPABASE_PUBLISHABLE_KEY||'';
function db(){return createClient(SUPABASE_URL,SUPABASE_KEY,{auth:{persistSession:false,autoRefreshToken:false}})}
async function getPost(slug:string){const {data}=await db().from('seo_blog_posts').select('*').eq('slug',slug).eq('status','published').maybeSingle();return data}

export async function generateMetadata({params}:{params:Promise<{slug:string}>}):Promise<Metadata>{const {slug}=await params;const p=await getPost(slug);if(!p)return {title:{absolute:'Article introuvable | Qatalink'}};const url=`https://qatalink.com/blog/${p.slug}`;const metaTitle=String(p.meta_title||p.title).replace(/\s*\|\s*Qatalink\s*$/i,'').trim();const absoluteTitle=`${metaTitle} | Qatalink`;return {title:{absolute:absoluteTitle},description:p.meta_description||p.excerpt,keywords:p.keywords||[],alternates:{canonical:url},openGraph:{title:absoluteTitle,description:p.meta_description||p.excerpt,url,type:'article',publishedTime:p.published_at||undefined,siteName:'Qatalink'},twitter:{card:'summary_large_image',title:absoluteTitle,description:p.meta_description||p.excerpt}}}

export default async function ArticlePage({params}:{params:Promise<{slug:string}>}){const {slug}=await params;const p=await getPost(slug);if(!p)notFound();const canonical=`https://qatalink.com/blog/${p.slug}`;const faq=Array.isArray(p.faq)?p.faq:[];const articleLd={"@context":"https://schema.org","@type":"Article",headline:p.title,description:p.excerpt,datePublished:p.published_at,dateModified:p.updated_at,mainEntityOfPage:canonical,author:{"@type":"Organization",name:'Qatalink'},publisher:{"@type":"Organization",name:'Qatalink',url:'https://qatalink.com',logo:{"@type":"ImageObject",url:'https://qatalink.com/qatalink-icon.svg'}},about:(p.keywords||[]).map((name:string)=>({"@type":"Thing",name})),spatialCoverage:p.city?{"@type":"Place",name:`${p.city}${p.country?`, ${p.country}`:''}`}:undefined};const faqLd=faq.length?{"@context":"https://schema.org","@type":"FAQPage",mainEntity:faq.map((x:any)=>({"@type":"Question",name:x.question,acceptedAnswer:{"@type":"Answer",text:x.answer}}))}:null;return <main className="seo-shell seo-article-shell"><script type="application/ld+json" dangerouslySetInnerHTML={{__html:JSON.stringify(articleLd)}}/>{faqLd&&<script type="application/ld+json" dangerouslySetInnerHTML={{__html:JSON.stringify(faqLd)}}/>}<nav className="seo-breadcrumb"><Link href="/">Qatalink</Link><span>›</span><Link href="/blog">Blog</Link><span>›</span><span>{p.title}</span></nav><article className="seo-article"><header><div className="eyebrow">GUIDE QATALINK · {p.city||'AFRIQUE FRANCOPHONE'}</div><h1>{p.title}</h1><p className="seo-lead">{p.excerpt}</p><div className="seo-card-meta"><span>{p.published_at?new Intl.DateTimeFormat('fr-FR',{dateStyle:'long'}).format(new Date(p.published_at)):''}</span><span>Rédaction assistée par {p.model||'Gemini'} via PoYo · sous règles éditoriales Qatalink</span></div></header><SeoMarkdown markdown={p.content_markdown}/>{faq.length>0&&<section className="seo-faq"><h2>Questions fréquentes</h2>{faq.map((x:any,i:number)=><details key={i}><summary>{x.question}</summary><p>{x.answer}</p></details>)}</section>}<section className="seo-cta"><h2>Passez de la lecture à votre propre catalogue</h2><p>Créez votre menu ou catalogue Qatalink, partagez-le par QR code et faites évoluer vos informations sans réimprimer votre support.</p><div className="seo-actions"><Link className="btn btn-primary" href="/create">Créer mon Qatalink</Link><Link className="btn btn-ghost" href="/docs">Comprendre toutes les fonctionnalités</Link></div></section></article></main>}
