import Link from 'next/link';

export const metadata={
  title:'Politique de confidentialité — Qatalink',
  description:'Politique de confidentialité de Qatalink, service édité par Digital ADN.'
};

export default function PrivacyPage(){return <main className="legal-page"><div className="legal-shell">
  <div className="legal-top"><Link href="/" className="brand">← Qatalink</Link><span>Digital ADN</span></div>
  <header className="legal-hero"><div className="eyebrow">DONNÉES PERSONNELLES</div><h1>Politique de confidentialité</h1><p>Version du 19 août 2026 · Cette politique explique comment Digital ADN traite les données personnelles dans le cadre de Qatalink.</p></header>

  <section><h2>1. Responsable du traitement</h2><p>Qatalink est édité et exploité par <strong>Digital ADN</strong>, service numérique basé en Côte d’Ivoire. Pour les données nécessaires à la création des comptes, à la facturation, à la sécurité, au support et au fonctionnement général de Qatalink, Digital ADN détermine les finalités et moyens du traitement.</p><p>Lorsqu’un professionnel utilise Qatalink pour collecter des informations de ses propres clients dans le cadre d’une commande, d’une réservation ou d’une prise de contact, ce professionnel détermine généralement les finalités commerciales de cette collecte. Digital ADN intervient alors comme prestataire technique pour l’exécution du service, sous réserve des traitements que Digital ADN réalise pour ses propres obligations de sécurité, de facturation ou de conformité.</p></section>

  <section><h2>2. Cadre applicable</h2><p>Digital ADN tient compte notamment de la loi ivoirienne n° 2013-450 du 19 juin 2013 relative à la protection des données à caractère personnel, de ses textes d’application, ainsi que des règles applicables aux transactions électroniques et aux services numériques en Côte d’Ivoire.</p></section>

  <section><h2>3. Données pouvant être traitées</h2><p>Selon votre utilisation de Qatalink, les catégories de données peuvent comprendre :</p><ul><li><strong>Données de compte :</strong> nom, adresse e-mail, identifiant utilisateur, informations d’authentification et préférences.</li><li><strong>Données d’entreprise :</strong> nom commercial, secteur, coordonnées, numéro WhatsApp, téléphone, adresse, logo, images et informations publiques du catalogue.</li><li><strong>Contenus de catalogue :</strong> noms de produits ou services, descriptions, prix, catégories, photos, promotions et paramètres visuels.</li><li><strong>Données de commande :</strong> articles choisis, quantités, montant, statut, numéro de table, nom, téléphone, adresse de livraison, note ou autres champs saisis par le client final lorsque le professionnel active ces fonctions.</li><li><strong>Données de paiement et d’abonnement :</strong> formule, période, montant, devise, statut de paiement et identifiants de transaction. Les informations confidentielles complètes de carte ou de portefeuille de paiement sont traitées directement par le prestataire de paiement lorsque celui-ci les collecte.</li><li><strong>Données d’utilisation :</strong> pages consultées, scans de QR code, interactions avec les catalogues, ajouts au panier, ouvertures de WhatsApp, identifiant de session, référent, navigateur ou informations techniques similaires.</li><li><strong>Données de support :</strong> messages, demandes, réponses et informations nécessaires à la résolution d’un incident.</li><li><strong>Données utilisées pour les fonctions IA :</strong> nom et description d’un article, image ou consigne fournie lorsque l’utilisateur demande une génération ou une amélioration de contenu.</li></ul></section>

  <section><h2>4. Finalités des traitements</h2><p>Ces données peuvent être utilisées pour créer et sécuriser les comptes, fournir les catalogues publics, traiter les commandes et demandes, gérer les abonnements et crédits, assurer le support, détecter les abus, mesurer l’utilisation du service, améliorer Qatalink, générer les contenus demandés par l’utilisateur, assurer la continuité technique et respecter les obligations légales ou réglementaires.</p></section>

  <section><h2>5. Fondements du traitement</h2><p>Selon la situation, les traitements reposent sur l’exécution du service demandé ou du contrat d’abonnement, le respect d’obligations légales, le consentement lorsqu’il est requis, ou les intérêts légitimes liés à la sécurité, à la prévention de la fraude, au support et à l’amélioration du service, dans les limites prévues par la réglementation applicable.</p></section>

  <section><h2>6. Données des clients finaux</h2><p>Le professionnel qui publie un catalogue Qatalink doit informer ses propres clients de l’usage des informations qu’il leur demande et ne collecter que les données nécessaires à sa prestation. Il lui appartient également de respecter les obligations qui lui incombent en qualité de responsable du traitement pour ses finalités propres.</p><p>Digital ADN ne vend pas les données de commande des clients finaux à des annonceurs.</p></section>

  <section><h2>7. Prestataires techniques</h2><p>Digital ADN peut faire appel à des prestataires spécialisés pour l’hébergement, l’authentification, le stockage, la livraison de contenu, le paiement, la génération d’images ou de textes, l’analyse d’usage, la sécurité ou le support. Ils ne reçoivent que les données nécessaires à leur mission et sont sélectionnés en tenant compte des garanties techniques et organisationnelles attendues.</p></section>

  <section><h2>8. Transferts internationaux</h2><p>Certains prestataires techniques peuvent traiter ou héberger des données en dehors de la Côte d’Ivoire. Lorsqu’un transfert international est soumis à des obligations ou formalités particulières, Digital ADN doit respecter les exigences prévues par la réglementation ivoirienne applicable, notamment en matière d’information, de garanties et, lorsque requis, d’autorisation de l’autorité compétente.</p></section>

  <section><h2>9. Durée de conservation</h2><p>Les données sont conservées pendant la durée nécessaire aux finalités pour lesquelles elles sont traitées. Les informations du compte et des catalogues sont généralement conservées tant que le compte est actif ou pendant la période nécessaire pour permettre une réactivation, une restitution ou une suppression. Les données de facturation, de sécurité ou de preuve peuvent être conservées plus longtemps lorsqu’une obligation légale, comptable, fiscale ou contentieuse le justifie.</p><p>Lorsqu’une donnée n’est plus nécessaire et qu’aucune obligation ne justifie sa conservation, elle est supprimée, anonymisée ou rendue inaccessible selon les possibilités techniques applicables.</p></section>

  <section><h2>10. Sécurité</h2><p>Digital ADN met en œuvre des mesures techniques et organisationnelles destinées à protéger les données contre l’accès non autorisé, la perte, l’altération ou la divulgation. Aucune plateforme ne pouvant garantir un risque nul, les utilisateurs doivent également protéger leurs identifiants, utiliser des mots de passe robustes et signaler rapidement toute activité suspecte.</p></section>

  <section><h2>11. Mesure d’audience et technologies de suivi</h2><p>Qatalink peut utiliser des technologies de mesure d’audience, de conversion et de performance pour comprendre l’utilisation du site, mesurer l’efficacité de campagnes ou améliorer le parcours utilisateur. Ces technologies peuvent utiliser des cookies, identifiants de navigateur ou mécanismes similaires. Les paramètres du navigateur ou du terminal peuvent permettre de limiter certaines de ces technologies, sous réserve de leur rôle dans le fonctionnement du service.</p></section>

  <section><h2>12. Vos droits</h2><p>Dans les conditions prévues par la loi ivoirienne relative à la protection des données personnelles, une personne concernée peut notamment exercer des droits d’information, d’accès, de rectification, d’opposition, de suppression ou d’effacement lorsque les conditions légales sont réunies.</p><p>Une demande peut être adressée à Digital ADN via le support intégré à Qatalink. Pour protéger la personne concernée, une vérification raisonnable de son identité peut être demandée avant de communiquer, rectifier ou supprimer certaines informations.</p></section>

  <section><h2>13. Réclamation auprès de l’autorité de protection</h2><p>En Côte d’Ivoire, l’Autorité de Régulation des Télécommunications/TIC de Côte d’Ivoire (ARTCI) exerce les missions d’Autorité de protection des données personnelles. Une personne concernée peut s’adresser à l’autorité compétente lorsqu’elle estime que ses droits ne sont pas respectés.</p></section>

  <section><h2>14. Données sensibles</h2><p>Qatalink n’est pas conçu pour collecter des données sensibles sans nécessité spécifique. Les utilisateurs ne doivent pas détourner les champs de catalogue, de commande ou de support pour collecter des données de santé, biométriques, politiques, religieuses ou d’autres données sensibles sans disposer d’une base légale et, lorsque requis, des autorisations appropriées.</p></section>

  <section><h2>15. Mineurs</h2><p>Qatalink est destiné à l’usage professionnel et n’est pas conçu comme un service destiné aux enfants. Un utilisateur professionnel ne doit pas collecter via Qatalink des données concernant des mineurs lorsqu’une telle collecte n’est pas nécessaire ou licite.</p></section>

  <section><h2>16. Modification de la politique</h2><p>Cette politique peut évoluer pour refléter les changements de Qatalink, de ses traitements ou du cadre réglementaire. La date de dernière mise à jour est indiquée en tête du document. Une information supplémentaire peut être affichée dans l’interface lorsqu’une modification est substantielle.</p></section>

  <section><h2>17. Contact</h2><p>Pour exercer un droit ou poser une question sur la protection des données, contactez Digital ADN via le support intégré à Qatalink en précisant qu’il s’agit d’une demande relative aux données personnelles.</p></section>

  <div className="legal-bottom"><Link href="/cgu">Conditions Générales d’Utilisation</Link><Link href="/">Retour à Qatalink</Link></div>
</div></main>}
